// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: audit.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAuditEvents = `-- name: CountAuditEvents :one
SELECT count(*)::bigint
FROM audit_events AS e
WHERE ($1::text IS NULL OR e.object_type = $1::text)
  AND ($2::bigint IS NULL OR e.object_id = $2::bigint)
  AND ($3::bigint IS NULL OR e.actor_user_id = $3::bigint)
  AND ($4::text IS NULL OR e.action = $4::text)
`

type CountAuditEventsParams struct {
	ObjectType pgtype.Text `db:"object_type" json:"object_type"`
	ObjectID   pgtype.Int8 `db:"object_id" json:"object_id"`
	ActorID    pgtype.Int8 `db:"actor_id" json:"actor_id"`
	Action     pgtype.Text `db:"action" json:"action"`
}

func (q *Queries) CountAuditEvents(ctx context.Context, arg CountAuditEventsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditEvents,
		arg.ObjectType,
		arg.ObjectID,
		arg.ActorID,
		arg.Action,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const listAuditEvents = `-- name: ListAuditEvents :many
SELECT
    e.id,
    e.actor_user_id,
    u.username AS actor_username,
    e.action,
    e.object_type,
    e.object_id,
    e.reason,
    e.metadata,
    e.created_at
FROM audit_events AS e
LEFT JOIN users AS u ON u.id = e.actor_user_id
WHERE ($1::text IS NULL OR e.object_type = $1::text)
  AND ($2::bigint IS NULL OR e.object_id = $2::bigint)
  AND ($3::bigint IS NULL OR e.actor_user_id = $3::bigint)
  AND ($4::text IS NULL OR e.action = $4::text)
ORDER BY e.created_at DESC, e.id DESC
LIMIT $6 OFFSET $5
`

type ListAuditEventsParams struct {
	ObjectType pgtype.Text `db:"object_type" json:"object_type"`
	ObjectID   pgtype.Int8 `db:"object_id" json:"object_id"`
	ActorID    pgtype.Int8 `db:"actor_id" json:"actor_id"`
	Action     pgtype.Text `db:"action" json:"action"`
	Offset     int32       `db:"offset" json:"offset"`
	Limit      int32       `db:"limit" json:"limit"`
}

type ListAuditEventsRow struct {
	ID            int64              `db:"id" json:"id"`
	ActorUserID   pgtype.Int8        `db:"actor_user_id" json:"actor_user_id"`
	ActorUsername pgtype.Text        `db:"actor_username" json:"actor_username"`
	Action        string             `db:"action" json:"action"`
	ObjectType    string             `db:"object_type" json:"object_type"`
	ObjectID      pgtype.Int8        `db:"object_id" json:"object_id"`
	Reason        string             `db:"reason" json:"reason"`
	Metadata      []byte             `db:"metadata" json:"metadata"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]ListAuditEventsRow, error) {
	rows, err := q.db.Query(ctx, listAuditEvents,
		arg.ObjectType,
		arg.ObjectID,
		arg.ActorID,
		arg.Action,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuditEventsRow
	for rows.Next() {
		var i ListAuditEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.ActorUserID,
			&i.ActorUsername,
			&i.Action,
			&i.ObjectType,
			&i.ObjectID,
			&i.Reason,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
