// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: contests.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addContestProblem = `-- name: AddContestProblem :one
INSERT INTO contest_problems (
    contest_id,
    problem_id,
    alias,
    sort_order
) VALUES (
    $1, $2, $3, $4
)
RETURNING contest_id, problem_id, alias, sort_order
`

type AddContestProblemParams struct {
	ContestID int64  `db:"contest_id" json:"contest_id"`
	ProblemID int64  `db:"problem_id" json:"problem_id"`
	Alias     string `db:"alias" json:"alias"`
	SortOrder int32  `db:"sort_order" json:"sort_order"`
}

func (q *Queries) AddContestProblem(ctx context.Context, arg AddContestProblemParams) (ContestProblem, error) {
	row := q.db.QueryRow(ctx, addContestProblem,
		arg.ContestID,
		arg.ProblemID,
		arg.Alias,
		arg.SortOrder,
	)
	var i ContestProblem
	err := row.Scan(
		&i.ContestID,
		&i.ProblemID,
		&i.Alias,
		&i.SortOrder,
	)
	return i, err
}

const archiveContest = `-- name: ArchiveContest :one
UPDATE contests
SET status = 'archived',
    updated_at = now()
WHERE id = $1
RETURNING id, owner_user_id, title, description, visibility, status, start_at, end_at, freeze_at, invite_code_hash, created_at, updated_at
`

func (q *Queries) ArchiveContest(ctx context.Context, id int64) (Contest, error) {
	row := q.db.QueryRow(ctx, archiveContest, id)
	var i Contest
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Title,
		&i.Description,
		&i.Visibility,
		&i.Status,
		&i.StartAt,
		&i.EndAt,
		&i.FreezeAt,
		&i.InviteCodeHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countContests = `-- name: CountContests :one
SELECT count(*)::bigint
FROM contests c
WHERE ($1::text IS NULL OR c.status = $1::text)
  AND ($2::text IS NULL OR c.visibility = $2::text)
  AND (
      $3::text IS NULL
      OR c.title ILIKE '%' || $3::text || '%'
  )
  AND (
      $4::boolean
      OR c.visibility = 'public'
      OR (
          $5::bigint IS NOT NULL
          AND (
              c.owner_user_id = $5::bigint
              OR EXISTS (
                  SELECT 1
                  FROM contest_registrations cr
                  WHERE cr.contest_id = c.id
                    AND cr.user_id = $5::bigint
                    AND cr.status = 'active'
              )
          )
      )
  )
`

type CountContestsParams struct {
	Status          pgtype.Text `db:"status" json:"status"`
	Visibility      pgtype.Text `db:"visibility" json:"visibility"`
	Keyword         pgtype.Text `db:"keyword" json:"keyword"`
	IncludePrivate  bool        `db:"include_private" json:"include_private"`
	VisibleToUserID pgtype.Int8 `db:"visible_to_user_id" json:"visible_to_user_id"`
}

func (q *Queries) CountContests(ctx context.Context, arg CountContestsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countContests,
		arg.Status,
		arg.Visibility,
		arg.Keyword,
		arg.IncludePrivate,
		arg.VisibleToUserID,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createContest = `-- name: CreateContest :one

INSERT INTO contests (
    owner_user_id,
    title,
    description,
    visibility,
    status,
    start_at,
    end_at,
    freeze_at,
    invite_code_hash
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, owner_user_id, title, description, visibility, status, start_at, end_at, freeze_at, invite_code_hash, created_at, updated_at
`

type CreateContestParams struct {
	OwnerUserID    int64              `db:"owner_user_id" json:"owner_user_id"`
	Title          string             `db:"title" json:"title"`
	Description    pgtype.Text        `db:"description" json:"description"`
	Visibility     string             `db:"visibility" json:"visibility"`
	Status         string             `db:"status" json:"status"`
	StartAt        pgtype.Timestamptz `db:"start_at" json:"start_at"`
	EndAt          pgtype.Timestamptz `db:"end_at" json:"end_at"`
	FreezeAt       pgtype.Timestamptz `db:"freeze_at" json:"freeze_at"`
	InviteCodeHash pgtype.Text        `db:"invite_code_hash" json:"invite_code_hash"`
}

// Owner: WP5 Contest
func (q *Queries) CreateContest(ctx context.Context, arg CreateContestParams) (Contest, error) {
	row := q.db.QueryRow(ctx, createContest,
		arg.OwnerUserID,
		arg.Title,
		arg.Description,
		arg.Visibility,
		arg.Status,
		arg.StartAt,
		arg.EndAt,
		arg.FreezeAt,
		arg.InviteCodeHash,
	)
	var i Contest
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Title,
		&i.Description,
		&i.Visibility,
		&i.Status,
		&i.StartAt,
		&i.EndAt,
		&i.FreezeAt,
		&i.InviteCodeHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createContestRegistration = `-- name: CreateContestRegistration :one
INSERT INTO contest_registrations (
    contest_id,
    user_id,
    display_name,
    email,
    status
) VALUES (
    $1, $2, $3, $4, 'active'
)
RETURNING id, contest_id, user_id, display_name, email, status, registered_at
`

type CreateContestRegistrationParams struct {
	ContestID   int64  `db:"contest_id" json:"contest_id"`
	UserID      int64  `db:"user_id" json:"user_id"`
	DisplayName string `db:"display_name" json:"display_name"`
	Email       string `db:"email" json:"email"`
}

func (q *Queries) CreateContestRegistration(ctx context.Context, arg CreateContestRegistrationParams) (ContestRegistration, error) {
	row := q.db.QueryRow(ctx, createContestRegistration,
		arg.ContestID,
		arg.UserID,
		arg.DisplayName,
		arg.Email,
	)
	var i ContestRegistration
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.UserID,
		&i.DisplayName,
		&i.Email,
		&i.Status,
		&i.RegisteredAt,
	)
	return i, err
}

const createContestScoreSnapshot = `-- name: CreateContestScoreSnapshot :one
INSERT INTO contest_score_snapshots (
    contest_id,
    kind,
    payload
) VALUES (
    $1, $2, $3
)
RETURNING id, contest_id, kind, payload, generated_at
`

type CreateContestScoreSnapshotParams struct {
	ContestID int64  `db:"contest_id" json:"contest_id"`
	Kind      string `db:"kind" json:"kind"`
	Payload   []byte `db:"payload" json:"payload"`
}

func (q *Queries) CreateContestScoreSnapshot(ctx context.Context, arg CreateContestScoreSnapshotParams) (ContestScoreSnapshot, error) {
	row := q.db.QueryRow(ctx, createContestScoreSnapshot, arg.ContestID, arg.Kind, arg.Payload)
	var i ContestScoreSnapshot
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.Kind,
		&i.Payload,
		&i.GeneratedAt,
	)
	return i, err
}

const deleteContestProblems = `-- name: DeleteContestProblems :exec
DELETE FROM contest_problems
WHERE contest_id = $1
`

func (q *Queries) DeleteContestProblems(ctx context.Context, contestID int64) error {
	_, err := q.db.Exec(ctx, deleteContestProblems, contestID)
	return err
}

const getContestByID = `-- name: GetContestByID :one
SELECT id, owner_user_id, title, description, visibility, status, start_at, end_at, freeze_at, invite_code_hash, created_at, updated_at
FROM contests
WHERE id = $1
`

func (q *Queries) GetContestByID(ctx context.Context, id int64) (Contest, error) {
	row := q.db.QueryRow(ctx, getContestByID, id)
	var i Contest
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Title,
		&i.Description,
		&i.Visibility,
		&i.Status,
		&i.StartAt,
		&i.EndAt,
		&i.FreezeAt,
		&i.InviteCodeHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getContestRegistration = `-- name: GetContestRegistration :one
SELECT id, contest_id, user_id, display_name, email, status, registered_at
FROM contest_registrations
WHERE contest_id = $1
  AND user_id = $2
`

type GetContestRegistrationParams struct {
	ContestID int64 `db:"contest_id" json:"contest_id"`
	UserID    int64 `db:"user_id" json:"user_id"`
}

func (q *Queries) GetContestRegistration(ctx context.Context, arg GetContestRegistrationParams) (ContestRegistration, error) {
	row := q.db.QueryRow(ctx, getContestRegistration, arg.ContestID, arg.UserID)
	var i ContestRegistration
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.UserID,
		&i.DisplayName,
		&i.Email,
		&i.Status,
		&i.RegisteredAt,
	)
	return i, err
}

const getLatestContestScoreSnapshot = `-- name: GetLatestContestScoreSnapshot :one
SELECT id, contest_id, kind, payload, generated_at
FROM contest_score_snapshots
WHERE contest_id = $1
  AND kind = $2
ORDER BY generated_at DESC, id DESC
LIMIT 1
`

type GetLatestContestScoreSnapshotParams struct {
	ContestID int64  `db:"contest_id" json:"contest_id"`
	Kind      string `db:"kind" json:"kind"`
}

func (q *Queries) GetLatestContestScoreSnapshot(ctx context.Context, arg GetLatestContestScoreSnapshotParams) (ContestScoreSnapshot, error) {
	row := q.db.QueryRow(ctx, getLatestContestScoreSnapshot, arg.ContestID, arg.Kind)
	var i ContestScoreSnapshot
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.Kind,
		&i.Payload,
		&i.GeneratedAt,
	)
	return i, err
}

const listContestProblemResults = `-- name: ListContestProblemResults :many
SELECT contest_id, user_id, problem_id, status, attempts, accepted_at, penalty_minutes, last_submission_id, best_submission_id, best_attempt_id, last_attempt_id, updated_at
FROM contest_problem_results
WHERE contest_id = $1
ORDER BY user_id, problem_id
`

func (q *Queries) ListContestProblemResults(ctx context.Context, contestID int64) ([]ContestProblemResult, error) {
	rows, err := q.db.Query(ctx, listContestProblemResults, contestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContestProblemResult
	for rows.Next() {
		var i ContestProblemResult
		if err := rows.Scan(
			&i.ContestID,
			&i.UserID,
			&i.ProblemID,
			&i.Status,
			&i.Attempts,
			&i.AcceptedAt,
			&i.PenaltyMinutes,
			&i.LastSubmissionID,
			&i.BestSubmissionID,
			&i.BestAttemptID,
			&i.LastAttemptID,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContestProblems = `-- name: ListContestProblems :many
SELECT
    cp.contest_id,
    cp.problem_id,
    cp.alias,
    cp.sort_order,
    p.title
FROM contest_problems cp
JOIN problems p ON p.id = cp.problem_id
WHERE cp.contest_id = $1
ORDER BY cp.sort_order
`

type ListContestProblemsRow struct {
	ContestID int64  `db:"contest_id" json:"contest_id"`
	ProblemID int64  `db:"problem_id" json:"problem_id"`
	Alias     string `db:"alias" json:"alias"`
	SortOrder int32  `db:"sort_order" json:"sort_order"`
	Title     string `db:"title" json:"title"`
}

func (q *Queries) ListContestProblems(ctx context.Context, contestID int64) ([]ListContestProblemsRow, error) {
	rows, err := q.db.Query(ctx, listContestProblems, contestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListContestProblemsRow
	for rows.Next() {
		var i ListContestProblemsRow
		if err := rows.Scan(
			&i.ContestID,
			&i.ProblemID,
			&i.Alias,
			&i.SortOrder,
			&i.Title,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContestRegistrations = `-- name: ListContestRegistrations :many
SELECT id, contest_id, user_id, display_name, email, status, registered_at
FROM contest_registrations
WHERE contest_id = $1
ORDER BY registered_at DESC, id DESC
LIMIT $2 OFFSET $3
`

type ListContestRegistrationsParams struct {
	ContestID int64 `db:"contest_id" json:"contest_id"`
	Limit     int32 `db:"limit" json:"limit"`
	Offset    int32 `db:"offset" json:"offset"`
}

func (q *Queries) ListContestRegistrations(ctx context.Context, arg ListContestRegistrationsParams) ([]ContestRegistration, error) {
	rows, err := q.db.Query(ctx, listContestRegistrations, arg.ContestID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContestRegistration
	for rows.Next() {
		var i ContestRegistration
		if err := rows.Scan(
			&i.ID,
			&i.ContestID,
			&i.UserID,
			&i.DisplayName,
			&i.Email,
			&i.Status,
			&i.RegisteredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContestScoreSnapshotCandidates = `-- name: ListContestScoreSnapshotCandidates :many
SELECT id,
       owner_user_id,
       title,
       description,
       visibility,
       status,
       start_at,
       end_at,
       freeze_at,
       invite_code_hash,
       created_at,
       updated_at,
       snapshot_kind
FROM (
    SELECT c.id,
           c.owner_user_id,
           c.title,
           c.description,
           c.visibility,
           c.status,
           c.start_at,
           c.end_at,
           c.freeze_at,
           c.invite_code_hash,
           c.created_at,
           c.updated_at,
           'frozen'::text AS snapshot_kind,
           c.freeze_at AS due_at
    FROM contests c
    WHERE c.status IN ('published', 'running', 'ended')
      AND c.freeze_at <= $1
      AND NOT EXISTS (
          SELECT 1
          FROM contest_score_snapshots css
          WHERE css.contest_id = c.id
            AND css.kind = 'frozen'
      )
    UNION ALL
    SELECT c.id,
           c.owner_user_id,
           c.title,
           c.description,
           c.visibility,
           c.status,
           c.start_at,
           c.end_at,
           c.freeze_at,
           c.invite_code_hash,
           c.created_at,
           c.updated_at,
           'final'::text AS snapshot_kind,
           c.end_at AS due_at
    FROM contests c
    WHERE c.status IN ('published', 'running', 'ended')
      AND c.end_at <= $1
      AND (
          NOT EXISTS (
              SELECT 1
              FROM contest_score_snapshots css
              WHERE css.contest_id = c.id
                AND css.kind = 'final'
          )
          OR EXISTS (
              SELECT 1
              FROM rejudge_batches rb
              LEFT JOIN contest_score_snapshots css
                ON css.contest_id = rb.contest_id
               AND css.kind = 'final'
              WHERE rb.contest_id = c.id
                AND rb.status = 'completed'
                AND rb.finished_at IS NOT NULL
              GROUP BY rb.id, rb.finished_at
              HAVING rb.finished_at > coalesce(max(css.generated_at), '-infinity'::timestamptz)
          )
      )
) due
ORDER BY due_at, id, snapshot_kind
LIMIT $2
`

type ListContestScoreSnapshotCandidatesParams struct {
	FreezeAt pgtype.Timestamptz `db:"freeze_at" json:"freeze_at"`
	Limit    int32              `db:"limit" json:"limit"`
}

type ListContestScoreSnapshotCandidatesRow struct {
	ID             int64              `db:"id" json:"id"`
	OwnerUserID    int64              `db:"owner_user_id" json:"owner_user_id"`
	Title          string             `db:"title" json:"title"`
	Description    pgtype.Text        `db:"description" json:"description"`
	Visibility     string             `db:"visibility" json:"visibility"`
	Status         string             `db:"status" json:"status"`
	StartAt        pgtype.Timestamptz `db:"start_at" json:"start_at"`
	EndAt          pgtype.Timestamptz `db:"end_at" json:"end_at"`
	FreezeAt       pgtype.Timestamptz `db:"freeze_at" json:"freeze_at"`
	InviteCodeHash pgtype.Text        `db:"invite_code_hash" json:"invite_code_hash"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	SnapshotKind   string             `db:"snapshot_kind" json:"snapshot_kind"`
}

func (q *Queries) ListContestScoreSnapshotCandidates(ctx context.Context, arg ListContestScoreSnapshotCandidatesParams) ([]ListContestScoreSnapshotCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listContestScoreSnapshotCandidates, arg.FreezeAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListContestScoreSnapshotCandidatesRow
	for rows.Next() {
		var i ListContestScoreSnapshotCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Title,
			&i.Description,
			&i.Visibility,
			&i.Status,
			&i.StartAt,
			&i.EndAt,
			&i.FreezeAt,
			&i.InviteCodeHash,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SnapshotKind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContestTerminalSubmissions = `-- name: ListContestTerminalSubmissions :many
SELECT id, user_id, problem_id, contest_id, status, submitted_at, judged_at
FROM submissions
WHERE contest_id = $1::bigint
  AND judged_at IS NOT NULL
  AND status IN ('accepted', 'wrong_answer', 'compile_error', 'runtime_error', 'time_limit', 'memory_limit', 'output_limit', 'system_error', 'canceled')
ORDER BY submitted_at, id
`

type ListContestTerminalSubmissionsRow struct {
	ID          int64              `db:"id" json:"id"`
	UserID      int64              `db:"user_id" json:"user_id"`
	ProblemID   int64              `db:"problem_id" json:"problem_id"`
	ContestID   pgtype.Int8        `db:"contest_id" json:"contest_id"`
	Status      string             `db:"status" json:"status"`
	SubmittedAt pgtype.Timestamptz `db:"submitted_at" json:"submitted_at"`
	JudgedAt    pgtype.Timestamptz `db:"judged_at" json:"judged_at"`
}

func (q *Queries) ListContestTerminalSubmissions(ctx context.Context, dollar_1 int64) ([]ListContestTerminalSubmissionsRow, error) {
	rows, err := q.db.Query(ctx, listContestTerminalSubmissions, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListContestTerminalSubmissionsRow
	for rows.Next() {
		var i ListContestTerminalSubmissionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProblemID,
			&i.ContestID,
			&i.Status,
			&i.SubmittedAt,
			&i.JudgedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContests = `-- name: ListContests :many
SELECT c.id, c.owner_user_id, c.title, c.description, c.visibility, c.status, c.start_at, c.end_at, c.freeze_at, c.invite_code_hash, c.created_at, c.updated_at
FROM contests c
WHERE ($1::text IS NULL OR c.status = $1::text)
  AND ($2::text IS NULL OR c.visibility = $2::text)
  AND (
      $3::text IS NULL
      OR c.title ILIKE '%' || $3::text || '%'
  )
  AND (
      $4::boolean
      OR c.visibility = 'public'
      OR (
          $5::bigint IS NOT NULL
          AND (
              c.owner_user_id = $5::bigint
              OR EXISTS (
                  SELECT 1
                  FROM contest_registrations cr
                  WHERE cr.contest_id = c.id
                    AND cr.user_id = $5::bigint
                    AND cr.status = 'active'
              )
          )
      )
  )
ORDER BY c.start_at DESC, c.id DESC
LIMIT $7 OFFSET $6
`

type ListContestsParams struct {
	Status          pgtype.Text `db:"status" json:"status"`
	Visibility      pgtype.Text `db:"visibility" json:"visibility"`
	Keyword         pgtype.Text `db:"keyword" json:"keyword"`
	IncludePrivate  bool        `db:"include_private" json:"include_private"`
	VisibleToUserID pgtype.Int8 `db:"visible_to_user_id" json:"visible_to_user_id"`
	Offset          int32       `db:"offset" json:"offset"`
	Limit           int32       `db:"limit" json:"limit"`
}

func (q *Queries) ListContests(ctx context.Context, arg ListContestsParams) ([]Contest, error) {
	rows, err := q.db.Query(ctx, listContests,
		arg.Status,
		arg.Visibility,
		arg.Keyword,
		arg.IncludePrivate,
		arg.VisibleToUserID,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Contest
	for rows.Next() {
		var i Contest
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Title,
			&i.Description,
			&i.Visibility,
			&i.Status,
			&i.StartAt,
			&i.EndAt,
			&i.FreezeAt,
			&i.InviteCodeHash,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContestsByCursor = `-- name: ListContestsByCursor :many
SELECT c.id, c.owner_user_id, c.title, c.description, c.visibility, c.status, c.start_at, c.end_at, c.freeze_at, c.invite_code_hash, c.created_at, c.updated_at
FROM contests c
WHERE ($1::text IS NULL OR c.status = $1::text)
  AND ($2::text IS NULL OR c.visibility = $2::text)
  AND (
      $3::text IS NULL
      OR c.title ILIKE '%' || $3::text || '%'
  )
  AND (
      $4::boolean
      OR c.visibility = 'public'
      OR (
          $5::bigint IS NOT NULL
          AND (
              c.owner_user_id = $5::bigint
              OR EXISTS (
                  SELECT 1
                  FROM contest_registrations cr
                  WHERE cr.contest_id = c.id
                    AND cr.user_id = $5::bigint
                    AND cr.status = 'active'
              )
          )
      )
  )
  AND (c.start_at, c.id) < (
      $6::timestamptz,
      $7::bigint
  )
ORDER BY c.start_at DESC, c.id DESC
LIMIT $8
`

type ListContestsByCursorParams struct {
	Status          pgtype.Text        `db:"status" json:"status"`
	Visibility      pgtype.Text        `db:"visibility" json:"visibility"`
	Keyword         pgtype.Text        `db:"keyword" json:"keyword"`
	IncludePrivate  bool               `db:"include_private" json:"include_private"`
	VisibleToUserID pgtype.Int8        `db:"visible_to_user_id" json:"visible_to_user_id"`
	BeforeStartAt   pgtype.Timestamptz `db:"before_start_at" json:"before_start_at"`
	BeforeID        int64              `db:"before_id" json:"before_id"`
	Limit           int32              `db:"limit" json:"limit"`
}

func (q *Queries) ListContestsByCursor(ctx context.Context, arg ListContestsByCursorParams) ([]Contest, error) {
	rows, err := q.db.Query(ctx, listContestsByCursor,
		arg.Status,
		arg.Visibility,
		arg.Keyword,
		arg.IncludePrivate,
		arg.VisibleToUserID,
		arg.BeforeStartAt,
		arg.BeforeID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Contest
	for rows.Next() {
		var i Contest
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Title,
			&i.Description,
			&i.Visibility,
			&i.Status,
			&i.StartAt,
			&i.EndAt,
			&i.FreezeAt,
			&i.InviteCodeHash,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContest = `-- name: UpdateContest :one
UPDATE contests
SET title = coalesce($1, title),
    description = coalesce($2, description),
    visibility = coalesce($3, visibility),
    status = coalesce($4, status),
    start_at = coalesce($5, start_at),
    end_at = coalesce($6, end_at),
    freeze_at = coalesce($7, freeze_at),
    invite_code_hash = coalesce($8, invite_code_hash),
    updated_at = now()
WHERE id = $9
RETURNING id, owner_user_id, title, description, visibility, status, start_at, end_at, freeze_at, invite_code_hash, created_at, updated_at
`

type UpdateContestParams struct {
	Title          pgtype.Text        `db:"title" json:"title"`
	Description    pgtype.Text        `db:"description" json:"description"`
	Visibility     pgtype.Text        `db:"visibility" json:"visibility"`
	Status         pgtype.Text        `db:"status" json:"status"`
	StartAt        pgtype.Timestamptz `db:"start_at" json:"start_at"`
	EndAt          pgtype.Timestamptz `db:"end_at" json:"end_at"`
	FreezeAt       pgtype.Timestamptz `db:"freeze_at" json:"freeze_at"`
	InviteCodeHash pgtype.Text        `db:"invite_code_hash" json:"invite_code_hash"`
	ID             int64              `db:"id" json:"id"`
}

func (q *Queries) UpdateContest(ctx context.Context, arg UpdateContestParams) (Contest, error) {
	row := q.db.QueryRow(ctx, updateContest,
		arg.Title,
		arg.Description,
		arg.Visibility,
		arg.Status,
		arg.StartAt,
		arg.EndAt,
		arg.FreezeAt,
		arg.InviteCodeHash,
		arg.ID,
	)
	var i Contest
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Title,
		&i.Description,
		&i.Visibility,
		&i.Status,
		&i.StartAt,
		&i.EndAt,
		&i.FreezeAt,
		&i.InviteCodeHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertContestProblemResult = `-- name: UpsertContestProblemResult :one
INSERT INTO contest_problem_results (
    contest_id,
    user_id,
    problem_id,
    status,
    attempts,
    accepted_at,
    penalty_minutes,
    last_submission_id,
    best_submission_id,
    best_attempt_id,
    last_attempt_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
ON CONFLICT (contest_id, user_id, problem_id) DO UPDATE
SET status = EXCLUDED.status,
    attempts = EXCLUDED.attempts,
    accepted_at = EXCLUDED.accepted_at,
    penalty_minutes = EXCLUDED.penalty_minutes,
    last_submission_id = EXCLUDED.last_submission_id,
    best_submission_id = EXCLUDED.best_submission_id,
    best_attempt_id = EXCLUDED.best_attempt_id,
    last_attempt_id = EXCLUDED.last_attempt_id,
    updated_at = now()
RETURNING contest_id, user_id, problem_id, status, attempts, accepted_at, penalty_minutes, last_submission_id, best_submission_id, best_attempt_id, last_attempt_id, updated_at
`

type UpsertContestProblemResultParams struct {
	ContestID        int64              `db:"contest_id" json:"contest_id"`
	UserID           int64              `db:"user_id" json:"user_id"`
	ProblemID        int64              `db:"problem_id" json:"problem_id"`
	Status           string             `db:"status" json:"status"`
	Attempts         int32              `db:"attempts" json:"attempts"`
	AcceptedAt       pgtype.Timestamptz `db:"accepted_at" json:"accepted_at"`
	PenaltyMinutes   int32              `db:"penalty_minutes" json:"penalty_minutes"`
	LastSubmissionID pgtype.Int8        `db:"last_submission_id" json:"last_submission_id"`
	BestSubmissionID pgtype.Int8        `db:"best_submission_id" json:"best_submission_id"`
	BestAttemptID    pgtype.Int8        `db:"best_attempt_id" json:"best_attempt_id"`
	LastAttemptID    pgtype.Int8        `db:"last_attempt_id" json:"last_attempt_id"`
}

func (q *Queries) UpsertContestProblemResult(ctx context.Context, arg UpsertContestProblemResultParams) (ContestProblemResult, error) {
	row := q.db.QueryRow(ctx, upsertContestProblemResult,
		arg.ContestID,
		arg.UserID,
		arg.ProblemID,
		arg.Status,
		arg.Attempts,
		arg.AcceptedAt,
		arg.PenaltyMinutes,
		arg.LastSubmissionID,
		arg.BestSubmissionID,
		arg.BestAttemptID,
		arg.LastAttemptID,
	)
	var i ContestProblemResult
	err := row.Scan(
		&i.ContestID,
		&i.UserID,
		&i.ProblemID,
		&i.Status,
		&i.Attempts,
		&i.AcceptedAt,
		&i.PenaltyMinutes,
		&i.LastSubmissionID,
		&i.BestSubmissionID,
		&i.BestAttemptID,
		&i.LastAttemptID,
		&i.UpdatedAt,
	)
	return i, err
}
