// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: languages.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countLanguages = `-- name: CountLanguages :one
SELECT count(*)::bigint
FROM languages
WHERE ($1::boolean IS NULL OR enabled = $1::boolean)
  AND (
      $2::text IS NULL
      OR engine = $2::text
  )
`

type CountLanguagesParams struct {
	Enabled pgtype.Bool `db:"enabled" json:"enabled"`
	Engine  pgtype.Text `db:"engine" json:"engine"`
}

func (q *Queries) CountLanguages(ctx context.Context, arg CountLanguagesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLanguages, arg.Enabled, arg.Engine)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getEnabledLanguageByID = `-- name: GetEnabledLanguageByID :one
SELECT id, engine, engine_language_id, name, version, compile_command, run_command, default_time_limit_ms, default_memory_limit_kb, enabled, created_at, updated_at
FROM languages
WHERE id = $1
  AND enabled = true
`

func (q *Queries) GetEnabledLanguageByID(ctx context.Context, id int64) (Language, error) {
	row := q.db.QueryRow(ctx, getEnabledLanguageByID, id)
	var i Language
	err := row.Scan(
		&i.ID,
		&i.Engine,
		&i.EngineLanguageID,
		&i.Name,
		&i.Version,
		&i.CompileCommand,
		&i.RunCommand,
		&i.DefaultTimeLimitMs,
		&i.DefaultMemoryLimitKb,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLanguageByID = `-- name: GetLanguageByID :one
SELECT id, engine, engine_language_id, name, version, compile_command, run_command, default_time_limit_ms, default_memory_limit_kb, enabled, created_at, updated_at
FROM languages
WHERE id = $1
`

func (q *Queries) GetLanguageByID(ctx context.Context, id int64) (Language, error) {
	row := q.db.QueryRow(ctx, getLanguageByID, id)
	var i Language
	err := row.Scan(
		&i.ID,
		&i.Engine,
		&i.EngineLanguageID,
		&i.Name,
		&i.Version,
		&i.CompileCommand,
		&i.RunCommand,
		&i.DefaultTimeLimitMs,
		&i.DefaultMemoryLimitKb,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLanguages = `-- name: ListLanguages :many
SELECT id, engine, engine_language_id, name, version, compile_command, run_command, default_time_limit_ms, default_memory_limit_kb, enabled, created_at, updated_at
FROM languages
WHERE ($1::boolean IS NULL OR enabled = $1::boolean)
  AND (
      $2::text IS NULL
      OR engine = $2::text
  )
ORDER BY enabled DESC, name ASC, id ASC
LIMIT $4 OFFSET $3
`

type ListLanguagesParams struct {
	Enabled pgtype.Bool `db:"enabled" json:"enabled"`
	Engine  pgtype.Text `db:"engine" json:"engine"`
	Offset  int32       `db:"offset" json:"offset"`
	Limit   int32       `db:"limit" json:"limit"`
}

func (q *Queries) ListLanguages(ctx context.Context, arg ListLanguagesParams) ([]Language, error) {
	rows, err := q.db.Query(ctx, listLanguages,
		arg.Enabled,
		arg.Engine,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Language
	for rows.Next() {
		var i Language
		if err := rows.Scan(
			&i.ID,
			&i.Engine,
			&i.EngineLanguageID,
			&i.Name,
			&i.Version,
			&i.CompileCommand,
			&i.RunCommand,
			&i.DefaultTimeLimitMs,
			&i.DefaultMemoryLimitKb,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLanguageAdminFields = `-- name: UpdateLanguageAdminFields :one
UPDATE languages
SET enabled = coalesce($1, enabled),
    default_time_limit_ms = coalesce($2, default_time_limit_ms),
    default_memory_limit_kb = coalesce($3, default_memory_limit_kb),
    updated_at = now()
WHERE id = $4
RETURNING id, engine, engine_language_id, name, version, compile_command, run_command, default_time_limit_ms, default_memory_limit_kb, enabled, created_at, updated_at
`

type UpdateLanguageAdminFieldsParams struct {
	Enabled              pgtype.Bool `db:"enabled" json:"enabled"`
	DefaultTimeLimitMs   pgtype.Int4 `db:"default_time_limit_ms" json:"default_time_limit_ms"`
	DefaultMemoryLimitKb pgtype.Int4 `db:"default_memory_limit_kb" json:"default_memory_limit_kb"`
	ID                   int64       `db:"id" json:"id"`
}

func (q *Queries) UpdateLanguageAdminFields(ctx context.Context, arg UpdateLanguageAdminFieldsParams) (Language, error) {
	row := q.db.QueryRow(ctx, updateLanguageAdminFields,
		arg.Enabled,
		arg.DefaultTimeLimitMs,
		arg.DefaultMemoryLimitKb,
		arg.ID,
	)
	var i Language
	err := row.Scan(
		&i.ID,
		&i.Engine,
		&i.EngineLanguageID,
		&i.Name,
		&i.Version,
		&i.CompileCommand,
		&i.RunCommand,
		&i.DefaultTimeLimitMs,
		&i.DefaultMemoryLimitKb,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertLanguage = `-- name: UpsertLanguage :one

INSERT INTO languages (
    engine,
    engine_language_id,
    name,
    version,
    compile_command,
    run_command,
    default_time_limit_ms,
    default_memory_limit_kb,
    enabled
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
ON CONFLICT (engine, engine_language_id) DO UPDATE
SET name = EXCLUDED.name,
    version = EXCLUDED.version,
    compile_command = EXCLUDED.compile_command,
    run_command = EXCLUDED.run_command,
    default_time_limit_ms = EXCLUDED.default_time_limit_ms,
    default_memory_limit_kb = EXCLUDED.default_memory_limit_kb,
    updated_at = now()
RETURNING id, engine, engine_language_id, name, version, compile_command, run_command, default_time_limit_ms, default_memory_limit_kb, enabled, created_at, updated_at
`

type UpsertLanguageParams struct {
	Engine               string      `db:"engine" json:"engine"`
	EngineLanguageID     string      `db:"engine_language_id" json:"engine_language_id"`
	Name                 string      `db:"name" json:"name"`
	Version              pgtype.Text `db:"version" json:"version"`
	CompileCommand       pgtype.Text `db:"compile_command" json:"compile_command"`
	RunCommand           pgtype.Text `db:"run_command" json:"run_command"`
	DefaultTimeLimitMs   int32       `db:"default_time_limit_ms" json:"default_time_limit_ms"`
	DefaultMemoryLimitKb int32       `db:"default_memory_limit_kb" json:"default_memory_limit_kb"`
	Enabled              bool        `db:"enabled" json:"enabled"`
}

// Owner: WP4 Submission/Language
// Sync intentionally preserves enabled on existing rows so JudgeEngine language
// refreshes do not re-enable languages disabled by an admin.
func (q *Queries) UpsertLanguage(ctx context.Context, arg UpsertLanguageParams) (Language, error) {
	row := q.db.QueryRow(ctx, upsertLanguage,
		arg.Engine,
		arg.EngineLanguageID,
		arg.Name,
		arg.Version,
		arg.CompileCommand,
		arg.RunCommand,
		arg.DefaultTimeLimitMs,
		arg.DefaultMemoryLimitKb,
		arg.Enabled,
	)
	var i Language
	err := row.Scan(
		&i.ID,
		&i.Engine,
		&i.EngineLanguageID,
		&i.Name,
		&i.Version,
		&i.CompileCommand,
		&i.RunCommand,
		&i.DefaultTimeLimitMs,
		&i.DefaultMemoryLimitKb,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
