// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type Artifact struct {
	ID             int64              `db:"id" json:"id"`
	OwnerType      string             `db:"owner_type" json:"owner_type"`
	OwnerID        int64              `db:"owner_id" json:"owner_id"`
	Kind           string             `db:"kind" json:"kind"`
	StorageKey     string             `db:"storage_key" json:"storage_key"`
	ChecksumSha256 string             `db:"checksum_sha256" json:"checksum_sha256"`
	SizeBytes      int64              `db:"size_bytes" json:"size_bytes"`
	ContentType    string             `db:"content_type" json:"content_type"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Contest struct {
	ID             int64              `db:"id" json:"id"`
	OwnerUserID    int64              `db:"owner_user_id" json:"owner_user_id"`
	Title          string             `db:"title" json:"title"`
	Description    pgtype.Text        `db:"description" json:"description"`
	Visibility     string             `db:"visibility" json:"visibility"`
	Status         string             `db:"status" json:"status"`
	StartAt        pgtype.Timestamptz `db:"start_at" json:"start_at"`
	EndAt          pgtype.Timestamptz `db:"end_at" json:"end_at"`
	FreezeAt       pgtype.Timestamptz `db:"freeze_at" json:"freeze_at"`
	InviteCodeHash pgtype.Text        `db:"invite_code_hash" json:"invite_code_hash"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type ContestProblem struct {
	ContestID int64  `db:"contest_id" json:"contest_id"`
	ProblemID int64  `db:"problem_id" json:"problem_id"`
	Alias     string `db:"alias" json:"alias"`
	SortOrder int32  `db:"sort_order" json:"sort_order"`
}

type ContestProblemResult struct {
	ContestID        int64              `db:"contest_id" json:"contest_id"`
	UserID           int64              `db:"user_id" json:"user_id"`
	ProblemID        int64              `db:"problem_id" json:"problem_id"`
	Status           string             `db:"status" json:"status"`
	Attempts         int32              `db:"attempts" json:"attempts"`
	AcceptedAt       pgtype.Timestamptz `db:"accepted_at" json:"accepted_at"`
	PenaltyMinutes   int32              `db:"penalty_minutes" json:"penalty_minutes"`
	LastSubmissionID pgtype.Int8        `db:"last_submission_id" json:"last_submission_id"`
	BestSubmissionID pgtype.Int8        `db:"best_submission_id" json:"best_submission_id"`
	BestAttemptID    pgtype.Int8        `db:"best_attempt_id" json:"best_attempt_id"`
	LastAttemptID    pgtype.Int8        `db:"last_attempt_id" json:"last_attempt_id"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type ContestRegistration struct {
	ID           int64              `db:"id" json:"id"`
	ContestID    int64              `db:"contest_id" json:"contest_id"`
	UserID       int64              `db:"user_id" json:"user_id"`
	DisplayName  string             `db:"display_name" json:"display_name"`
	Email        string             `db:"email" json:"email"`
	Status       string             `db:"status" json:"status"`
	RegisteredAt pgtype.Timestamptz `db:"registered_at" json:"registered_at"`
}

type ContestScoreSnapshot struct {
	ID          int64              `db:"id" json:"id"`
	ContestID   int64              `db:"contest_id" json:"contest_id"`
	Kind        string             `db:"kind" json:"kind"`
	Payload     []byte             `db:"payload" json:"payload"`
	GeneratedAt pgtype.Timestamptz `db:"generated_at" json:"generated_at"`
}

type JudgeAttempt struct {
	ID                   int64              `db:"id" json:"id"`
	SubmissionID         pgtype.Int8        `db:"submission_id" json:"submission_id"`
	RunID                pgtype.Int8        `db:"run_id" json:"run_id"`
	TaskID               pgtype.Int8        `db:"task_id" json:"task_id"`
	RejudgeBatchID       pgtype.Int8        `db:"rejudge_batch_id" json:"rejudge_batch_id"`
	AttemptNo            int32              `db:"attempt_no" json:"attempt_no"`
	ProtocolVersion      string             `db:"protocol_version" json:"protocol_version"`
	JudgeCoreVersion     string             `db:"judge_core_version" json:"judge_core_version"`
	JudgeEngine          string             `db:"judge_engine" json:"judge_engine"`
	JudgeAgentID         pgtype.Text        `db:"judge_agent_id" json:"judge_agent_id"`
	LanguageID           int64              `db:"language_id" json:"language_id"`
	LanguageRuntime      pgtype.Text        `db:"language_runtime" json:"language_runtime"`
	SandboxBackend       pgtype.Text        `db:"sandbox_backend" json:"sandbox_backend"`
	SandboxProfile       pgtype.Text        `db:"sandbox_profile" json:"sandbox_profile"`
	TestcaseSetID        pgtype.Int8        `db:"testcase_set_id" json:"testcase_set_id"`
	TestcaseSetHash      pgtype.Text        `db:"testcase_set_hash" json:"testcase_set_hash"`
	CheckerHash          pgtype.Text        `db:"checker_hash" json:"checker_hash"`
	ValidatorHash        pgtype.Text        `db:"validator_hash" json:"validator_hash"`
	Status               string             `db:"status" json:"status"`
	Verdict              pgtype.Text        `db:"verdict" json:"verdict"`
	Score                int32              `db:"score" json:"score"`
	TimeMs               pgtype.Int4        `db:"time_ms" json:"time_ms"`
	MemoryKb             pgtype.Int4        `db:"memory_kb" json:"memory_kb"`
	FirstFailedCaseIndex pgtype.Int4        `db:"first_failed_case_index" json:"first_failed_case_index"`
	FirstFailedGroup     pgtype.Text        `db:"first_failed_group" json:"first_failed_group"`
	CompileOutputSummary pgtype.Text        `db:"compile_output_summary" json:"compile_output_summary"`
	StderrSummary        pgtype.Text        `db:"stderr_summary" json:"stderr_summary"`
	CheckerMessage       pgtype.Text        `db:"checker_message" json:"checker_message"`
	ErrorClass           pgtype.Text        `db:"error_class" json:"error_class"`
	ErrorMessage         pgtype.Text        `db:"error_message" json:"error_message"`
	Manifest             []byte             `db:"manifest" json:"manifest"`
	Metrics              []byte             `db:"metrics" json:"metrics"`
	TraceID              pgtype.Text        `db:"trace_id" json:"trace_id"`
	StartedAt            pgtype.Timestamptz `db:"started_at" json:"started_at"`
	FinishedAt           pgtype.Timestamptz `db:"finished_at" json:"finished_at"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type JudgeCaseResult struct {
	ID                int64              `db:"id" json:"id"`
	AttemptID         int64              `db:"attempt_id" json:"attempt_id"`
	CaseIndex         int32              `db:"case_index" json:"case_index"`
	GroupName         pgtype.Text        `db:"group_name" json:"group_name"`
	TestcaseKey       pgtype.Text        `db:"testcase_key" json:"testcase_key"`
	Status            string             `db:"status" json:"status"`
	Score             int32              `db:"score" json:"score"`
	TimeMs            pgtype.Int4        `db:"time_ms" json:"time_ms"`
	MemoryKb          pgtype.Int4        `db:"memory_kb" json:"memory_kb"`
	ExitCode          pgtype.Int4        `db:"exit_code" json:"exit_code"`
	Signal            pgtype.Text        `db:"signal" json:"signal"`
	CheckerMessage    pgtype.Text        `db:"checker_message" json:"checker_message"`
	OutputDiffSummary pgtype.Text        `db:"output_diff_summary" json:"output_diff_summary"`
	StdoutArtifactID  pgtype.Int8        `db:"stdout_artifact_id" json:"stdout_artifact_id"`
	StderrArtifactID  pgtype.Int8        `db:"stderr_artifact_id" json:"stderr_artifact_id"`
	DiffArtifactID    pgtype.Int8        `db:"diff_artifact_id" json:"diff_artifact_id"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type JudgeTask struct {
	ID           int64              `db:"id" json:"id"`
	SubmissionID int64              `db:"submission_id" json:"submission_id"`
	StreamID     pgtype.Text        `db:"stream_id" json:"stream_id"`
	Status       string             `db:"status" json:"status"`
	Attempts     int32              `db:"attempts" json:"attempts"`
	NextRunAt    pgtype.Timestamptz `db:"next_run_at" json:"next_run_at"`
	LastError    pgtype.Text        `db:"last_error" json:"last_error"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Language struct {
	ID                   int64              `db:"id" json:"id"`
	Engine               string             `db:"engine" json:"engine"`
	EngineLanguageID     string             `db:"engine_language_id" json:"engine_language_id"`
	Name                 string             `db:"name" json:"name"`
	Version              pgtype.Text        `db:"version" json:"version"`
	CompileCommand       pgtype.Text        `db:"compile_command" json:"compile_command"`
	RunCommand           pgtype.Text        `db:"run_command" json:"run_command"`
	DefaultTimeLimitMs   int32              `db:"default_time_limit_ms" json:"default_time_limit_ms"`
	DefaultMemoryLimitKb int32              `db:"default_memory_limit_kb" json:"default_memory_limit_kb"`
	Enabled              bool               `db:"enabled" json:"enabled"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Problem struct {
	ID            int64              `db:"id" json:"id"`
	OwnerUserID   int64              `db:"owner_user_id" json:"owner_user_id"`
	Title         string             `db:"title" json:"title"`
	Slug          string             `db:"slug" json:"slug"`
	Difficulty    string             `db:"difficulty" json:"difficulty"`
	Visibility    string             `db:"visibility" json:"visibility"`
	Status        string             `db:"status" json:"status"`
	TimeLimitMs   int32              `db:"time_limit_ms" json:"time_limit_ms"`
	MemoryLimitKb int32              `db:"memory_limit_kb" json:"memory_limit_kb"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	PublishedAt   pgtype.Timestamptz `db:"published_at" json:"published_at"`
}

type ProblemCheckFinding struct {
	ID          int64              `db:"id" json:"id"`
	RunID       int64              `db:"run_id" json:"run_id"`
	Severity    string             `db:"severity" json:"severity"`
	Code        string             `db:"code" json:"code"`
	Message     string             `db:"message" json:"message"`
	CaseIndex   pgtype.Int4        `db:"case_index" json:"case_index"`
	TestcaseKey pgtype.Text        `db:"testcase_key" json:"testcase_key"`
	Details     []byte             `db:"details" json:"details"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type ProblemCheckRun struct {
	ID            int64              `db:"id" json:"id"`
	ProblemID     int64              `db:"problem_id" json:"problem_id"`
	TestcaseSetID pgtype.Int8        `db:"testcase_set_id" json:"testcase_set_id"`
	RequestedBy   pgtype.Int8        `db:"requested_by" json:"requested_by"`
	Status        string             `db:"status" json:"status"`
	Summary       []byte             `db:"summary" json:"summary"`
	ErrorMessage  pgtype.Text        `db:"error_message" json:"error_message"`
	StartedAt     pgtype.Timestamptz `db:"started_at" json:"started_at"`
	FinishedAt    pgtype.Timestamptz `db:"finished_at" json:"finished_at"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	StatementID   pgtype.Int8        `db:"statement_id" json:"statement_id"`
}

type ProblemStatement struct {
	ID                int64              `db:"id" json:"id"`
	ProblemID         int64              `db:"problem_id" json:"problem_id"`
	Version           int32              `db:"version" json:"version"`
	Title             string             `db:"title" json:"title"`
	Description       string             `db:"description" json:"description"`
	InputDescription  pgtype.Text        `db:"input_description" json:"input_description"`
	OutputDescription pgtype.Text        `db:"output_description" json:"output_description"`
	Samples           []byte             `db:"samples" json:"samples"`
	Hint              pgtype.Text        `db:"hint" json:"hint"`
	Source            pgtype.Text        `db:"source" json:"source"`
	IsCurrent         bool               `db:"is_current" json:"is_current"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type ProblemTag struct {
	ID   int64  `db:"id" json:"id"`
	Name string `db:"name" json:"name"`
	Slug string `db:"slug" json:"slug"`
}

type ProblemTagLink struct {
	ProblemID int64 `db:"problem_id" json:"problem_id"`
	TagID     int64 `db:"tag_id" json:"tag_id"`
}

type RefreshToken struct {
	ID        int64              `db:"id" json:"id"`
	UserID    int64              `db:"user_id" json:"user_id"`
	TokenHash string             `db:"token_hash" json:"token_hash"`
	DeviceID  string             `db:"device_id" json:"device_id"`
	UserAgent pgtype.Text        `db:"user_agent" json:"user_agent"`
	Ip        *netip.Addr        `db:"ip" json:"ip"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	RevokedAt pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type RejudgeBatch struct {
	ID             int64              `db:"id" json:"id"`
	ProblemID      pgtype.Int8        `db:"problem_id" json:"problem_id"`
	ContestID      pgtype.Int8        `db:"contest_id" json:"contest_id"`
	RequestedBy    int64              `db:"requested_by" json:"requested_by"`
	Status         string             `db:"status" json:"status"`
	Reason         string             `db:"reason" json:"reason"`
	Filters        []byte             `db:"filters" json:"filters"`
	TotalCount     int32              `db:"total_count" json:"total_count"`
	CompletedCount int32              `db:"completed_count" json:"completed_count"`
	FailedCount    int32              `db:"failed_count" json:"failed_count"`
	CanceledCount  int32              `db:"canceled_count" json:"canceled_count"`
	ErrorMessage   pgtype.Text        `db:"error_message" json:"error_message"`
	StartedAt      pgtype.Timestamptz `db:"started_at" json:"started_at"`
	FinishedAt     pgtype.Timestamptz `db:"finished_at" json:"finished_at"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Run struct {
	ID               int64              `db:"id" json:"id"`
	UserID           int64              `db:"user_id" json:"user_id"`
	ProblemID        int64              `db:"problem_id" json:"problem_id"`
	LanguageID       int64              `db:"language_id" json:"language_id"`
	Status           string             `db:"status" json:"status"`
	SourceArtifactID pgtype.Int8        `db:"source_artifact_id" json:"source_artifact_id"`
	Stdin            pgtype.Text        `db:"stdin" json:"stdin"`
	Stdout           pgtype.Text        `db:"stdout" json:"stdout"`
	Stderr           pgtype.Text        `db:"stderr" json:"stderr"`
	CompileOutput    pgtype.Text        `db:"compile_output" json:"compile_output"`
	TimeMs           pgtype.Int4        `db:"time_ms" json:"time_ms"`
	MemoryKb         pgtype.Int4        `db:"memory_kb" json:"memory_kb"`
	ErrorMessage     pgtype.Text        `db:"error_message" json:"error_message"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	FinishedAt       pgtype.Timestamptz `db:"finished_at" json:"finished_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Submission struct {
	ID               int64              `db:"id" json:"id"`
	UserID           int64              `db:"user_id" json:"user_id"`
	ProblemID        int64              `db:"problem_id" json:"problem_id"`
	ContestID        pgtype.Int8        `db:"contest_id" json:"contest_id"`
	LanguageID       int64              `db:"language_id" json:"language_id"`
	TestcaseSetID    int64              `db:"testcase_set_id" json:"testcase_set_id"`
	Status           string             `db:"status" json:"status"`
	SourceArtifactID pgtype.Int8        `db:"source_artifact_id" json:"source_artifact_id"`
	TimeMs           pgtype.Int4        `db:"time_ms" json:"time_ms"`
	MemoryKb         pgtype.Int4        `db:"memory_kb" json:"memory_kb"`
	Score            int32              `db:"score" json:"score"`
	ErrorMessage     pgtype.Text        `db:"error_message" json:"error_message"`
	SubmittedAt      pgtype.Timestamptz `db:"submitted_at" json:"submitted_at"`
	JudgedAt         pgtype.Timestamptz `db:"judged_at" json:"judged_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type SubmissionResult struct {
	SubmissionID         int64              `db:"submission_id" json:"submission_id"`
	AttemptID            int64              `db:"attempt_id" json:"attempt_id"`
	Status               string             `db:"status" json:"status"`
	Score                int32              `db:"score" json:"score"`
	TimeMs               pgtype.Int4        `db:"time_ms" json:"time_ms"`
	MemoryKb             pgtype.Int4        `db:"memory_kb" json:"memory_kb"`
	FirstFailedCaseIndex pgtype.Int4        `db:"first_failed_case_index" json:"first_failed_case_index"`
	FirstFailedGroup     pgtype.Text        `db:"first_failed_group" json:"first_failed_group"`
	ErrorClass           pgtype.Text        `db:"error_class" json:"error_class"`
	SafeSummary          []byte             `db:"safe_summary" json:"safe_summary"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type TestcaseSet struct {
	ID             int64              `db:"id" json:"id"`
	ProblemID      int64              `db:"problem_id" json:"problem_id"`
	Version        int32              `db:"version" json:"version"`
	StorageKey     string             `db:"storage_key" json:"storage_key"`
	ChecksumSha256 string             `db:"checksum_sha256" json:"checksum_sha256"`
	SizeBytes      int64              `db:"size_bytes" json:"size_bytes"`
	CaseCount      int32              `db:"case_count" json:"case_count"`
	Status         string             `db:"status" json:"status"`
	IsCurrent      bool               `db:"is_current" json:"is_current"`
	CreatedBy      int64              `db:"created_by" json:"created_by"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type User struct {
	ID           int64              `db:"id" json:"id"`
	Email        string             `db:"email" json:"email"`
	PasswordHash string             `db:"password_hash" json:"password_hash"`
	Username     string             `db:"username" json:"username"`
	AvatarUrl    pgtype.Text        `db:"avatar_url" json:"avatar_url"`
	Bio          pgtype.Text        `db:"bio" json:"bio"`
	Role         string             `db:"role" json:"role"`
	Status       string             `db:"status" json:"status"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}
