// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type Artifact struct {
	ID             int64              `db:"id" json:"id"`
	OwnerType      string             `db:"owner_type" json:"owner_type"`
	OwnerID        int64              `db:"owner_id" json:"owner_id"`
	Kind           string             `db:"kind" json:"kind"`
	StorageKey     string             `db:"storage_key" json:"storage_key"`
	ChecksumSha256 string             `db:"checksum_sha256" json:"checksum_sha256"`
	SizeBytes      int64              `db:"size_bytes" json:"size_bytes"`
	ContentType    string             `db:"content_type" json:"content_type"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Contest struct {
	ID             int64              `db:"id" json:"id"`
	OwnerUserID    int64              `db:"owner_user_id" json:"owner_user_id"`
	Title          string             `db:"title" json:"title"`
	Description    pgtype.Text        `db:"description" json:"description"`
	Visibility     string             `db:"visibility" json:"visibility"`
	Status         string             `db:"status" json:"status"`
	StartAt        pgtype.Timestamptz `db:"start_at" json:"start_at"`
	EndAt          pgtype.Timestamptz `db:"end_at" json:"end_at"`
	FreezeAt       pgtype.Timestamptz `db:"freeze_at" json:"freeze_at"`
	InviteCodeHash pgtype.Text        `db:"invite_code_hash" json:"invite_code_hash"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type ContestProblem struct {
	ContestID int64  `db:"contest_id" json:"contest_id"`
	ProblemID int64  `db:"problem_id" json:"problem_id"`
	Alias     string `db:"alias" json:"alias"`
	SortOrder int32  `db:"sort_order" json:"sort_order"`
}

type ContestProblemResult struct {
	ContestID        int64              `db:"contest_id" json:"contest_id"`
	UserID           int64              `db:"user_id" json:"user_id"`
	ProblemID        int64              `db:"problem_id" json:"problem_id"`
	Status           string             `db:"status" json:"status"`
	Attempts         int32              `db:"attempts" json:"attempts"`
	AcceptedAt       pgtype.Timestamptz `db:"accepted_at" json:"accepted_at"`
	PenaltyMinutes   int32              `db:"penalty_minutes" json:"penalty_minutes"`
	LastSubmissionID pgtype.Int8        `db:"last_submission_id" json:"last_submission_id"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type ContestRegistration struct {
	ID           int64              `db:"id" json:"id"`
	ContestID    int64              `db:"contest_id" json:"contest_id"`
	UserID       int64              `db:"user_id" json:"user_id"`
	DisplayName  string             `db:"display_name" json:"display_name"`
	Email        string             `db:"email" json:"email"`
	Status       string             `db:"status" json:"status"`
	RegisteredAt pgtype.Timestamptz `db:"registered_at" json:"registered_at"`
}

type ContestScoreSnapshot struct {
	ID          int64              `db:"id" json:"id"`
	ContestID   int64              `db:"contest_id" json:"contest_id"`
	Kind        string             `db:"kind" json:"kind"`
	Payload     []byte             `db:"payload" json:"payload"`
	GeneratedAt pgtype.Timestamptz `db:"generated_at" json:"generated_at"`
}

type JudgeTask struct {
	ID           int64              `db:"id" json:"id"`
	SubmissionID int64              `db:"submission_id" json:"submission_id"`
	StreamID     pgtype.Text        `db:"stream_id" json:"stream_id"`
	Status       string             `db:"status" json:"status"`
	Attempts     int32              `db:"attempts" json:"attempts"`
	NextRunAt    pgtype.Timestamptz `db:"next_run_at" json:"next_run_at"`
	LastError    pgtype.Text        `db:"last_error" json:"last_error"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Language struct {
	ID                   int64              `db:"id" json:"id"`
	Engine               string             `db:"engine" json:"engine"`
	EngineLanguageID     string             `db:"engine_language_id" json:"engine_language_id"`
	Name                 string             `db:"name" json:"name"`
	Version              pgtype.Text        `db:"version" json:"version"`
	CompileCommand       pgtype.Text        `db:"compile_command" json:"compile_command"`
	RunCommand           pgtype.Text        `db:"run_command" json:"run_command"`
	DefaultTimeLimitMs   int32              `db:"default_time_limit_ms" json:"default_time_limit_ms"`
	DefaultMemoryLimitKb int32              `db:"default_memory_limit_kb" json:"default_memory_limit_kb"`
	Enabled              bool               `db:"enabled" json:"enabled"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Problem struct {
	ID            int64              `db:"id" json:"id"`
	OwnerUserID   int64              `db:"owner_user_id" json:"owner_user_id"`
	Title         string             `db:"title" json:"title"`
	Slug          string             `db:"slug" json:"slug"`
	Difficulty    string             `db:"difficulty" json:"difficulty"`
	Visibility    string             `db:"visibility" json:"visibility"`
	Status        string             `db:"status" json:"status"`
	TimeLimitMs   int32              `db:"time_limit_ms" json:"time_limit_ms"`
	MemoryLimitKb int32              `db:"memory_limit_kb" json:"memory_limit_kb"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	PublishedAt   pgtype.Timestamptz `db:"published_at" json:"published_at"`
}

type ProblemStatement struct {
	ID                int64              `db:"id" json:"id"`
	ProblemID         int64              `db:"problem_id" json:"problem_id"`
	Version           int32              `db:"version" json:"version"`
	Title             string             `db:"title" json:"title"`
	Description       string             `db:"description" json:"description"`
	InputDescription  pgtype.Text        `db:"input_description" json:"input_description"`
	OutputDescription pgtype.Text        `db:"output_description" json:"output_description"`
	Samples           []byte             `db:"samples" json:"samples"`
	Hint              pgtype.Text        `db:"hint" json:"hint"`
	Source            pgtype.Text        `db:"source" json:"source"`
	IsCurrent         bool               `db:"is_current" json:"is_current"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type ProblemTag struct {
	ID   int64  `db:"id" json:"id"`
	Name string `db:"name" json:"name"`
	Slug string `db:"slug" json:"slug"`
}

type ProblemTagLink struct {
	ProblemID int64 `db:"problem_id" json:"problem_id"`
	TagID     int64 `db:"tag_id" json:"tag_id"`
}

type RefreshToken struct {
	ID        int64              `db:"id" json:"id"`
	UserID    int64              `db:"user_id" json:"user_id"`
	TokenHash string             `db:"token_hash" json:"token_hash"`
	DeviceID  string             `db:"device_id" json:"device_id"`
	UserAgent pgtype.Text        `db:"user_agent" json:"user_agent"`
	Ip        *netip.Addr        `db:"ip" json:"ip"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	RevokedAt pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Run struct {
	ID               int64              `db:"id" json:"id"`
	UserID           int64              `db:"user_id" json:"user_id"`
	ProblemID        int64              `db:"problem_id" json:"problem_id"`
	LanguageID       int64              `db:"language_id" json:"language_id"`
	Status           string             `db:"status" json:"status"`
	SourceArtifactID pgtype.Int8        `db:"source_artifact_id" json:"source_artifact_id"`
	Stdin            pgtype.Text        `db:"stdin" json:"stdin"`
	Stdout           pgtype.Text        `db:"stdout" json:"stdout"`
	Stderr           pgtype.Text        `db:"stderr" json:"stderr"`
	CompileOutput    pgtype.Text        `db:"compile_output" json:"compile_output"`
	TimeMs           pgtype.Int4        `db:"time_ms" json:"time_ms"`
	MemoryKb         pgtype.Int4        `db:"memory_kb" json:"memory_kb"`
	ErrorMessage     pgtype.Text        `db:"error_message" json:"error_message"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	FinishedAt       pgtype.Timestamptz `db:"finished_at" json:"finished_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Submission struct {
	ID               int64              `db:"id" json:"id"`
	UserID           int64              `db:"user_id" json:"user_id"`
	ProblemID        int64              `db:"problem_id" json:"problem_id"`
	ContestID        pgtype.Int8        `db:"contest_id" json:"contest_id"`
	LanguageID       int64              `db:"language_id" json:"language_id"`
	TestcaseSetID    int64              `db:"testcase_set_id" json:"testcase_set_id"`
	Status           string             `db:"status" json:"status"`
	SourceArtifactID pgtype.Int8        `db:"source_artifact_id" json:"source_artifact_id"`
	TimeMs           pgtype.Int4        `db:"time_ms" json:"time_ms"`
	MemoryKb         pgtype.Int4        `db:"memory_kb" json:"memory_kb"`
	Score            int32              `db:"score" json:"score"`
	ErrorMessage     pgtype.Text        `db:"error_message" json:"error_message"`
	SubmittedAt      pgtype.Timestamptz `db:"submitted_at" json:"submitted_at"`
	JudgedAt         pgtype.Timestamptz `db:"judged_at" json:"judged_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type SubmissionResult struct {
	ID           int64              `db:"id" json:"id"`
	SubmissionID int64              `db:"submission_id" json:"submission_id"`
	Status       string             `db:"status" json:"status"`
	Score        int32              `db:"score" json:"score"`
	TimeMs       pgtype.Int4        `db:"time_ms" json:"time_ms"`
	MemoryKb     pgtype.Int4        `db:"memory_kb" json:"memory_kb"`
	Details      []byte             `db:"details" json:"details"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type TestcaseSet struct {
	ID             int64              `db:"id" json:"id"`
	ProblemID      int64              `db:"problem_id" json:"problem_id"`
	Version        int32              `db:"version" json:"version"`
	StorageKey     string             `db:"storage_key" json:"storage_key"`
	ChecksumSha256 string             `db:"checksum_sha256" json:"checksum_sha256"`
	SizeBytes      int64              `db:"size_bytes" json:"size_bytes"`
	CaseCount      int32              `db:"case_count" json:"case_count"`
	Status         string             `db:"status" json:"status"`
	IsCurrent      bool               `db:"is_current" json:"is_current"`
	CreatedBy      int64              `db:"created_by" json:"created_by"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type User struct {
	ID           int64              `db:"id" json:"id"`
	Email        string             `db:"email" json:"email"`
	PasswordHash string             `db:"password_hash" json:"password_hash"`
	Username     string             `db:"username" json:"username"`
	AvatarUrl    pgtype.Text        `db:"avatar_url" json:"avatar_url"`
	Bio          pgtype.Text        `db:"bio" json:"bio"`
	Role         string             `db:"role" json:"role"`
	Status       string             `db:"status" json:"status"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}
