// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: problem_reviews.sql

package db

import (
	"context"
)

const countProblemsForReview = `-- name: CountProblemsForReview :one
SELECT count(*)::bigint
FROM problems
WHERE status = 'in_review'
`

func (q *Queries) CountProblemsForReview(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countProblemsForReview)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createProblemReviewEvent = `-- name: CreateProblemReviewEvent :one

INSERT INTO problem_review_events (
    problem_id,
    actor_user_id,
    from_status,
    to_status,
    decision,
    comment
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, problem_id, actor_user_id, from_status, to_status, decision, comment, created_at
`

type CreateProblemReviewEventParams struct {
	ProblemID   int64  `db:"problem_id" json:"problem_id"`
	ActorUserID int64  `db:"actor_user_id" json:"actor_user_id"`
	FromStatus  string `db:"from_status" json:"from_status"`
	ToStatus    string `db:"to_status" json:"to_status"`
	Decision    string `db:"decision" json:"decision"`
	Comment     string `db:"comment" json:"comment"`
}

// Problem review workflow.
func (q *Queries) CreateProblemReviewEvent(ctx context.Context, arg CreateProblemReviewEventParams) (ProblemReviewEvent, error) {
	row := q.db.QueryRow(ctx, createProblemReviewEvent,
		arg.ProblemID,
		arg.ActorUserID,
		arg.FromStatus,
		arg.ToStatus,
		arg.Decision,
		arg.Comment,
	)
	var i ProblemReviewEvent
	err := row.Scan(
		&i.ID,
		&i.ProblemID,
		&i.ActorUserID,
		&i.FromStatus,
		&i.ToStatus,
		&i.Decision,
		&i.Comment,
		&i.CreatedAt,
	)
	return i, err
}

const listProblemReviewEvents = `-- name: ListProblemReviewEvents :many
SELECT id, problem_id, actor_user_id, from_status, to_status, decision, comment, created_at
FROM problem_review_events
WHERE problem_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListProblemReviewEvents(ctx context.Context, problemID int64) ([]ProblemReviewEvent, error) {
	rows, err := q.db.Query(ctx, listProblemReviewEvents, problemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProblemReviewEvent
	for rows.Next() {
		var i ProblemReviewEvent
		if err := rows.Scan(
			&i.ID,
			&i.ProblemID,
			&i.ActorUserID,
			&i.FromStatus,
			&i.ToStatus,
			&i.Decision,
			&i.Comment,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProblemsForReview = `-- name: ListProblemsForReview :many
SELECT p.id, p.owner_user_id, p.title, p.slug, p.difficulty, p.visibility, p.status, p.time_limit_ms, p.memory_limit_kb, p.created_at, p.updated_at, p.published_at
FROM problems p
WHERE p.status = 'in_review'
ORDER BY p.updated_at ASC, p.id ASC
LIMIT $1 OFFSET $2
`

type ListProblemsForReviewParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) ListProblemsForReview(ctx context.Context, arg ListProblemsForReviewParams) ([]Problem, error) {
	rows, err := q.db.Query(ctx, listProblemsForReview, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Problem
	for rows.Next() {
		var i Problem
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Title,
			&i.Slug,
			&i.Difficulty,
			&i.Visibility,
			&i.Status,
			&i.TimeLimitMs,
			&i.MemoryLimitKb,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
