// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: problems.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveProblem = `-- name: ArchiveProblem :one
UPDATE problems
SET status = 'archived',
    updated_at = now()
WHERE id = $1
RETURNING id, owner_user_id, title, slug, difficulty, visibility, status, time_limit_ms, memory_limit_kb, created_at, updated_at, published_at
`

func (q *Queries) ArchiveProblem(ctx context.Context, id int64) (Problem, error) {
	row := q.db.QueryRow(ctx, archiveProblem, id)
	var i Problem
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Title,
		&i.Slug,
		&i.Difficulty,
		&i.Visibility,
		&i.Status,
		&i.TimeLimitMs,
		&i.MemoryLimitKb,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const clearCurrentProblemStatement = `-- name: ClearCurrentProblemStatement :exec
UPDATE problem_statements
SET is_current = false
WHERE problem_id = $1
  AND is_current = true
`

func (q *Queries) ClearCurrentProblemStatement(ctx context.Context, problemID int64) error {
	_, err := q.db.Exec(ctx, clearCurrentProblemStatement, problemID)
	return err
}

const clearCurrentTestcaseSet = `-- name: ClearCurrentTestcaseSet :exec
UPDATE testcase_sets
SET is_current = false
WHERE problem_id = $1
  AND is_current = true
`

func (q *Queries) ClearCurrentTestcaseSet(ctx context.Context, problemID int64) error {
	_, err := q.db.Exec(ctx, clearCurrentTestcaseSet, problemID)
	return err
}

const countProblems = `-- name: CountProblems :one
SELECT count(*)::bigint
FROM problems
WHERE ($1::text IS NULL OR difficulty = $1::text)
  AND ($2::text IS NULL OR status = $2::text)
  AND ($3::text IS NULL OR visibility = $3::text)
  AND (
      $4::text IS NULL
      OR title ILIKE '%' || $4::text || '%'
      OR slug ILIKE '%' || $4::text || '%'
  )
`

type CountProblemsParams struct {
	Difficulty pgtype.Text `db:"difficulty" json:"difficulty"`
	Status     pgtype.Text `db:"status" json:"status"`
	Visibility pgtype.Text `db:"visibility" json:"visibility"`
	Keyword    pgtype.Text `db:"keyword" json:"keyword"`
}

func (q *Queries) CountProblems(ctx context.Context, arg CountProblemsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProblems,
		arg.Difficulty,
		arg.Status,
		arg.Visibility,
		arg.Keyword,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createProblem = `-- name: CreateProblem :one

INSERT INTO problems (
    owner_user_id,
    title,
    slug,
    difficulty,
    visibility,
    status,
    time_limit_ms,
    memory_limit_kb
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, owner_user_id, title, slug, difficulty, visibility, status, time_limit_ms, memory_limit_kb, created_at, updated_at, published_at
`

type CreateProblemParams struct {
	OwnerUserID   int64  `db:"owner_user_id" json:"owner_user_id"`
	Title         string `db:"title" json:"title"`
	Slug          string `db:"slug" json:"slug"`
	Difficulty    string `db:"difficulty" json:"difficulty"`
	Visibility    string `db:"visibility" json:"visibility"`
	Status        string `db:"status" json:"status"`
	TimeLimitMs   int32  `db:"time_limit_ms" json:"time_limit_ms"`
	MemoryLimitKb int32  `db:"memory_limit_kb" json:"memory_limit_kb"`
}

// Owner: WP3 Problem/Storage
func (q *Queries) CreateProblem(ctx context.Context, arg CreateProblemParams) (Problem, error) {
	row := q.db.QueryRow(ctx, createProblem,
		arg.OwnerUserID,
		arg.Title,
		arg.Slug,
		arg.Difficulty,
		arg.Visibility,
		arg.Status,
		arg.TimeLimitMs,
		arg.MemoryLimitKb,
	)
	var i Problem
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Title,
		&i.Slug,
		&i.Difficulty,
		&i.Visibility,
		&i.Status,
		&i.TimeLimitMs,
		&i.MemoryLimitKb,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const createProblemStatement = `-- name: CreateProblemStatement :one
INSERT INTO problem_statements (
    problem_id,
    version,
    title,
    description,
    input_description,
    output_description,
    samples,
    hint,
    source,
    is_current
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, problem_id, version, title, description, input_description, output_description, samples, hint, source, is_current, created_at
`

type CreateProblemStatementParams struct {
	ProblemID         int64       `db:"problem_id" json:"problem_id"`
	Version           int32       `db:"version" json:"version"`
	Title             string      `db:"title" json:"title"`
	Description       string      `db:"description" json:"description"`
	InputDescription  pgtype.Text `db:"input_description" json:"input_description"`
	OutputDescription pgtype.Text `db:"output_description" json:"output_description"`
	Samples           []byte      `db:"samples" json:"samples"`
	Hint              pgtype.Text `db:"hint" json:"hint"`
	Source            pgtype.Text `db:"source" json:"source"`
	IsCurrent         bool        `db:"is_current" json:"is_current"`
}

func (q *Queries) CreateProblemStatement(ctx context.Context, arg CreateProblemStatementParams) (ProblemStatement, error) {
	row := q.db.QueryRow(ctx, createProblemStatement,
		arg.ProblemID,
		arg.Version,
		arg.Title,
		arg.Description,
		arg.InputDescription,
		arg.OutputDescription,
		arg.Samples,
		arg.Hint,
		arg.Source,
		arg.IsCurrent,
	)
	var i ProblemStatement
	err := row.Scan(
		&i.ID,
		&i.ProblemID,
		&i.Version,
		&i.Title,
		&i.Description,
		&i.InputDescription,
		&i.OutputDescription,
		&i.Samples,
		&i.Hint,
		&i.Source,
		&i.IsCurrent,
		&i.CreatedAt,
	)
	return i, err
}

const createProblemTag = `-- name: CreateProblemTag :one
INSERT INTO problem_tags (name, slug)
VALUES ($1, $2)
ON CONFLICT (slug) DO UPDATE
SET name = EXCLUDED.name
RETURNING id, name, slug
`

type CreateProblemTagParams struct {
	Name string `db:"name" json:"name"`
	Slug string `db:"slug" json:"slug"`
}

func (q *Queries) CreateProblemTag(ctx context.Context, arg CreateProblemTagParams) (ProblemTag, error) {
	row := q.db.QueryRow(ctx, createProblemTag, arg.Name, arg.Slug)
	var i ProblemTag
	err := row.Scan(&i.ID, &i.Name, &i.Slug)
	return i, err
}

const createTestcaseSet = `-- name: CreateTestcaseSet :one
INSERT INTO testcase_sets (
    problem_id,
    version,
    storage_key,
    checksum_sha256,
    size_bytes,
    case_count,
    status,
    is_current,
    created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, problem_id, version, storage_key, checksum_sha256, size_bytes, case_count, status, is_current, created_by, created_at
`

type CreateTestcaseSetParams struct {
	ProblemID      int64  `db:"problem_id" json:"problem_id"`
	Version        int32  `db:"version" json:"version"`
	StorageKey     string `db:"storage_key" json:"storage_key"`
	ChecksumSha256 string `db:"checksum_sha256" json:"checksum_sha256"`
	SizeBytes      int64  `db:"size_bytes" json:"size_bytes"`
	CaseCount      int32  `db:"case_count" json:"case_count"`
	Status         string `db:"status" json:"status"`
	IsCurrent      bool   `db:"is_current" json:"is_current"`
	CreatedBy      int64  `db:"created_by" json:"created_by"`
}

func (q *Queries) CreateTestcaseSet(ctx context.Context, arg CreateTestcaseSetParams) (TestcaseSet, error) {
	row := q.db.QueryRow(ctx, createTestcaseSet,
		arg.ProblemID,
		arg.Version,
		arg.StorageKey,
		arg.ChecksumSha256,
		arg.SizeBytes,
		arg.CaseCount,
		arg.Status,
		arg.IsCurrent,
		arg.CreatedBy,
	)
	var i TestcaseSet
	err := row.Scan(
		&i.ID,
		&i.ProblemID,
		&i.Version,
		&i.StorageKey,
		&i.ChecksumSha256,
		&i.SizeBytes,
		&i.CaseCount,
		&i.Status,
		&i.IsCurrent,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getCurrentProblemStatement = `-- name: GetCurrentProblemStatement :one
SELECT id, problem_id, version, title, description, input_description, output_description, samples, hint, source, is_current, created_at
FROM problem_statements
WHERE problem_id = $1
  AND is_current = true
`

func (q *Queries) GetCurrentProblemStatement(ctx context.Context, problemID int64) (ProblemStatement, error) {
	row := q.db.QueryRow(ctx, getCurrentProblemStatement, problemID)
	var i ProblemStatement
	err := row.Scan(
		&i.ID,
		&i.ProblemID,
		&i.Version,
		&i.Title,
		&i.Description,
		&i.InputDescription,
		&i.OutputDescription,
		&i.Samples,
		&i.Hint,
		&i.Source,
		&i.IsCurrent,
		&i.CreatedAt,
	)
	return i, err
}

const getCurrentReadyTestcaseSet = `-- name: GetCurrentReadyTestcaseSet :one
SELECT id, problem_id, version, storage_key, checksum_sha256, size_bytes, case_count, status, is_current, created_by, created_at
FROM testcase_sets
WHERE problem_id = $1
  AND is_current = true
  AND status = 'ready'
`

func (q *Queries) GetCurrentReadyTestcaseSet(ctx context.Context, problemID int64) (TestcaseSet, error) {
	row := q.db.QueryRow(ctx, getCurrentReadyTestcaseSet, problemID)
	var i TestcaseSet
	err := row.Scan(
		&i.ID,
		&i.ProblemID,
		&i.Version,
		&i.StorageKey,
		&i.ChecksumSha256,
		&i.SizeBytes,
		&i.CaseCount,
		&i.Status,
		&i.IsCurrent,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getProblemByID = `-- name: GetProblemByID :one
SELECT id, owner_user_id, title, slug, difficulty, visibility, status, time_limit_ms, memory_limit_kb, created_at, updated_at, published_at
FROM problems
WHERE id = $1
`

func (q *Queries) GetProblemByID(ctx context.Context, id int64) (Problem, error) {
	row := q.db.QueryRow(ctx, getProblemByID, id)
	var i Problem
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Title,
		&i.Slug,
		&i.Difficulty,
		&i.Visibility,
		&i.Status,
		&i.TimeLimitMs,
		&i.MemoryLimitKb,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const getProblemBySlug = `-- name: GetProblemBySlug :one
SELECT id, owner_user_id, title, slug, difficulty, visibility, status, time_limit_ms, memory_limit_kb, created_at, updated_at, published_at
FROM problems
WHERE slug = $1
`

func (q *Queries) GetProblemBySlug(ctx context.Context, slug string) (Problem, error) {
	row := q.db.QueryRow(ctx, getProblemBySlug, slug)
	var i Problem
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Title,
		&i.Slug,
		&i.Difficulty,
		&i.Visibility,
		&i.Status,
		&i.TimeLimitMs,
		&i.MemoryLimitKb,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const getProblemStats = `-- name: GetProblemStats :one
SELECT
    p.id AS problem_id,
    count(s.id)::bigint AS total_submissions,
    count(s.id) FILTER (WHERE s.status = 'accepted')::bigint AS accepted_submissions,
    coalesce(jsonb_object_agg(s.status, status_counts.count) FILTER (WHERE s.status IS NOT NULL), '{}'::jsonb) AS status_counts
FROM problems p
LEFT JOIN submissions s ON s.problem_id = p.id
LEFT JOIN (
    SELECT problem_id, status, count(*)::bigint AS count
    FROM submissions
    GROUP BY problem_id, status
) status_counts ON status_counts.problem_id = s.problem_id AND status_counts.status = s.status
WHERE p.id = $1
GROUP BY p.id
`

type GetProblemStatsRow struct {
	ProblemID           int64       `db:"problem_id" json:"problem_id"`
	TotalSubmissions    int64       `db:"total_submissions" json:"total_submissions"`
	AcceptedSubmissions int64       `db:"accepted_submissions" json:"accepted_submissions"`
	StatusCounts        interface{} `db:"status_counts" json:"status_counts"`
}

func (q *Queries) GetProblemStats(ctx context.Context, id int64) (GetProblemStatsRow, error) {
	row := q.db.QueryRow(ctx, getProblemStats, id)
	var i GetProblemStatsRow
	err := row.Scan(
		&i.ProblemID,
		&i.TotalSubmissions,
		&i.AcceptedSubmissions,
		&i.StatusCounts,
	)
	return i, err
}

const linkProblemTag = `-- name: LinkProblemTag :exec
INSERT INTO problem_tag_links (problem_id, tag_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type LinkProblemTagParams struct {
	ProblemID int64 `db:"problem_id" json:"problem_id"`
	TagID     int64 `db:"tag_id" json:"tag_id"`
}

func (q *Queries) LinkProblemTag(ctx context.Context, arg LinkProblemTagParams) error {
	_, err := q.db.Exec(ctx, linkProblemTag, arg.ProblemID, arg.TagID)
	return err
}

const listProblemTags = `-- name: ListProblemTags :many
SELECT pt.id, pt.name, pt.slug
FROM problem_tags pt
JOIN problem_tag_links ptl ON ptl.tag_id = pt.id
WHERE ptl.problem_id = $1
ORDER BY pt.name
`

func (q *Queries) ListProblemTags(ctx context.Context, problemID int64) ([]ProblemTag, error) {
	rows, err := q.db.Query(ctx, listProblemTags, problemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProblemTag
	for rows.Next() {
		var i ProblemTag
		if err := rows.Scan(&i.ID, &i.Name, &i.Slug); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProblems = `-- name: ListProblems :many
SELECT id, owner_user_id, title, slug, difficulty, visibility, status, time_limit_ms, memory_limit_kb, created_at, updated_at, published_at
FROM problems
WHERE ($1::text IS NULL OR difficulty = $1::text)
  AND ($2::text IS NULL OR status = $2::text)
  AND ($3::text IS NULL OR visibility = $3::text)
  AND (
      $4::text IS NULL
      OR title ILIKE '%' || $4::text || '%'
      OR slug ILIKE '%' || $4::text || '%'
  )
ORDER BY created_at DESC, id DESC
LIMIT $6 OFFSET $5
`

type ListProblemsParams struct {
	Difficulty pgtype.Text `db:"difficulty" json:"difficulty"`
	Status     pgtype.Text `db:"status" json:"status"`
	Visibility pgtype.Text `db:"visibility" json:"visibility"`
	Keyword    pgtype.Text `db:"keyword" json:"keyword"`
	Offset     int32       `db:"offset" json:"offset"`
	Limit      int32       `db:"limit" json:"limit"`
}

func (q *Queries) ListProblems(ctx context.Context, arg ListProblemsParams) ([]Problem, error) {
	rows, err := q.db.Query(ctx, listProblems,
		arg.Difficulty,
		arg.Status,
		arg.Visibility,
		arg.Keyword,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Problem
	for rows.Next() {
		var i Problem
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Title,
			&i.Slug,
			&i.Difficulty,
			&i.Visibility,
			&i.Status,
			&i.TimeLimitMs,
			&i.MemoryLimitKb,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockProblemForUpdate = `-- name: LockProblemForUpdate :one
SELECT id, owner_user_id, title, slug, difficulty, visibility, status, time_limit_ms, memory_limit_kb, created_at, updated_at, published_at
FROM problems
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockProblemForUpdate(ctx context.Context, id int64) (Problem, error) {
	row := q.db.QueryRow(ctx, lockProblemForUpdate, id)
	var i Problem
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Title,
		&i.Slug,
		&i.Difficulty,
		&i.Visibility,
		&i.Status,
		&i.TimeLimitMs,
		&i.MemoryLimitKb,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const nextProblemStatementVersion = `-- name: NextProblemStatementVersion :one
SELECT coalesce(max(version), 0)::integer + 1 AS next_version
FROM problem_statements
WHERE problem_id = $1
`

func (q *Queries) NextProblemStatementVersion(ctx context.Context, problemID int64) (int32, error) {
	row := q.db.QueryRow(ctx, nextProblemStatementVersion, problemID)
	var next_version int32
	err := row.Scan(&next_version)
	return next_version, err
}

const nextTestcaseSetVersion = `-- name: NextTestcaseSetVersion :one
SELECT coalesce(max(version), 0)::integer + 1 AS next_version
FROM testcase_sets
WHERE problem_id = $1
`

func (q *Queries) NextTestcaseSetVersion(ctx context.Context, problemID int64) (int32, error) {
	row := q.db.QueryRow(ctx, nextTestcaseSetVersion, problemID)
	var next_version int32
	err := row.Scan(&next_version)
	return next_version, err
}

const updateProblem = `-- name: UpdateProblem :one
UPDATE problems
SET title = coalesce($1, title),
    slug = coalesce($2, slug),
    difficulty = coalesce($3, difficulty),
    visibility = coalesce($4, visibility),
    status = coalesce($5, status),
    time_limit_ms = coalesce($6, time_limit_ms),
    memory_limit_kb = coalesce($7, memory_limit_kb),
    published_at = CASE
        WHEN $5::text = 'published' AND published_at IS NULL THEN now()
        WHEN $5::text IS NULL THEN published_at
        ELSE published_at
    END,
    updated_at = now()
WHERE id = $8
RETURNING id, owner_user_id, title, slug, difficulty, visibility, status, time_limit_ms, memory_limit_kb, created_at, updated_at, published_at
`

type UpdateProblemParams struct {
	Title         pgtype.Text `db:"title" json:"title"`
	Slug          pgtype.Text `db:"slug" json:"slug"`
	Difficulty    pgtype.Text `db:"difficulty" json:"difficulty"`
	Visibility    pgtype.Text `db:"visibility" json:"visibility"`
	Status        pgtype.Text `db:"status" json:"status"`
	TimeLimitMs   pgtype.Int4 `db:"time_limit_ms" json:"time_limit_ms"`
	MemoryLimitKb pgtype.Int4 `db:"memory_limit_kb" json:"memory_limit_kb"`
	ID            int64       `db:"id" json:"id"`
}

func (q *Queries) UpdateProblem(ctx context.Context, arg UpdateProblemParams) (Problem, error) {
	row := q.db.QueryRow(ctx, updateProblem,
		arg.Title,
		arg.Slug,
		arg.Difficulty,
		arg.Visibility,
		arg.Status,
		arg.TimeLimitMs,
		arg.MemoryLimitKb,
		arg.ID,
	)
	var i Problem
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Title,
		&i.Slug,
		&i.Difficulty,
		&i.Visibility,
		&i.Status,
		&i.TimeLimitMs,
		&i.MemoryLimitKb,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
	)
	return i, err
}
