// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: problem_reviews.sql

package db

import (
	"context"
)

const countProblemsForReview = `-- name: CountProblemsForReview :one
SELECT count(*)::bigint
FROM problems
WHERE status = 'in_review'
`

func (q *Queries) CountProblemsForReview(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countProblemsForReview)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProblemReviewEvent = `-- name: CreateProblemReviewEvent :one
INSERT INTO problem_review_events (
    problem_id,
    actor_user_id,
    from_status,
    to_status,
    decision,
    comment
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, problem_id, actor_user_id, from_status, to_status, decision, comment, created_at
`

type CreateProblemReviewEventParams struct {
	ProblemID   int64  `db:"problem_id" json:"problem_id"`
	ActorUserID int64  `db:"actor_user_id" json:"actor_user_id"`
	FromStatus  string `db:"from_status" json:"from_status"`
	ToStatus    string `db:"to_status" json:"to_status"`
	Decision    string `db:"decision" json:"decision"`
	Comment     string `db:"comment" json:"comment"`
}

func (q *Queries) CreateProblemReviewEvent(ctx context.Context, arg CreateProblemReviewEventParams) (ProblemReviewEvent, error) {
	row := q.db.QueryRow(ctx, createProblemReviewEvent,
		arg.ProblemID,
		arg.ActorUserID,
		arg.FromStatus,
		arg.ToStatus,
		arg.Decision,
		arg.Comment,
	)
	var event ProblemReviewEvent
	err := row.Scan(
		&event.ID,
		&event.ProblemID,
		&event.ActorUserID,
		&event.FromStatus,
		&event.ToStatus,
		&event.Decision,
		&event.Comment,
		&event.CreatedAt,
	)
	return event, err
}

const listProblemReviewEvents = `-- name: ListProblemReviewEvents :many
SELECT id, problem_id, actor_user_id, from_status, to_status, decision, comment, created_at
FROM problem_review_events
WHERE problem_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListProblemReviewEvents(ctx context.Context, problemID int64) ([]ProblemReviewEvent, error) {
	rows, err := q.db.Query(ctx, listProblemReviewEvents, problemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := make([]ProblemReviewEvent, 0)
	for rows.Next() {
		var event ProblemReviewEvent
		if err := rows.Scan(
			&event.ID,
			&event.ProblemID,
			&event.ActorUserID,
			&event.FromStatus,
			&event.ToStatus,
			&event.Decision,
			&event.Comment,
			&event.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, event)
	}
	return items, rows.Err()
}

const listProblemsForReview = `-- name: ListProblemsForReview :many
SELECT id, owner_user_id, title, slug, difficulty, visibility, status, time_limit_ms, memory_limit_kb, created_at, updated_at, published_at
FROM problems
WHERE status = 'in_review'
ORDER BY updated_at ASC, id ASC
LIMIT $1 OFFSET $2
`

type ListProblemsForReviewParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) ListProblemsForReview(ctx context.Context, arg ListProblemsForReviewParams) ([]Problem, error) {
	rows, err := q.db.Query(ctx, listProblemsForReview, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := make([]Problem, 0)
	for rows.Next() {
		var problem Problem
		if err := rows.Scan(
			&problem.ID,
			&problem.OwnerUserID,
			&problem.Title,
			&problem.Slug,
			&problem.Difficulty,
			&problem.Visibility,
			&problem.Status,
			&problem.TimeLimitMs,
			&problem.MemoryLimitKb,
			&problem.CreatedAt,
			&problem.UpdatedAt,
			&problem.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, problem)
	}
	return items, rows.Err()
}
