// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	AddContestProblem(ctx context.Context, arg AddContestProblemParams) (ContestProblem, error)
	ArchiveContest(ctx context.Context, id int64) (Contest, error)
	ArchiveProblem(ctx context.Context, id int64) (Problem, error)
	ClaimPendingJudgeTasks(ctx context.Context, limit int32) ([]JudgeTask, error)
	ClearCurrentProblemStatement(ctx context.Context, problemID int64) error
	ClearCurrentTestcaseSet(ctx context.Context, problemID int64) error
	ClearProblemTags(ctx context.Context, problemID int64) error
	CountContests(ctx context.Context, arg CountContestsParams) (int64, error)
	CountLanguages(ctx context.Context, arg CountLanguagesParams) (int64, error)
	CountProblems(ctx context.Context, arg CountProblemsParams) (int64, error)
	CountSubmissions(ctx context.Context, arg CountSubmissionsParams) (int64, error)
	CountUsers(ctx context.Context, arg CountUsersParams) (int64, error)
	// Owner: WP4 Submission/Run
	CreateArtifact(ctx context.Context, arg CreateArtifactParams) (Artifact, error)
	// Owner: WP5 Contest
	CreateContest(ctx context.Context, arg CreateContestParams) (Contest, error)
	CreateContestRegistration(ctx context.Context, arg CreateContestRegistrationParams) (ContestRegistration, error)
	CreateContestScoreSnapshot(ctx context.Context, arg CreateContestScoreSnapshotParams) (ContestScoreSnapshot, error)
	CreateJudgeTask(ctx context.Context, arg CreateJudgeTaskParams) (JudgeTask, error)
	// Owner: WP3 Problem/Storage
	CreateProblem(ctx context.Context, arg CreateProblemParams) (Problem, error)
	CreateProblemStatement(ctx context.Context, arg CreateProblemStatementParams) (ProblemStatement, error)
	CreateProblemTag(ctx context.Context, arg CreateProblemTagParams) (ProblemTag, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateRun(ctx context.Context, arg CreateRunParams) (Run, error)
	CreateSubmission(ctx context.Context, arg CreateSubmissionParams) (Submission, error)
	CreateTestcaseSet(ctx context.Context, arg CreateTestcaseSetParams) (TestcaseSet, error)
	// Owner: WP2 Auth/User
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteContestProblems(ctx context.Context, contestID int64) error
	GetArtifactByID(ctx context.Context, id int64) (Artifact, error)
	GetContestByID(ctx context.Context, id int64) (Contest, error)
	GetContestRegistration(ctx context.Context, arg GetContestRegistrationParams) (ContestRegistration, error)
	GetCurrentProblemStatement(ctx context.Context, problemID int64) (ProblemStatement, error)
	GetCurrentReadyTestcaseSet(ctx context.Context, problemID int64) (TestcaseSet, error)
	GetEnabledLanguageByID(ctx context.Context, id int64) (Language, error)
	GetJudgeTaskByID(ctx context.Context, id int64) (JudgeTask, error)
	GetJudgeTaskBySubmissionID(ctx context.Context, submissionID int64) (JudgeTask, error)
	GetLanguageByID(ctx context.Context, id int64) (Language, error)
	GetLatestContestScoreSnapshot(ctx context.Context, arg GetLatestContestScoreSnapshotParams) (ContestScoreSnapshot, error)
	GetProblemByID(ctx context.Context, id int64) (GetProblemByIDRow, error)
	GetProblemBySlug(ctx context.Context, slug string) (GetProblemBySlugRow, error)
	GetProblemStats(ctx context.Context, id int64) (GetProblemStatsRow, error)
	GetReadyTestcaseSetByID(ctx context.Context, arg GetReadyTestcaseSetByIDParams) (TestcaseSet, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetRunByID(ctx context.Context, id int64) (Run, error)
	GetSubmissionByID(ctx context.Context, id int64) (Submission, error)
	GetUserByEmail(ctx context.Context, lower string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	LinkProblemTag(ctx context.Context, arg LinkProblemTagParams) error
	ListContestProblemResults(ctx context.Context, contestID int64) ([]ContestProblemResult, error)
	ListContestProblems(ctx context.Context, contestID int64) ([]ContestProblem, error)
	ListContestRegistrations(ctx context.Context, arg ListContestRegistrationsParams) ([]ContestRegistration, error)
	ListContestTerminalSubmissions(ctx context.Context, dollar_1 int64) ([]ListContestTerminalSubmissionsRow, error)
	ListContests(ctx context.Context, arg ListContestsParams) ([]Contest, error)
	ListLanguages(ctx context.Context, arg ListLanguagesParams) ([]Language, error)
	ListProblemTags(ctx context.Context, problemID int64) ([]ProblemTag, error)
	ListProblems(ctx context.Context, arg ListProblemsParams) ([]ListProblemsRow, error)
	ListSubmissions(ctx context.Context, arg ListSubmissionsParams) ([]Submission, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	LockProblemForUpdate(ctx context.Context, id int64) (LockProblemForUpdateRow, error)
	MarkJudgeTaskDead(ctx context.Context, arg MarkJudgeTaskDeadParams) (JudgeTask, error)
	MarkJudgeTaskDispatched(ctx context.Context, arg MarkJudgeTaskDispatchedParams) (JudgeTask, error)
	MarkJudgeTaskDone(ctx context.Context, id int64) (JudgeTask, error)
	MarkJudgeTaskRunning(ctx context.Context, id int64) (JudgeTask, error)
	MarkStaleRunsSystemError(ctx context.Context, arg MarkStaleRunsSystemErrorParams) ([]Run, error)
	MarkSubmissionQueued(ctx context.Context, arg MarkSubmissionQueuedParams) (Submission, error)
	MarkSubmissionRunning(ctx context.Context, id int64) (Submission, error)
	MarkSubmissionSystemError(ctx context.Context, arg MarkSubmissionSystemErrorParams) (Submission, error)
	NextProblemStatementVersion(ctx context.Context, problemID int64) (int32, error)
	NextTestcaseSetVersion(ctx context.Context, problemID int64) (int32, error)
	ResetStaleJudgeTasks(ctx context.Context, arg ResetStaleJudgeTasksParams) ([]ResetStaleJudgeTasksRow, error)
	RetryJudgeTask(ctx context.Context, arg RetryJudgeTaskParams) (JudgeTask, error)
	RevokeRefreshToken(ctx context.Context, tokenHash string) error
	RevokeUserDeviceRefreshTokens(ctx context.Context, arg RevokeUserDeviceRefreshTokensParams) error
	UpdateContest(ctx context.Context, arg UpdateContestParams) (Contest, error)
	UpdateJudgeTaskDispatching(ctx context.Context, id int64) (JudgeTask, error)
	UpdateLanguageAdminFields(ctx context.Context, arg UpdateLanguageAdminFieldsParams) (Language, error)
	UpdateProblem(ctx context.Context, arg UpdateProblemParams) (Problem, error)
	UpdateRunStatus(ctx context.Context, arg UpdateRunStatusParams) (Run, error)
	UpdateSubmissionStatus(ctx context.Context, arg UpdateSubmissionStatusParams) (Submission, error)
	UpdateUserAdminFields(ctx context.Context, arg UpdateUserAdminFieldsParams) (User, error)
	UpsertContestProblemResult(ctx context.Context, arg UpsertContestProblemResultParams) (ContestProblemResult, error)
	// Owner: WP4 Submission/Language
	// Sync intentionally preserves enabled on existing rows so JudgeEngine language
	// refreshes do not re-enable languages disabled by an admin.
	UpsertLanguage(ctx context.Context, arg UpsertLanguageParams) (Language, error)
}

var _ Querier = (*Queries)(nil)
