// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: submissions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimPendingJudgeTasks = `-- name: ClaimPendingJudgeTasks :many
WITH claimed AS (
    SELECT id
    FROM judge_tasks
    WHERE status = 'pending'
      AND next_run_at <= now()
    ORDER BY next_run_at, id
    LIMIT $1
    FOR UPDATE SKIP LOCKED
)
UPDATE judge_tasks
SET status = 'dispatching',
    updated_at = now()
FROM claimed
WHERE judge_tasks.id = claimed.id
  AND judge_tasks.status = 'pending'
RETURNING judge_tasks.id, judge_tasks.submission_id, judge_tasks.stream_id, judge_tasks.status, judge_tasks.attempts, judge_tasks.next_run_at, judge_tasks.last_error, judge_tasks.created_at, judge_tasks.updated_at
`

func (q *Queries) ClaimPendingJudgeTasks(ctx context.Context, limit int32) ([]JudgeTask, error) {
	rows, err := q.db.Query(ctx, claimPendingJudgeTasks, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JudgeTask
	for rows.Next() {
		var i JudgeTask
		if err := rows.Scan(
			&i.ID,
			&i.SubmissionID,
			&i.StreamID,
			&i.Status,
			&i.Attempts,
			&i.NextRunAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countSubmissions = `-- name: CountSubmissions :one
SELECT count(*)::bigint
FROM submissions
WHERE ($1::bigint IS NULL OR user_id = $1::bigint)
  AND ($2::bigint IS NULL OR problem_id = $2::bigint)
  AND ($3::bigint IS NULL OR contest_id = $3::bigint)
  AND ($4::text IS NULL OR status = $4::text)
`

type CountSubmissionsParams struct {
	UserID    pgtype.Int8 `db:"user_id" json:"user_id"`
	ProblemID pgtype.Int8 `db:"problem_id" json:"problem_id"`
	ContestID pgtype.Int8 `db:"contest_id" json:"contest_id"`
	Status    pgtype.Text `db:"status" json:"status"`
}

func (q *Queries) CountSubmissions(ctx context.Context, arg CountSubmissionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSubmissions,
		arg.UserID,
		arg.ProblemID,
		arg.ContestID,
		arg.Status,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createArtifact = `-- name: CreateArtifact :one

INSERT INTO artifacts (
    owner_type,
    owner_id,
    kind,
    storage_key,
    checksum_sha256,
    size_bytes,
    content_type
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, owner_type, owner_id, kind, storage_key, checksum_sha256, size_bytes, content_type, created_at
`

type CreateArtifactParams struct {
	OwnerType      string `db:"owner_type" json:"owner_type"`
	OwnerID        int64  `db:"owner_id" json:"owner_id"`
	Kind           string `db:"kind" json:"kind"`
	StorageKey     string `db:"storage_key" json:"storage_key"`
	ChecksumSha256 string `db:"checksum_sha256" json:"checksum_sha256"`
	SizeBytes      int64  `db:"size_bytes" json:"size_bytes"`
	ContentType    string `db:"content_type" json:"content_type"`
}

// Owner: WP4 Submission/Run
func (q *Queries) CreateArtifact(ctx context.Context, arg CreateArtifactParams) (Artifact, error) {
	row := q.db.QueryRow(ctx, createArtifact,
		arg.OwnerType,
		arg.OwnerID,
		arg.Kind,
		arg.StorageKey,
		arg.ChecksumSha256,
		arg.SizeBytes,
		arg.ContentType,
	)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.OwnerType,
		&i.OwnerID,
		&i.Kind,
		&i.StorageKey,
		&i.ChecksumSha256,
		&i.SizeBytes,
		&i.ContentType,
		&i.CreatedAt,
	)
	return i, err
}

const createJudgeAttempt = `-- name: CreateJudgeAttempt :one
INSERT INTO judge_attempts (
    submission_id,
    run_id,
    task_id,
    attempt_no,
    protocol_version,
    judge_core_version,
    judge_engine,
    judge_agent_id,
    language_id,
    language_runtime,
    sandbox_backend,
    sandbox_profile,
    testcase_set_id,
    testcase_set_hash,
    checker_hash,
    validator_hash,
    status,
    verdict,
    score,
    time_ms,
    memory_kb,
    first_failed_case_index,
    first_failed_group,
    compile_output_summary,
    stderr_summary,
    checker_message,
    error_class,
    error_message,
    manifest,
    metrics,
    trace_id,
    started_at,
    finished_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17,
    $18,
    $19,
    $20,
    $21,
    $22,
    $23,
    $24,
    $25,
    $26,
    $27,
    $28,
    $29,
    $30,
    $31,
    $32,
    $33
)
RETURNING id, submission_id, run_id, task_id, attempt_no, protocol_version, judge_core_version, judge_engine, judge_agent_id, language_id, language_runtime, sandbox_backend, sandbox_profile, testcase_set_id, testcase_set_hash, checker_hash, validator_hash, status, verdict, score, time_ms, memory_kb, first_failed_case_index, first_failed_group, compile_output_summary, stderr_summary, checker_message, error_class, error_message, manifest, metrics, trace_id, started_at, finished_at, created_at, updated_at
`

type CreateJudgeAttemptParams struct {
	SubmissionID         pgtype.Int8        `db:"submission_id" json:"submission_id"`
	RunID                pgtype.Int8        `db:"run_id" json:"run_id"`
	TaskID               pgtype.Int8        `db:"task_id" json:"task_id"`
	AttemptNo            int32              `db:"attempt_no" json:"attempt_no"`
	ProtocolVersion      string             `db:"protocol_version" json:"protocol_version"`
	JudgeCoreVersion     string             `db:"judge_core_version" json:"judge_core_version"`
	JudgeEngine          string             `db:"judge_engine" json:"judge_engine"`
	JudgeAgentID         pgtype.Text        `db:"judge_agent_id" json:"judge_agent_id"`
	LanguageID           int64              `db:"language_id" json:"language_id"`
	LanguageRuntime      pgtype.Text        `db:"language_runtime" json:"language_runtime"`
	SandboxBackend       pgtype.Text        `db:"sandbox_backend" json:"sandbox_backend"`
	SandboxProfile       pgtype.Text        `db:"sandbox_profile" json:"sandbox_profile"`
	TestcaseSetID        pgtype.Int8        `db:"testcase_set_id" json:"testcase_set_id"`
	TestcaseSetHash      pgtype.Text        `db:"testcase_set_hash" json:"testcase_set_hash"`
	CheckerHash          pgtype.Text        `db:"checker_hash" json:"checker_hash"`
	ValidatorHash        pgtype.Text        `db:"validator_hash" json:"validator_hash"`
	Status               string             `db:"status" json:"status"`
	Verdict              pgtype.Text        `db:"verdict" json:"verdict"`
	Score                int32              `db:"score" json:"score"`
	TimeMs               pgtype.Int4        `db:"time_ms" json:"time_ms"`
	MemoryKb             pgtype.Int4        `db:"memory_kb" json:"memory_kb"`
	FirstFailedCaseIndex pgtype.Int4        `db:"first_failed_case_index" json:"first_failed_case_index"`
	FirstFailedGroup     pgtype.Text        `db:"first_failed_group" json:"first_failed_group"`
	CompileOutputSummary pgtype.Text        `db:"compile_output_summary" json:"compile_output_summary"`
	StderrSummary        pgtype.Text        `db:"stderr_summary" json:"stderr_summary"`
	CheckerMessage       pgtype.Text        `db:"checker_message" json:"checker_message"`
	ErrorClass           pgtype.Text        `db:"error_class" json:"error_class"`
	ErrorMessage         pgtype.Text        `db:"error_message" json:"error_message"`
	Manifest             []byte             `db:"manifest" json:"manifest"`
	Metrics              []byte             `db:"metrics" json:"metrics"`
	TraceID              pgtype.Text        `db:"trace_id" json:"trace_id"`
	StartedAt            pgtype.Timestamptz `db:"started_at" json:"started_at"`
	FinishedAt           pgtype.Timestamptz `db:"finished_at" json:"finished_at"`
}

func (q *Queries) CreateJudgeAttempt(ctx context.Context, arg CreateJudgeAttemptParams) (JudgeAttempt, error) {
	row := q.db.QueryRow(ctx, createJudgeAttempt,
		arg.SubmissionID,
		arg.RunID,
		arg.TaskID,
		arg.AttemptNo,
		arg.ProtocolVersion,
		arg.JudgeCoreVersion,
		arg.JudgeEngine,
		arg.JudgeAgentID,
		arg.LanguageID,
		arg.LanguageRuntime,
		arg.SandboxBackend,
		arg.SandboxProfile,
		arg.TestcaseSetID,
		arg.TestcaseSetHash,
		arg.CheckerHash,
		arg.ValidatorHash,
		arg.Status,
		arg.Verdict,
		arg.Score,
		arg.TimeMs,
		arg.MemoryKb,
		arg.FirstFailedCaseIndex,
		arg.FirstFailedGroup,
		arg.CompileOutputSummary,
		arg.StderrSummary,
		arg.CheckerMessage,
		arg.ErrorClass,
		arg.ErrorMessage,
		arg.Manifest,
		arg.Metrics,
		arg.TraceID,
		arg.StartedAt,
		arg.FinishedAt,
	)
	var i JudgeAttempt
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.RunID,
		&i.TaskID,
		&i.AttemptNo,
		&i.ProtocolVersion,
		&i.JudgeCoreVersion,
		&i.JudgeEngine,
		&i.JudgeAgentID,
		&i.LanguageID,
		&i.LanguageRuntime,
		&i.SandboxBackend,
		&i.SandboxProfile,
		&i.TestcaseSetID,
		&i.TestcaseSetHash,
		&i.CheckerHash,
		&i.ValidatorHash,
		&i.Status,
		&i.Verdict,
		&i.Score,
		&i.TimeMs,
		&i.MemoryKb,
		&i.FirstFailedCaseIndex,
		&i.FirstFailedGroup,
		&i.CompileOutputSummary,
		&i.StderrSummary,
		&i.CheckerMessage,
		&i.ErrorClass,
		&i.ErrorMessage,
		&i.Manifest,
		&i.Metrics,
		&i.TraceID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createJudgeCaseResult = `-- name: CreateJudgeCaseResult :one
INSERT INTO judge_case_results (
    attempt_id,
    case_index,
    group_name,
    testcase_key,
    status,
    score,
    time_ms,
    memory_kb,
    exit_code,
    signal,
    checker_message,
    output_diff_summary,
    stdout_artifact_id,
    stderr_artifact_id,
    diff_artifact_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15
)
RETURNING id, attempt_id, case_index, group_name, testcase_key, status, score, time_ms, memory_kb, exit_code, signal, checker_message, output_diff_summary, stdout_artifact_id, stderr_artifact_id, diff_artifact_id, created_at
`

type CreateJudgeCaseResultParams struct {
	AttemptID         int64       `db:"attempt_id" json:"attempt_id"`
	CaseIndex         int32       `db:"case_index" json:"case_index"`
	GroupName         pgtype.Text `db:"group_name" json:"group_name"`
	TestcaseKey       pgtype.Text `db:"testcase_key" json:"testcase_key"`
	Status            string      `db:"status" json:"status"`
	Score             int32       `db:"score" json:"score"`
	TimeMs            pgtype.Int4 `db:"time_ms" json:"time_ms"`
	MemoryKb          pgtype.Int4 `db:"memory_kb" json:"memory_kb"`
	ExitCode          pgtype.Int4 `db:"exit_code" json:"exit_code"`
	Signal            pgtype.Text `db:"signal" json:"signal"`
	CheckerMessage    pgtype.Text `db:"checker_message" json:"checker_message"`
	OutputDiffSummary pgtype.Text `db:"output_diff_summary" json:"output_diff_summary"`
	StdoutArtifactID  pgtype.Int8 `db:"stdout_artifact_id" json:"stdout_artifact_id"`
	StderrArtifactID  pgtype.Int8 `db:"stderr_artifact_id" json:"stderr_artifact_id"`
	DiffArtifactID    pgtype.Int8 `db:"diff_artifact_id" json:"diff_artifact_id"`
}

func (q *Queries) CreateJudgeCaseResult(ctx context.Context, arg CreateJudgeCaseResultParams) (JudgeCaseResult, error) {
	row := q.db.QueryRow(ctx, createJudgeCaseResult,
		arg.AttemptID,
		arg.CaseIndex,
		arg.GroupName,
		arg.TestcaseKey,
		arg.Status,
		arg.Score,
		arg.TimeMs,
		arg.MemoryKb,
		arg.ExitCode,
		arg.Signal,
		arg.CheckerMessage,
		arg.OutputDiffSummary,
		arg.StdoutArtifactID,
		arg.StderrArtifactID,
		arg.DiffArtifactID,
	)
	var i JudgeCaseResult
	err := row.Scan(
		&i.ID,
		&i.AttemptID,
		&i.CaseIndex,
		&i.GroupName,
		&i.TestcaseKey,
		&i.Status,
		&i.Score,
		&i.TimeMs,
		&i.MemoryKb,
		&i.ExitCode,
		&i.Signal,
		&i.CheckerMessage,
		&i.OutputDiffSummary,
		&i.StdoutArtifactID,
		&i.StderrArtifactID,
		&i.DiffArtifactID,
		&i.CreatedAt,
	)
	return i, err
}

const createJudgeTask = `-- name: CreateJudgeTask :one
INSERT INTO judge_tasks (
    submission_id,
    status,
    next_run_at
) VALUES (
    $1, $2, $3
)
RETURNING id, submission_id, stream_id, status, attempts, next_run_at, last_error, created_at, updated_at
`

type CreateJudgeTaskParams struct {
	SubmissionID int64              `db:"submission_id" json:"submission_id"`
	Status       string             `db:"status" json:"status"`
	NextRunAt    pgtype.Timestamptz `db:"next_run_at" json:"next_run_at"`
}

func (q *Queries) CreateJudgeTask(ctx context.Context, arg CreateJudgeTaskParams) (JudgeTask, error) {
	row := q.db.QueryRow(ctx, createJudgeTask, arg.SubmissionID, arg.Status, arg.NextRunAt)
	var i JudgeTask
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.StreamID,
		&i.Status,
		&i.Attempts,
		&i.NextRunAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRun = `-- name: CreateRun :one
INSERT INTO runs (
    user_id,
    problem_id,
    language_id,
    status,
    source_artifact_id,
    stdin
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, user_id, problem_id, language_id, status, source_artifact_id, stdin, stdout, stderr, compile_output, time_ms, memory_kb, error_message, created_at, finished_at, updated_at
`

type CreateRunParams struct {
	UserID           int64       `db:"user_id" json:"user_id"`
	ProblemID        int64       `db:"problem_id" json:"problem_id"`
	LanguageID       int64       `db:"language_id" json:"language_id"`
	Status           string      `db:"status" json:"status"`
	SourceArtifactID pgtype.Int8 `db:"source_artifact_id" json:"source_artifact_id"`
	Stdin            pgtype.Text `db:"stdin" json:"stdin"`
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (Run, error) {
	row := q.db.QueryRow(ctx, createRun,
		arg.UserID,
		arg.ProblemID,
		arg.LanguageID,
		arg.Status,
		arg.SourceArtifactID,
		arg.Stdin,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProblemID,
		&i.LanguageID,
		&i.Status,
		&i.SourceArtifactID,
		&i.Stdin,
		&i.Stdout,
		&i.Stderr,
		&i.CompileOutput,
		&i.TimeMs,
		&i.MemoryKb,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSubmission = `-- name: CreateSubmission :one
INSERT INTO submissions (
    user_id,
    problem_id,
    contest_id,
    language_id,
    testcase_set_id,
    status,
    source_artifact_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, user_id, problem_id, contest_id, language_id, testcase_set_id, status, source_artifact_id, time_ms, memory_kb, score, error_message, submitted_at, judged_at, updated_at
`

type CreateSubmissionParams struct {
	UserID           int64       `db:"user_id" json:"user_id"`
	ProblemID        int64       `db:"problem_id" json:"problem_id"`
	ContestID        pgtype.Int8 `db:"contest_id" json:"contest_id"`
	LanguageID       int64       `db:"language_id" json:"language_id"`
	TestcaseSetID    int64       `db:"testcase_set_id" json:"testcase_set_id"`
	Status           string      `db:"status" json:"status"`
	SourceArtifactID pgtype.Int8 `db:"source_artifact_id" json:"source_artifact_id"`
}

func (q *Queries) CreateSubmission(ctx context.Context, arg CreateSubmissionParams) (Submission, error) {
	row := q.db.QueryRow(ctx, createSubmission,
		arg.UserID,
		arg.ProblemID,
		arg.ContestID,
		arg.LanguageID,
		arg.TestcaseSetID,
		arg.Status,
		arg.SourceArtifactID,
	)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProblemID,
		&i.ContestID,
		&i.LanguageID,
		&i.TestcaseSetID,
		&i.Status,
		&i.SourceArtifactID,
		&i.TimeMs,
		&i.MemoryKb,
		&i.Score,
		&i.ErrorMessage,
		&i.SubmittedAt,
		&i.JudgedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getArtifactByID = `-- name: GetArtifactByID :one
SELECT id, owner_type, owner_id, kind, storage_key, checksum_sha256, size_bytes, content_type, created_at
FROM artifacts
WHERE id = $1
`

func (q *Queries) GetArtifactByID(ctx context.Context, id int64) (Artifact, error) {
	row := q.db.QueryRow(ctx, getArtifactByID, id)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.OwnerType,
		&i.OwnerID,
		&i.Kind,
		&i.StorageKey,
		&i.ChecksumSha256,
		&i.SizeBytes,
		&i.ContentType,
		&i.CreatedAt,
	)
	return i, err
}

const getJudgeAttemptByID = `-- name: GetJudgeAttemptByID :one
SELECT id, submission_id, run_id, task_id, attempt_no, protocol_version, judge_core_version, judge_engine, judge_agent_id, language_id, language_runtime, sandbox_backend, sandbox_profile, testcase_set_id, testcase_set_hash, checker_hash, validator_hash, status, verdict, score, time_ms, memory_kb, first_failed_case_index, first_failed_group, compile_output_summary, stderr_summary, checker_message, error_class, error_message, manifest, metrics, trace_id, started_at, finished_at, created_at, updated_at
FROM judge_attempts
WHERE id = $1
`

func (q *Queries) GetJudgeAttemptByID(ctx context.Context, id int64) (JudgeAttempt, error) {
	row := q.db.QueryRow(ctx, getJudgeAttemptByID, id)
	var i JudgeAttempt
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.RunID,
		&i.TaskID,
		&i.AttemptNo,
		&i.ProtocolVersion,
		&i.JudgeCoreVersion,
		&i.JudgeEngine,
		&i.JudgeAgentID,
		&i.LanguageID,
		&i.LanguageRuntime,
		&i.SandboxBackend,
		&i.SandboxProfile,
		&i.TestcaseSetID,
		&i.TestcaseSetHash,
		&i.CheckerHash,
		&i.ValidatorHash,
		&i.Status,
		&i.Verdict,
		&i.Score,
		&i.TimeMs,
		&i.MemoryKb,
		&i.FirstFailedCaseIndex,
		&i.FirstFailedGroup,
		&i.CompileOutputSummary,
		&i.StderrSummary,
		&i.CheckerMessage,
		&i.ErrorClass,
		&i.ErrorMessage,
		&i.Manifest,
		&i.Metrics,
		&i.TraceID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJudgeTaskByID = `-- name: GetJudgeTaskByID :one
SELECT id, submission_id, stream_id, status, attempts, next_run_at, last_error, created_at, updated_at
FROM judge_tasks
WHERE id = $1
`

func (q *Queries) GetJudgeTaskByID(ctx context.Context, id int64) (JudgeTask, error) {
	row := q.db.QueryRow(ctx, getJudgeTaskByID, id)
	var i JudgeTask
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.StreamID,
		&i.Status,
		&i.Attempts,
		&i.NextRunAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJudgeTaskBySubmissionID = `-- name: GetJudgeTaskBySubmissionID :one
SELECT id, submission_id, stream_id, status, attempts, next_run_at, last_error, created_at, updated_at
FROM judge_tasks
WHERE submission_id = $1
`

func (q *Queries) GetJudgeTaskBySubmissionID(ctx context.Context, submissionID int64) (JudgeTask, error) {
	row := q.db.QueryRow(ctx, getJudgeTaskBySubmissionID, submissionID)
	var i JudgeTask
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.StreamID,
		&i.Status,
		&i.Attempts,
		&i.NextRunAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestJudgeAttemptByRunID = `-- name: GetLatestJudgeAttemptByRunID :one
SELECT id, submission_id, run_id, task_id, attempt_no, protocol_version, judge_core_version, judge_engine, judge_agent_id, language_id, language_runtime, sandbox_backend, sandbox_profile, testcase_set_id, testcase_set_hash, checker_hash, validator_hash, status, verdict, score, time_ms, memory_kb, first_failed_case_index, first_failed_group, compile_output_summary, stderr_summary, checker_message, error_class, error_message, manifest, metrics, trace_id, started_at, finished_at, created_at, updated_at
FROM judge_attempts
WHERE run_id = $1
ORDER BY attempt_no DESC, id DESC
LIMIT 1
`

func (q *Queries) GetLatestJudgeAttemptByRunID(ctx context.Context, runID pgtype.Int8) (JudgeAttempt, error) {
	row := q.db.QueryRow(ctx, getLatestJudgeAttemptByRunID, runID)
	var i JudgeAttempt
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.RunID,
		&i.TaskID,
		&i.AttemptNo,
		&i.ProtocolVersion,
		&i.JudgeCoreVersion,
		&i.JudgeEngine,
		&i.JudgeAgentID,
		&i.LanguageID,
		&i.LanguageRuntime,
		&i.SandboxBackend,
		&i.SandboxProfile,
		&i.TestcaseSetID,
		&i.TestcaseSetHash,
		&i.CheckerHash,
		&i.ValidatorHash,
		&i.Status,
		&i.Verdict,
		&i.Score,
		&i.TimeMs,
		&i.MemoryKb,
		&i.FirstFailedCaseIndex,
		&i.FirstFailedGroup,
		&i.CompileOutputSummary,
		&i.StderrSummary,
		&i.CheckerMessage,
		&i.ErrorClass,
		&i.ErrorMessage,
		&i.Manifest,
		&i.Metrics,
		&i.TraceID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestJudgeAttemptBySubmissionID = `-- name: GetLatestJudgeAttemptBySubmissionID :one
SELECT id, submission_id, run_id, task_id, attempt_no, protocol_version, judge_core_version, judge_engine, judge_agent_id, language_id, language_runtime, sandbox_backend, sandbox_profile, testcase_set_id, testcase_set_hash, checker_hash, validator_hash, status, verdict, score, time_ms, memory_kb, first_failed_case_index, first_failed_group, compile_output_summary, stderr_summary, checker_message, error_class, error_message, manifest, metrics, trace_id, started_at, finished_at, created_at, updated_at
FROM judge_attempts
WHERE submission_id = $1
ORDER BY attempt_no DESC, id DESC
LIMIT 1
`

func (q *Queries) GetLatestJudgeAttemptBySubmissionID(ctx context.Context, submissionID pgtype.Int8) (JudgeAttempt, error) {
	row := q.db.QueryRow(ctx, getLatestJudgeAttemptBySubmissionID, submissionID)
	var i JudgeAttempt
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.RunID,
		&i.TaskID,
		&i.AttemptNo,
		&i.ProtocolVersion,
		&i.JudgeCoreVersion,
		&i.JudgeEngine,
		&i.JudgeAgentID,
		&i.LanguageID,
		&i.LanguageRuntime,
		&i.SandboxBackend,
		&i.SandboxProfile,
		&i.TestcaseSetID,
		&i.TestcaseSetHash,
		&i.CheckerHash,
		&i.ValidatorHash,
		&i.Status,
		&i.Verdict,
		&i.Score,
		&i.TimeMs,
		&i.MemoryKb,
		&i.FirstFailedCaseIndex,
		&i.FirstFailedGroup,
		&i.CompileOutputSummary,
		&i.StderrSummary,
		&i.CheckerMessage,
		&i.ErrorClass,
		&i.ErrorMessage,
		&i.Manifest,
		&i.Metrics,
		&i.TraceID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReadyTestcaseSetByID = `-- name: GetReadyTestcaseSetByID :one
SELECT id, problem_id, version, storage_key, checksum_sha256, size_bytes, case_count, status, is_current, created_by, created_at
FROM testcase_sets
WHERE id = $1
  AND problem_id = $2
  AND status = 'ready'
`

type GetReadyTestcaseSetByIDParams struct {
	ID        int64 `db:"id" json:"id"`
	ProblemID int64 `db:"problem_id" json:"problem_id"`
}

func (q *Queries) GetReadyTestcaseSetByID(ctx context.Context, arg GetReadyTestcaseSetByIDParams) (TestcaseSet, error) {
	row := q.db.QueryRow(ctx, getReadyTestcaseSetByID, arg.ID, arg.ProblemID)
	var i TestcaseSet
	err := row.Scan(
		&i.ID,
		&i.ProblemID,
		&i.Version,
		&i.StorageKey,
		&i.ChecksumSha256,
		&i.SizeBytes,
		&i.CaseCount,
		&i.Status,
		&i.IsCurrent,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getRunByID = `-- name: GetRunByID :one
SELECT id, user_id, problem_id, language_id, status, source_artifact_id, stdin, stdout, stderr, compile_output, time_ms, memory_kb, error_message, created_at, finished_at, updated_at
FROM runs
WHERE id = $1
`

func (q *Queries) GetRunByID(ctx context.Context, id int64) (Run, error) {
	row := q.db.QueryRow(ctx, getRunByID, id)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProblemID,
		&i.LanguageID,
		&i.Status,
		&i.SourceArtifactID,
		&i.Stdin,
		&i.Stdout,
		&i.Stderr,
		&i.CompileOutput,
		&i.TimeMs,
		&i.MemoryKb,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubmissionByID = `-- name: GetSubmissionByID :one
SELECT id, user_id, problem_id, contest_id, language_id, testcase_set_id, status, source_artifact_id, time_ms, memory_kb, score, error_message, submitted_at, judged_at, updated_at
FROM submissions
WHERE id = $1
`

func (q *Queries) GetSubmissionByID(ctx context.Context, id int64) (Submission, error) {
	row := q.db.QueryRow(ctx, getSubmissionByID, id)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProblemID,
		&i.ContestID,
		&i.LanguageID,
		&i.TestcaseSetID,
		&i.Status,
		&i.SourceArtifactID,
		&i.TimeMs,
		&i.MemoryKb,
		&i.Score,
		&i.ErrorMessage,
		&i.SubmittedAt,
		&i.JudgedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubmissionResultBySubmissionID = `-- name: GetSubmissionResultBySubmissionID :one
SELECT submission_id, attempt_id, status, score, time_ms, memory_kb, first_failed_case_index, first_failed_group, error_class, safe_summary, created_at, updated_at
FROM submission_results
WHERE submission_id = $1
`

func (q *Queries) GetSubmissionResultBySubmissionID(ctx context.Context, submissionID int64) (SubmissionResult, error) {
	row := q.db.QueryRow(ctx, getSubmissionResultBySubmissionID, submissionID)
	var i SubmissionResult
	err := row.Scan(
		&i.SubmissionID,
		&i.AttemptID,
		&i.Status,
		&i.Score,
		&i.TimeMs,
		&i.MemoryKb,
		&i.FirstFailedCaseIndex,
		&i.FirstFailedGroup,
		&i.ErrorClass,
		&i.SafeSummary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listJudgeAttemptsBySubmissionID = `-- name: ListJudgeAttemptsBySubmissionID :many
SELECT id, submission_id, run_id, task_id, attempt_no, protocol_version, judge_core_version, judge_engine, judge_agent_id, language_id, language_runtime, sandbox_backend, sandbox_profile, testcase_set_id, testcase_set_hash, checker_hash, validator_hash, status, verdict, score, time_ms, memory_kb, first_failed_case_index, first_failed_group, compile_output_summary, stderr_summary, checker_message, error_class, error_message, manifest, metrics, trace_id, started_at, finished_at, created_at, updated_at
FROM judge_attempts
WHERE submission_id = $1
ORDER BY attempt_no DESC, id DESC
`

func (q *Queries) ListJudgeAttemptsBySubmissionID(ctx context.Context, submissionID pgtype.Int8) ([]JudgeAttempt, error) {
	rows, err := q.db.Query(ctx, listJudgeAttemptsBySubmissionID, submissionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JudgeAttempt
	for rows.Next() {
		var i JudgeAttempt
		if err := rows.Scan(
			&i.ID,
			&i.SubmissionID,
			&i.RunID,
			&i.TaskID,
			&i.AttemptNo,
			&i.ProtocolVersion,
			&i.JudgeCoreVersion,
			&i.JudgeEngine,
			&i.JudgeAgentID,
			&i.LanguageID,
			&i.LanguageRuntime,
			&i.SandboxBackend,
			&i.SandboxProfile,
			&i.TestcaseSetID,
			&i.TestcaseSetHash,
			&i.CheckerHash,
			&i.ValidatorHash,
			&i.Status,
			&i.Verdict,
			&i.Score,
			&i.TimeMs,
			&i.MemoryKb,
			&i.FirstFailedCaseIndex,
			&i.FirstFailedGroup,
			&i.CompileOutputSummary,
			&i.StderrSummary,
			&i.CheckerMessage,
			&i.ErrorClass,
			&i.ErrorMessage,
			&i.Manifest,
			&i.Metrics,
			&i.TraceID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJudgeCaseResultsByAttemptID = `-- name: ListJudgeCaseResultsByAttemptID :many
SELECT id, attempt_id, case_index, group_name, testcase_key, status, score, time_ms, memory_kb, exit_code, signal, checker_message, output_diff_summary, stdout_artifact_id, stderr_artifact_id, diff_artifact_id, created_at
FROM judge_case_results
WHERE attempt_id = $1
ORDER BY case_index
`

func (q *Queries) ListJudgeCaseResultsByAttemptID(ctx context.Context, attemptID int64) ([]JudgeCaseResult, error) {
	rows, err := q.db.Query(ctx, listJudgeCaseResultsByAttemptID, attemptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JudgeCaseResult
	for rows.Next() {
		var i JudgeCaseResult
		if err := rows.Scan(
			&i.ID,
			&i.AttemptID,
			&i.CaseIndex,
			&i.GroupName,
			&i.TestcaseKey,
			&i.Status,
			&i.Score,
			&i.TimeMs,
			&i.MemoryKb,
			&i.ExitCode,
			&i.Signal,
			&i.CheckerMessage,
			&i.OutputDiffSummary,
			&i.StdoutArtifactID,
			&i.StderrArtifactID,
			&i.DiffArtifactID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubmissions = `-- name: ListSubmissions :many
SELECT id, user_id, problem_id, contest_id, language_id, testcase_set_id, status, source_artifact_id, time_ms, memory_kb, score, error_message, submitted_at, judged_at, updated_at
FROM submissions
WHERE ($1::bigint IS NULL OR user_id = $1::bigint)
  AND ($2::bigint IS NULL OR problem_id = $2::bigint)
  AND ($3::bigint IS NULL OR contest_id = $3::bigint)
  AND ($4::text IS NULL OR status = $4::text)
ORDER BY submitted_at DESC, id DESC
LIMIT $6 OFFSET $5
`

type ListSubmissionsParams struct {
	UserID    pgtype.Int8 `db:"user_id" json:"user_id"`
	ProblemID pgtype.Int8 `db:"problem_id" json:"problem_id"`
	ContestID pgtype.Int8 `db:"contest_id" json:"contest_id"`
	Status    pgtype.Text `db:"status" json:"status"`
	Offset    int32       `db:"offset" json:"offset"`
	Limit     int32       `db:"limit" json:"limit"`
}

func (q *Queries) ListSubmissions(ctx context.Context, arg ListSubmissionsParams) ([]Submission, error) {
	rows, err := q.db.Query(ctx, listSubmissions,
		arg.UserID,
		arg.ProblemID,
		arg.ContestID,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Submission
	for rows.Next() {
		var i Submission
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProblemID,
			&i.ContestID,
			&i.LanguageID,
			&i.TestcaseSetID,
			&i.Status,
			&i.SourceArtifactID,
			&i.TimeMs,
			&i.MemoryKb,
			&i.Score,
			&i.ErrorMessage,
			&i.SubmittedAt,
			&i.JudgedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markJudgeAttemptFinished = `-- name: MarkJudgeAttemptFinished :one
UPDATE judge_attempts
SET status = $1,
    verdict = $2,
    score = $3,
    time_ms = $4,
    memory_kb = $5,
    first_failed_case_index = $6,
    first_failed_group = $7,
    compile_output_summary = $8,
    stderr_summary = $9,
    checker_message = $10,
    error_class = $11,
    error_message = $12,
    manifest = $13,
    metrics = $14,
    trace_id = $15,
    finished_at = coalesce($16, finished_at, now()),
    updated_at = now()
WHERE id = $17
RETURNING id, submission_id, run_id, task_id, attempt_no, protocol_version, judge_core_version, judge_engine, judge_agent_id, language_id, language_runtime, sandbox_backend, sandbox_profile, testcase_set_id, testcase_set_hash, checker_hash, validator_hash, status, verdict, score, time_ms, memory_kb, first_failed_case_index, first_failed_group, compile_output_summary, stderr_summary, checker_message, error_class, error_message, manifest, metrics, trace_id, started_at, finished_at, created_at, updated_at
`

type MarkJudgeAttemptFinishedParams struct {
	Status               string             `db:"status" json:"status"`
	Verdict              pgtype.Text        `db:"verdict" json:"verdict"`
	Score                int32              `db:"score" json:"score"`
	TimeMs               pgtype.Int4        `db:"time_ms" json:"time_ms"`
	MemoryKb             pgtype.Int4        `db:"memory_kb" json:"memory_kb"`
	FirstFailedCaseIndex pgtype.Int4        `db:"first_failed_case_index" json:"first_failed_case_index"`
	FirstFailedGroup     pgtype.Text        `db:"first_failed_group" json:"first_failed_group"`
	CompileOutputSummary pgtype.Text        `db:"compile_output_summary" json:"compile_output_summary"`
	StderrSummary        pgtype.Text        `db:"stderr_summary" json:"stderr_summary"`
	CheckerMessage       pgtype.Text        `db:"checker_message" json:"checker_message"`
	ErrorClass           pgtype.Text        `db:"error_class" json:"error_class"`
	ErrorMessage         pgtype.Text        `db:"error_message" json:"error_message"`
	Manifest             []byte             `db:"manifest" json:"manifest"`
	Metrics              []byte             `db:"metrics" json:"metrics"`
	TraceID              pgtype.Text        `db:"trace_id" json:"trace_id"`
	FinishedAt           pgtype.Timestamptz `db:"finished_at" json:"finished_at"`
	ID                   int64              `db:"id" json:"id"`
}

func (q *Queries) MarkJudgeAttemptFinished(ctx context.Context, arg MarkJudgeAttemptFinishedParams) (JudgeAttempt, error) {
	row := q.db.QueryRow(ctx, markJudgeAttemptFinished,
		arg.Status,
		arg.Verdict,
		arg.Score,
		arg.TimeMs,
		arg.MemoryKb,
		arg.FirstFailedCaseIndex,
		arg.FirstFailedGroup,
		arg.CompileOutputSummary,
		arg.StderrSummary,
		arg.CheckerMessage,
		arg.ErrorClass,
		arg.ErrorMessage,
		arg.Manifest,
		arg.Metrics,
		arg.TraceID,
		arg.FinishedAt,
		arg.ID,
	)
	var i JudgeAttempt
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.RunID,
		&i.TaskID,
		&i.AttemptNo,
		&i.ProtocolVersion,
		&i.JudgeCoreVersion,
		&i.JudgeEngine,
		&i.JudgeAgentID,
		&i.LanguageID,
		&i.LanguageRuntime,
		&i.SandboxBackend,
		&i.SandboxProfile,
		&i.TestcaseSetID,
		&i.TestcaseSetHash,
		&i.CheckerHash,
		&i.ValidatorHash,
		&i.Status,
		&i.Verdict,
		&i.Score,
		&i.TimeMs,
		&i.MemoryKb,
		&i.FirstFailedCaseIndex,
		&i.FirstFailedGroup,
		&i.CompileOutputSummary,
		&i.StderrSummary,
		&i.CheckerMessage,
		&i.ErrorClass,
		&i.ErrorMessage,
		&i.Manifest,
		&i.Metrics,
		&i.TraceID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markJudgeTaskDead = `-- name: MarkJudgeTaskDead :one
UPDATE judge_tasks
SET status = 'dead',
    last_error = $2,
    updated_at = now()
WHERE id = $1
  AND status IN ('dispatching', 'dispatched', 'running')
RETURNING id, submission_id, stream_id, status, attempts, next_run_at, last_error, created_at, updated_at
`

type MarkJudgeTaskDeadParams struct {
	ID        int64       `db:"id" json:"id"`
	LastError pgtype.Text `db:"last_error" json:"last_error"`
}

func (q *Queries) MarkJudgeTaskDead(ctx context.Context, arg MarkJudgeTaskDeadParams) (JudgeTask, error) {
	row := q.db.QueryRow(ctx, markJudgeTaskDead, arg.ID, arg.LastError)
	var i JudgeTask
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.StreamID,
		&i.Status,
		&i.Attempts,
		&i.NextRunAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markJudgeTaskDispatched = `-- name: MarkJudgeTaskDispatched :one
UPDATE judge_tasks
SET status = CASE
        WHEN status = 'dispatching' THEN 'dispatched'
        ELSE status
    END,
    stream_id = $2,
    updated_at = now()
WHERE id = $1
  AND status IN ('dispatching', 'running')
RETURNING id, submission_id, stream_id, status, attempts, next_run_at, last_error, created_at, updated_at
`

type MarkJudgeTaskDispatchedParams struct {
	ID       int64       `db:"id" json:"id"`
	StreamID pgtype.Text `db:"stream_id" json:"stream_id"`
}

func (q *Queries) MarkJudgeTaskDispatched(ctx context.Context, arg MarkJudgeTaskDispatchedParams) (JudgeTask, error) {
	row := q.db.QueryRow(ctx, markJudgeTaskDispatched, arg.ID, arg.StreamID)
	var i JudgeTask
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.StreamID,
		&i.Status,
		&i.Attempts,
		&i.NextRunAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markJudgeTaskDone = `-- name: MarkJudgeTaskDone :one
UPDATE judge_tasks
SET status = 'done',
    updated_at = now()
WHERE id = $1
  AND status IN ('dispatched', 'running')
RETURNING id, submission_id, stream_id, status, attempts, next_run_at, last_error, created_at, updated_at
`

func (q *Queries) MarkJudgeTaskDone(ctx context.Context, id int64) (JudgeTask, error) {
	row := q.db.QueryRow(ctx, markJudgeTaskDone, id)
	var i JudgeTask
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.StreamID,
		&i.Status,
		&i.Attempts,
		&i.NextRunAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markJudgeTaskRunning = `-- name: MarkJudgeTaskRunning :one
UPDATE judge_tasks
SET status = 'running',
    updated_at = now()
WHERE id = $1
  AND status IN ('dispatching', 'dispatched', 'running')
RETURNING id, submission_id, stream_id, status, attempts, next_run_at, last_error, created_at, updated_at
`

func (q *Queries) MarkJudgeTaskRunning(ctx context.Context, id int64) (JudgeTask, error) {
	row := q.db.QueryRow(ctx, markJudgeTaskRunning, id)
	var i JudgeTask
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.StreamID,
		&i.Status,
		&i.Attempts,
		&i.NextRunAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markStaleRunsSystemError = `-- name: MarkStaleRunsSystemError :many
UPDATE runs
SET status = 'system_error',
    error_message = $1,
    finished_at = CASE WHEN finished_at IS NULL THEN now() ELSE finished_at END,
    updated_at = now()
WHERE status IN ('queued', 'running')
  AND updated_at < $2
RETURNING id, user_id, problem_id, language_id, status, source_artifact_id, stdin, stdout, stderr, compile_output, time_ms, memory_kb, error_message, created_at, finished_at, updated_at
`

type MarkStaleRunsSystemErrorParams struct {
	ErrorMessage pgtype.Text        `db:"error_message" json:"error_message"`
	StaleBefore  pgtype.Timestamptz `db:"stale_before" json:"stale_before"`
}

func (q *Queries) MarkStaleRunsSystemError(ctx context.Context, arg MarkStaleRunsSystemErrorParams) ([]Run, error) {
	rows, err := q.db.Query(ctx, markStaleRunsSystemError, arg.ErrorMessage, arg.StaleBefore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Run
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProblemID,
			&i.LanguageID,
			&i.Status,
			&i.SourceArtifactID,
			&i.Stdin,
			&i.Stdout,
			&i.Stderr,
			&i.CompileOutput,
			&i.TimeMs,
			&i.MemoryKb,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.FinishedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSubmissionQueued = `-- name: MarkSubmissionQueued :one
UPDATE submissions
SET status = 'queued',
    error_message = $1,
    updated_at = now()
WHERE id = $2
  AND status NOT IN ('accepted', 'wrong_answer', 'compile_error', 'runtime_error', 'time_limit', 'memory_limit', 'system_error', 'canceled')
RETURNING id, user_id, problem_id, contest_id, language_id, testcase_set_id, status, source_artifact_id, time_ms, memory_kb, score, error_message, submitted_at, judged_at, updated_at
`

type MarkSubmissionQueuedParams struct {
	ErrorMessage pgtype.Text `db:"error_message" json:"error_message"`
	ID           int64       `db:"id" json:"id"`
}

func (q *Queries) MarkSubmissionQueued(ctx context.Context, arg MarkSubmissionQueuedParams) (Submission, error) {
	row := q.db.QueryRow(ctx, markSubmissionQueued, arg.ErrorMessage, arg.ID)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProblemID,
		&i.ContestID,
		&i.LanguageID,
		&i.TestcaseSetID,
		&i.Status,
		&i.SourceArtifactID,
		&i.TimeMs,
		&i.MemoryKb,
		&i.Score,
		&i.ErrorMessage,
		&i.SubmittedAt,
		&i.JudgedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markSubmissionRunning = `-- name: MarkSubmissionRunning :one
UPDATE submissions
SET status = 'running',
    updated_at = now()
WHERE id = $1
  AND status = 'queued'
RETURNING id, user_id, problem_id, contest_id, language_id, testcase_set_id, status, source_artifact_id, time_ms, memory_kb, score, error_message, submitted_at, judged_at, updated_at
`

func (q *Queries) MarkSubmissionRunning(ctx context.Context, id int64) (Submission, error) {
	row := q.db.QueryRow(ctx, markSubmissionRunning, id)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProblemID,
		&i.ContestID,
		&i.LanguageID,
		&i.TestcaseSetID,
		&i.Status,
		&i.SourceArtifactID,
		&i.TimeMs,
		&i.MemoryKb,
		&i.Score,
		&i.ErrorMessage,
		&i.SubmittedAt,
		&i.JudgedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markSubmissionSystemError = `-- name: MarkSubmissionSystemError :one
UPDATE submissions
SET status = 'system_error',
    error_message = $1,
    judged_at = CASE WHEN judged_at IS NULL THEN now() ELSE judged_at END,
    updated_at = now()
WHERE id = $2
  AND status NOT IN ('accepted', 'wrong_answer', 'compile_error', 'runtime_error', 'time_limit', 'memory_limit', 'system_error', 'canceled')
RETURNING id, user_id, problem_id, contest_id, language_id, testcase_set_id, status, source_artifact_id, time_ms, memory_kb, score, error_message, submitted_at, judged_at, updated_at
`

type MarkSubmissionSystemErrorParams struct {
	ErrorMessage pgtype.Text `db:"error_message" json:"error_message"`
	ID           int64       `db:"id" json:"id"`
}

func (q *Queries) MarkSubmissionSystemError(ctx context.Context, arg MarkSubmissionSystemErrorParams) (Submission, error) {
	row := q.db.QueryRow(ctx, markSubmissionSystemError, arg.ErrorMessage, arg.ID)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProblemID,
		&i.ContestID,
		&i.LanguageID,
		&i.TestcaseSetID,
		&i.Status,
		&i.SourceArtifactID,
		&i.TimeMs,
		&i.MemoryKb,
		&i.Score,
		&i.ErrorMessage,
		&i.SubmittedAt,
		&i.JudgedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resetStaleJudgeTasks = `-- name: ResetStaleJudgeTasks :many
WITH reset_tasks AS (
    UPDATE judge_tasks
    SET status = 'pending',
        next_run_at = now(),
        last_error = $1,
        updated_at = now()
    WHERE judge_tasks.status IN ('dispatching', 'running')
      AND judge_tasks.updated_at < $2
      AND EXISTS (
          SELECT 1
          FROM submissions
          WHERE submissions.id = judge_tasks.submission_id
            AND submissions.status NOT IN ('accepted', 'wrong_answer', 'compile_error', 'runtime_error', 'time_limit', 'memory_limit', 'system_error', 'canceled')
      )
    RETURNING id, submission_id, stream_id, status, attempts, next_run_at, last_error, created_at, updated_at
), reset_submissions AS (
    UPDATE submissions
    SET status = 'queued',
        error_message = $1,
        updated_at = now()
    FROM reset_tasks
    WHERE submissions.id = reset_tasks.submission_id
      AND submissions.status = 'running'
    RETURNING submissions.id
)
SELECT id, submission_id, stream_id, status, attempts, next_run_at, last_error, created_at, updated_at
FROM reset_tasks
ORDER BY id
`

type ResetStaleJudgeTasksParams struct {
	LastError   pgtype.Text        `db:"last_error" json:"last_error"`
	StaleBefore pgtype.Timestamptz `db:"stale_before" json:"stale_before"`
}

type ResetStaleJudgeTasksRow struct {
	ID           int64              `db:"id" json:"id"`
	SubmissionID int64              `db:"submission_id" json:"submission_id"`
	StreamID     pgtype.Text        `db:"stream_id" json:"stream_id"`
	Status       string             `db:"status" json:"status"`
	Attempts     int32              `db:"attempts" json:"attempts"`
	NextRunAt    pgtype.Timestamptz `db:"next_run_at" json:"next_run_at"`
	LastError    pgtype.Text        `db:"last_error" json:"last_error"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ResetStaleJudgeTasks(ctx context.Context, arg ResetStaleJudgeTasksParams) ([]ResetStaleJudgeTasksRow, error) {
	rows, err := q.db.Query(ctx, resetStaleJudgeTasks, arg.LastError, arg.StaleBefore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResetStaleJudgeTasksRow
	for rows.Next() {
		var i ResetStaleJudgeTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.SubmissionID,
			&i.StreamID,
			&i.Status,
			&i.Attempts,
			&i.NextRunAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retryJudgeTask = `-- name: RetryJudgeTask :one
UPDATE judge_tasks
SET status = 'pending',
    attempts = attempts + 1,
    next_run_at = $1,
    last_error = $2,
    updated_at = now()
WHERE id = $3
  AND status IN ('dispatching', 'dispatched', 'running')
RETURNING id, submission_id, stream_id, status, attempts, next_run_at, last_error, created_at, updated_at
`

type RetryJudgeTaskParams struct {
	NextRunAt pgtype.Timestamptz `db:"next_run_at" json:"next_run_at"`
	LastError pgtype.Text        `db:"last_error" json:"last_error"`
	ID        int64              `db:"id" json:"id"`
}

func (q *Queries) RetryJudgeTask(ctx context.Context, arg RetryJudgeTaskParams) (JudgeTask, error) {
	row := q.db.QueryRow(ctx, retryJudgeTask, arg.NextRunAt, arg.LastError, arg.ID)
	var i JudgeTask
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.StreamID,
		&i.Status,
		&i.Attempts,
		&i.NextRunAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateJudgeTaskDispatching = `-- name: UpdateJudgeTaskDispatching :one
UPDATE judge_tasks
SET status = 'dispatching',
    updated_at = now()
WHERE id = $1
  AND status = 'pending'
RETURNING id, submission_id, stream_id, status, attempts, next_run_at, last_error, created_at, updated_at
`

func (q *Queries) UpdateJudgeTaskDispatching(ctx context.Context, id int64) (JudgeTask, error) {
	row := q.db.QueryRow(ctx, updateJudgeTaskDispatching, id)
	var i JudgeTask
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.StreamID,
		&i.Status,
		&i.Attempts,
		&i.NextRunAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRunStatus = `-- name: UpdateRunStatus :one
UPDATE runs
SET status = $1,
    stdout = $2,
    stderr = $3,
    compile_output = $4,
    time_ms = $5,
    memory_kb = $6,
    error_message = $7,
    finished_at = CASE
        WHEN finished_at IS NULL
          AND $1::text IN ('accepted', 'wrong_answer', 'compile_error', 'runtime_error', 'time_limit', 'memory_limit', 'system_error', 'canceled') THEN now()
        ELSE finished_at
    END,
    updated_at = now()
WHERE id = $8
  AND status NOT IN ('accepted', 'wrong_answer', 'compile_error', 'runtime_error', 'time_limit', 'memory_limit', 'system_error', 'canceled')
RETURNING id, user_id, problem_id, language_id, status, source_artifact_id, stdin, stdout, stderr, compile_output, time_ms, memory_kb, error_message, created_at, finished_at, updated_at
`

type UpdateRunStatusParams struct {
	Status        string      `db:"status" json:"status"`
	Stdout        pgtype.Text `db:"stdout" json:"stdout"`
	Stderr        pgtype.Text `db:"stderr" json:"stderr"`
	CompileOutput pgtype.Text `db:"compile_output" json:"compile_output"`
	TimeMs        pgtype.Int4 `db:"time_ms" json:"time_ms"`
	MemoryKb      pgtype.Int4 `db:"memory_kb" json:"memory_kb"`
	ErrorMessage  pgtype.Text `db:"error_message" json:"error_message"`
	ID            int64       `db:"id" json:"id"`
}

func (q *Queries) UpdateRunStatus(ctx context.Context, arg UpdateRunStatusParams) (Run, error) {
	row := q.db.QueryRow(ctx, updateRunStatus,
		arg.Status,
		arg.Stdout,
		arg.Stderr,
		arg.CompileOutput,
		arg.TimeMs,
		arg.MemoryKb,
		arg.ErrorMessage,
		arg.ID,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProblemID,
		&i.LanguageID,
		&i.Status,
		&i.SourceArtifactID,
		&i.Stdin,
		&i.Stdout,
		&i.Stderr,
		&i.CompileOutput,
		&i.TimeMs,
		&i.MemoryKb,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSubmissionStatus = `-- name: UpdateSubmissionStatus :one
UPDATE submissions
SET status = $1,
    time_ms = $2,
    memory_kb = $3,
    score = coalesce($4, score),
    error_message = $5,
    judged_at = CASE
        WHEN judged_at IS NULL
          AND $1::text IN ('accepted', 'wrong_answer', 'compile_error', 'runtime_error', 'time_limit', 'memory_limit', 'system_error', 'canceled') THEN now()
        ELSE judged_at
    END,
    updated_at = now()
WHERE id = $6
  AND status NOT IN ('accepted', 'wrong_answer', 'compile_error', 'runtime_error', 'time_limit', 'memory_limit', 'system_error', 'canceled')
RETURNING id, user_id, problem_id, contest_id, language_id, testcase_set_id, status, source_artifact_id, time_ms, memory_kb, score, error_message, submitted_at, judged_at, updated_at
`

type UpdateSubmissionStatusParams struct {
	Status       string      `db:"status" json:"status"`
	TimeMs       pgtype.Int4 `db:"time_ms" json:"time_ms"`
	MemoryKb     pgtype.Int4 `db:"memory_kb" json:"memory_kb"`
	Score        pgtype.Int4 `db:"score" json:"score"`
	ErrorMessage pgtype.Text `db:"error_message" json:"error_message"`
	ID           int64       `db:"id" json:"id"`
}

func (q *Queries) UpdateSubmissionStatus(ctx context.Context, arg UpdateSubmissionStatusParams) (Submission, error) {
	row := q.db.QueryRow(ctx, updateSubmissionStatus,
		arg.Status,
		arg.TimeMs,
		arg.MemoryKb,
		arg.Score,
		arg.ErrorMessage,
		arg.ID,
	)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProblemID,
		&i.ContestID,
		&i.LanguageID,
		&i.TestcaseSetID,
		&i.Status,
		&i.SourceArtifactID,
		&i.TimeMs,
		&i.MemoryKb,
		&i.Score,
		&i.ErrorMessage,
		&i.SubmittedAt,
		&i.JudgedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSubmissionResult = `-- name: UpsertSubmissionResult :one
INSERT INTO submission_results (
    submission_id,
    attempt_id,
    status,
    score,
    time_ms,
    memory_kb,
    first_failed_case_index,
    first_failed_group,
    error_class,
    safe_summary
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
ON CONFLICT (submission_id) DO UPDATE
SET attempt_id = EXCLUDED.attempt_id,
    status = EXCLUDED.status,
    score = EXCLUDED.score,
    time_ms = EXCLUDED.time_ms,
    memory_kb = EXCLUDED.memory_kb,
    first_failed_case_index = EXCLUDED.first_failed_case_index,
    first_failed_group = EXCLUDED.first_failed_group,
    error_class = EXCLUDED.error_class,
    safe_summary = EXCLUDED.safe_summary,
    updated_at = now()
RETURNING submission_id, attempt_id, status, score, time_ms, memory_kb, first_failed_case_index, first_failed_group, error_class, safe_summary, created_at, updated_at
`

type UpsertSubmissionResultParams struct {
	SubmissionID         int64       `db:"submission_id" json:"submission_id"`
	AttemptID            int64       `db:"attempt_id" json:"attempt_id"`
	Status               string      `db:"status" json:"status"`
	Score                int32       `db:"score" json:"score"`
	TimeMs               pgtype.Int4 `db:"time_ms" json:"time_ms"`
	MemoryKb             pgtype.Int4 `db:"memory_kb" json:"memory_kb"`
	FirstFailedCaseIndex pgtype.Int4 `db:"first_failed_case_index" json:"first_failed_case_index"`
	FirstFailedGroup     pgtype.Text `db:"first_failed_group" json:"first_failed_group"`
	ErrorClass           pgtype.Text `db:"error_class" json:"error_class"`
	SafeSummary          []byte      `db:"safe_summary" json:"safe_summary"`
}

func (q *Queries) UpsertSubmissionResult(ctx context.Context, arg UpsertSubmissionResultParams) (SubmissionResult, error) {
	row := q.db.QueryRow(ctx, upsertSubmissionResult,
		arg.SubmissionID,
		arg.AttemptID,
		arg.Status,
		arg.Score,
		arg.TimeMs,
		arg.MemoryKb,
		arg.FirstFailedCaseIndex,
		arg.FirstFailedGroup,
		arg.ErrorClass,
		arg.SafeSummary,
	)
	var i SubmissionResult
	err := row.Scan(
		&i.SubmissionID,
		&i.AttemptID,
		&i.Status,
		&i.Score,
		&i.TimeMs,
		&i.MemoryKb,
		&i.FirstFailedCaseIndex,
		&i.FirstFailedGroup,
		&i.ErrorClass,
		&i.SafeSummary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
