// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: submissions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimPendingJudgeTasks = `-- name: ClaimPendingJudgeTasks :many
SELECT id, submission_id, stream_id, status, attempts, next_run_at, last_error, created_at, updated_at
FROM judge_tasks
WHERE status = 'pending'
  AND next_run_at <= now()
ORDER BY next_run_at, id
LIMIT $1
FOR UPDATE SKIP LOCKED
`

func (q *Queries) ClaimPendingJudgeTasks(ctx context.Context, limit int32) ([]JudgeTask, error) {
	rows, err := q.db.Query(ctx, claimPendingJudgeTasks, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JudgeTask
	for rows.Next() {
		var i JudgeTask
		if err := rows.Scan(
			&i.ID,
			&i.SubmissionID,
			&i.StreamID,
			&i.Status,
			&i.Attempts,
			&i.NextRunAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countSubmissions = `-- name: CountSubmissions :one
SELECT count(*)::bigint
FROM submissions
WHERE ($1::bigint IS NULL OR user_id = $1::bigint)
  AND ($2::bigint IS NULL OR problem_id = $2::bigint)
  AND ($3::bigint IS NULL OR contest_id = $3::bigint)
  AND ($4::text IS NULL OR status = $4::text)
`

type CountSubmissionsParams struct {
	UserID    pgtype.Int8 `db:"user_id" json:"user_id"`
	ProblemID pgtype.Int8 `db:"problem_id" json:"problem_id"`
	ContestID pgtype.Int8 `db:"contest_id" json:"contest_id"`
	Status    pgtype.Text `db:"status" json:"status"`
}

func (q *Queries) CountSubmissions(ctx context.Context, arg CountSubmissionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSubmissions,
		arg.UserID,
		arg.ProblemID,
		arg.ContestID,
		arg.Status,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createArtifact = `-- name: CreateArtifact :one

INSERT INTO artifacts (
    owner_type,
    owner_id,
    kind,
    storage_key,
    checksum_sha256,
    size_bytes,
    content_type
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, owner_type, owner_id, kind, storage_key, checksum_sha256, size_bytes, content_type, created_at
`

type CreateArtifactParams struct {
	OwnerType      string `db:"owner_type" json:"owner_type"`
	OwnerID        int64  `db:"owner_id" json:"owner_id"`
	Kind           string `db:"kind" json:"kind"`
	StorageKey     string `db:"storage_key" json:"storage_key"`
	ChecksumSha256 string `db:"checksum_sha256" json:"checksum_sha256"`
	SizeBytes      int64  `db:"size_bytes" json:"size_bytes"`
	ContentType    string `db:"content_type" json:"content_type"`
}

// Owner: WP4 Submission/Run
func (q *Queries) CreateArtifact(ctx context.Context, arg CreateArtifactParams) (Artifact, error) {
	row := q.db.QueryRow(ctx, createArtifact,
		arg.OwnerType,
		arg.OwnerID,
		arg.Kind,
		arg.StorageKey,
		arg.ChecksumSha256,
		arg.SizeBytes,
		arg.ContentType,
	)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.OwnerType,
		&i.OwnerID,
		&i.Kind,
		&i.StorageKey,
		&i.ChecksumSha256,
		&i.SizeBytes,
		&i.ContentType,
		&i.CreatedAt,
	)
	return i, err
}

const createJudgeTask = `-- name: CreateJudgeTask :one
INSERT INTO judge_tasks (
    submission_id,
    status,
    next_run_at
) VALUES (
    $1, $2, $3
)
RETURNING id, submission_id, stream_id, status, attempts, next_run_at, last_error, created_at, updated_at
`

type CreateJudgeTaskParams struct {
	SubmissionID int64              `db:"submission_id" json:"submission_id"`
	Status       string             `db:"status" json:"status"`
	NextRunAt    pgtype.Timestamptz `db:"next_run_at" json:"next_run_at"`
}

func (q *Queries) CreateJudgeTask(ctx context.Context, arg CreateJudgeTaskParams) (JudgeTask, error) {
	row := q.db.QueryRow(ctx, createJudgeTask, arg.SubmissionID, arg.Status, arg.NextRunAt)
	var i JudgeTask
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.StreamID,
		&i.Status,
		&i.Attempts,
		&i.NextRunAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRun = `-- name: CreateRun :one
INSERT INTO runs (
    user_id,
    problem_id,
    language_id,
    status,
    source_artifact_id,
    stdin
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, user_id, problem_id, language_id, status, source_artifact_id, stdin, stdout, stderr, compile_output, time_ms, memory_kb, error_message, created_at, finished_at, updated_at
`

type CreateRunParams struct {
	UserID           int64       `db:"user_id" json:"user_id"`
	ProblemID        int64       `db:"problem_id" json:"problem_id"`
	LanguageID       int64       `db:"language_id" json:"language_id"`
	Status           string      `db:"status" json:"status"`
	SourceArtifactID pgtype.Int8 `db:"source_artifact_id" json:"source_artifact_id"`
	Stdin            pgtype.Text `db:"stdin" json:"stdin"`
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (Run, error) {
	row := q.db.QueryRow(ctx, createRun,
		arg.UserID,
		arg.ProblemID,
		arg.LanguageID,
		arg.Status,
		arg.SourceArtifactID,
		arg.Stdin,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProblemID,
		&i.LanguageID,
		&i.Status,
		&i.SourceArtifactID,
		&i.Stdin,
		&i.Stdout,
		&i.Stderr,
		&i.CompileOutput,
		&i.TimeMs,
		&i.MemoryKb,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSubmission = `-- name: CreateSubmission :one
INSERT INTO submissions (
    user_id,
    problem_id,
    contest_id,
    language_id,
    testcase_set_id,
    status,
    source_artifact_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, user_id, problem_id, contest_id, language_id, testcase_set_id, status, source_artifact_id, time_ms, memory_kb, score, error_message, submitted_at, judged_at, updated_at
`

type CreateSubmissionParams struct {
	UserID           int64       `db:"user_id" json:"user_id"`
	ProblemID        int64       `db:"problem_id" json:"problem_id"`
	ContestID        pgtype.Int8 `db:"contest_id" json:"contest_id"`
	LanguageID       int64       `db:"language_id" json:"language_id"`
	TestcaseSetID    int64       `db:"testcase_set_id" json:"testcase_set_id"`
	Status           string      `db:"status" json:"status"`
	SourceArtifactID pgtype.Int8 `db:"source_artifact_id" json:"source_artifact_id"`
}

func (q *Queries) CreateSubmission(ctx context.Context, arg CreateSubmissionParams) (Submission, error) {
	row := q.db.QueryRow(ctx, createSubmission,
		arg.UserID,
		arg.ProblemID,
		arg.ContestID,
		arg.LanguageID,
		arg.TestcaseSetID,
		arg.Status,
		arg.SourceArtifactID,
	)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProblemID,
		&i.ContestID,
		&i.LanguageID,
		&i.TestcaseSetID,
		&i.Status,
		&i.SourceArtifactID,
		&i.TimeMs,
		&i.MemoryKb,
		&i.Score,
		&i.ErrorMessage,
		&i.SubmittedAt,
		&i.JudgedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getArtifactByID = `-- name: GetArtifactByID :one
SELECT id, owner_type, owner_id, kind, storage_key, checksum_sha256, size_bytes, content_type, created_at
FROM artifacts
WHERE id = $1
`

func (q *Queries) GetArtifactByID(ctx context.Context, id int64) (Artifact, error) {
	row := q.db.QueryRow(ctx, getArtifactByID, id)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.OwnerType,
		&i.OwnerID,
		&i.Kind,
		&i.StorageKey,
		&i.ChecksumSha256,
		&i.SizeBytes,
		&i.ContentType,
		&i.CreatedAt,
	)
	return i, err
}

const getJudgeTaskByID = `-- name: GetJudgeTaskByID :one
SELECT id, submission_id, stream_id, status, attempts, next_run_at, last_error, created_at, updated_at
FROM judge_tasks
WHERE id = $1
`

func (q *Queries) GetJudgeTaskByID(ctx context.Context, id int64) (JudgeTask, error) {
	row := q.db.QueryRow(ctx, getJudgeTaskByID, id)
	var i JudgeTask
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.StreamID,
		&i.Status,
		&i.Attempts,
		&i.NextRunAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJudgeTaskBySubmissionID = `-- name: GetJudgeTaskBySubmissionID :one
SELECT id, submission_id, stream_id, status, attempts, next_run_at, last_error, created_at, updated_at
FROM judge_tasks
WHERE submission_id = $1
`

func (q *Queries) GetJudgeTaskBySubmissionID(ctx context.Context, submissionID int64) (JudgeTask, error) {
	row := q.db.QueryRow(ctx, getJudgeTaskBySubmissionID, submissionID)
	var i JudgeTask
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.StreamID,
		&i.Status,
		&i.Attempts,
		&i.NextRunAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRunByID = `-- name: GetRunByID :one
SELECT id, user_id, problem_id, language_id, status, source_artifact_id, stdin, stdout, stderr, compile_output, time_ms, memory_kb, error_message, created_at, finished_at, updated_at
FROM runs
WHERE id = $1
`

func (q *Queries) GetRunByID(ctx context.Context, id int64) (Run, error) {
	row := q.db.QueryRow(ctx, getRunByID, id)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProblemID,
		&i.LanguageID,
		&i.Status,
		&i.SourceArtifactID,
		&i.Stdin,
		&i.Stdout,
		&i.Stderr,
		&i.CompileOutput,
		&i.TimeMs,
		&i.MemoryKb,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubmissionByID = `-- name: GetSubmissionByID :one
SELECT id, user_id, problem_id, contest_id, language_id, testcase_set_id, status, source_artifact_id, time_ms, memory_kb, score, error_message, submitted_at, judged_at, updated_at
FROM submissions
WHERE id = $1
`

func (q *Queries) GetSubmissionByID(ctx context.Context, id int64) (Submission, error) {
	row := q.db.QueryRow(ctx, getSubmissionByID, id)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProblemID,
		&i.ContestID,
		&i.LanguageID,
		&i.TestcaseSetID,
		&i.Status,
		&i.SourceArtifactID,
		&i.TimeMs,
		&i.MemoryKb,
		&i.Score,
		&i.ErrorMessage,
		&i.SubmittedAt,
		&i.JudgedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSubmissions = `-- name: ListSubmissions :many
SELECT id, user_id, problem_id, contest_id, language_id, testcase_set_id, status, source_artifact_id, time_ms, memory_kb, score, error_message, submitted_at, judged_at, updated_at
FROM submissions
WHERE ($1::bigint IS NULL OR user_id = $1::bigint)
  AND ($2::bigint IS NULL OR problem_id = $2::bigint)
  AND ($3::bigint IS NULL OR contest_id = $3::bigint)
  AND ($4::text IS NULL OR status = $4::text)
ORDER BY submitted_at DESC, id DESC
LIMIT $6 OFFSET $5
`

type ListSubmissionsParams struct {
	UserID    pgtype.Int8 `db:"user_id" json:"user_id"`
	ProblemID pgtype.Int8 `db:"problem_id" json:"problem_id"`
	ContestID pgtype.Int8 `db:"contest_id" json:"contest_id"`
	Status    pgtype.Text `db:"status" json:"status"`
	Offset    int32       `db:"offset" json:"offset"`
	Limit     int32       `db:"limit" json:"limit"`
}

func (q *Queries) ListSubmissions(ctx context.Context, arg ListSubmissionsParams) ([]Submission, error) {
	rows, err := q.db.Query(ctx, listSubmissions,
		arg.UserID,
		arg.ProblemID,
		arg.ContestID,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Submission
	for rows.Next() {
		var i Submission
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProblemID,
			&i.ContestID,
			&i.LanguageID,
			&i.TestcaseSetID,
			&i.Status,
			&i.SourceArtifactID,
			&i.TimeMs,
			&i.MemoryKb,
			&i.Score,
			&i.ErrorMessage,
			&i.SubmittedAt,
			&i.JudgedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markJudgeTaskDispatched = `-- name: MarkJudgeTaskDispatched :one
UPDATE judge_tasks
SET status = 'dispatched',
    stream_id = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, submission_id, stream_id, status, attempts, next_run_at, last_error, created_at, updated_at
`

type MarkJudgeTaskDispatchedParams struct {
	ID       int64       `db:"id" json:"id"`
	StreamID pgtype.Text `db:"stream_id" json:"stream_id"`
}

func (q *Queries) MarkJudgeTaskDispatched(ctx context.Context, arg MarkJudgeTaskDispatchedParams) (JudgeTask, error) {
	row := q.db.QueryRow(ctx, markJudgeTaskDispatched, arg.ID, arg.StreamID)
	var i JudgeTask
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.StreamID,
		&i.Status,
		&i.Attempts,
		&i.NextRunAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markJudgeTaskDone = `-- name: MarkJudgeTaskDone :one
UPDATE judge_tasks
SET status = 'done',
    updated_at = now()
WHERE id = $1
RETURNING id, submission_id, stream_id, status, attempts, next_run_at, last_error, created_at, updated_at
`

func (q *Queries) MarkJudgeTaskDone(ctx context.Context, id int64) (JudgeTask, error) {
	row := q.db.QueryRow(ctx, markJudgeTaskDone, id)
	var i JudgeTask
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.StreamID,
		&i.Status,
		&i.Attempts,
		&i.NextRunAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const retryJudgeTask = `-- name: RetryJudgeTask :one
UPDATE judge_tasks
SET status = 'pending',
    attempts = attempts + 1,
    next_run_at = $1,
    last_error = $2,
    updated_at = now()
WHERE id = $3
RETURNING id, submission_id, stream_id, status, attempts, next_run_at, last_error, created_at, updated_at
`

type RetryJudgeTaskParams struct {
	NextRunAt pgtype.Timestamptz `db:"next_run_at" json:"next_run_at"`
	LastError pgtype.Text        `db:"last_error" json:"last_error"`
	ID        int64              `db:"id" json:"id"`
}

func (q *Queries) RetryJudgeTask(ctx context.Context, arg RetryJudgeTaskParams) (JudgeTask, error) {
	row := q.db.QueryRow(ctx, retryJudgeTask, arg.NextRunAt, arg.LastError, arg.ID)
	var i JudgeTask
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.StreamID,
		&i.Status,
		&i.Attempts,
		&i.NextRunAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateJudgeTaskDispatching = `-- name: UpdateJudgeTaskDispatching :one
UPDATE judge_tasks
SET status = 'dispatching',
    updated_at = now()
WHERE id = $1
  AND status = 'pending'
RETURNING id, submission_id, stream_id, status, attempts, next_run_at, last_error, created_at, updated_at
`

func (q *Queries) UpdateJudgeTaskDispatching(ctx context.Context, id int64) (JudgeTask, error) {
	row := q.db.QueryRow(ctx, updateJudgeTaskDispatching, id)
	var i JudgeTask
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.StreamID,
		&i.Status,
		&i.Attempts,
		&i.NextRunAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRunStatus = `-- name: UpdateRunStatus :one
UPDATE runs
SET status = $1,
    stdout = $2,
    stderr = $3,
    compile_output = $4,
    time_ms = $5,
    memory_kb = $6,
    error_message = $7,
    finished_at = CASE
        WHEN finished_at IS NULL
          AND $1::text IN ('accepted', 'wrong_answer', 'compile_error', 'runtime_error', 'time_limit', 'memory_limit', 'system_error', 'canceled') THEN now()
        ELSE finished_at
    END,
    updated_at = now()
WHERE id = $8
RETURNING id, user_id, problem_id, language_id, status, source_artifact_id, stdin, stdout, stderr, compile_output, time_ms, memory_kb, error_message, created_at, finished_at, updated_at
`

type UpdateRunStatusParams struct {
	Status        string      `db:"status" json:"status"`
	Stdout        pgtype.Text `db:"stdout" json:"stdout"`
	Stderr        pgtype.Text `db:"stderr" json:"stderr"`
	CompileOutput pgtype.Text `db:"compile_output" json:"compile_output"`
	TimeMs        pgtype.Int4 `db:"time_ms" json:"time_ms"`
	MemoryKb      pgtype.Int4 `db:"memory_kb" json:"memory_kb"`
	ErrorMessage  pgtype.Text `db:"error_message" json:"error_message"`
	ID            int64       `db:"id" json:"id"`
}

func (q *Queries) UpdateRunStatus(ctx context.Context, arg UpdateRunStatusParams) (Run, error) {
	row := q.db.QueryRow(ctx, updateRunStatus,
		arg.Status,
		arg.Stdout,
		arg.Stderr,
		arg.CompileOutput,
		arg.TimeMs,
		arg.MemoryKb,
		arg.ErrorMessage,
		arg.ID,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProblemID,
		&i.LanguageID,
		&i.Status,
		&i.SourceArtifactID,
		&i.Stdin,
		&i.Stdout,
		&i.Stderr,
		&i.CompileOutput,
		&i.TimeMs,
		&i.MemoryKb,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSubmissionStatus = `-- name: UpdateSubmissionStatus :one
UPDATE submissions
SET status = $1,
    time_ms = $2,
    memory_kb = $3,
    score = coalesce($4, score),
    error_message = $5,
    judged_at = CASE
        WHEN judged_at IS NULL
          AND $1::text IN ('accepted', 'wrong_answer', 'compile_error', 'runtime_error', 'time_limit', 'memory_limit', 'system_error', 'canceled') THEN now()
        ELSE judged_at
    END,
    updated_at = now()
WHERE id = $6
RETURNING id, user_id, problem_id, contest_id, language_id, testcase_set_id, status, source_artifact_id, time_ms, memory_kb, score, error_message, submitted_at, judged_at, updated_at
`

type UpdateSubmissionStatusParams struct {
	Status       string      `db:"status" json:"status"`
	TimeMs       pgtype.Int4 `db:"time_ms" json:"time_ms"`
	MemoryKb     pgtype.Int4 `db:"memory_kb" json:"memory_kb"`
	Score        pgtype.Int4 `db:"score" json:"score"`
	ErrorMessage pgtype.Text `db:"error_message" json:"error_message"`
	ID           int64       `db:"id" json:"id"`
}

func (q *Queries) UpdateSubmissionStatus(ctx context.Context, arg UpdateSubmissionStatusParams) (Submission, error) {
	row := q.db.QueryRow(ctx, updateSubmissionStatus,
		arg.Status,
		arg.TimeMs,
		arg.MemoryKb,
		arg.Score,
		arg.ErrorMessage,
		arg.ID,
	)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProblemID,
		&i.ContestID,
		&i.LanguageID,
		&i.TestcaseSetID,
		&i.Status,
		&i.SourceArtifactID,
		&i.TimeMs,
		&i.MemoryKb,
		&i.Score,
		&i.ErrorMessage,
		&i.SubmittedAt,
		&i.JudgedAt,
		&i.UpdatedAt,
	)
	return i, err
}
