// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT count(*)::bigint
FROM users
WHERE ($1::text IS NULL OR status = $1::text)
  AND (
      $2::text IS NULL
      OR email ILIKE '%' || $2::text || '%'
      OR username ILIKE '%' || $2::text || '%'
  )
`

type CountUsersParams struct {
	Status  pgtype.Text `db:"status" json:"status"`
	Keyword pgtype.Text `db:"keyword" json:"keyword"`
}

func (q *Queries) CountUsers(ctx context.Context, arg CountUsersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers, arg.Status, arg.Keyword)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (
    user_id,
    token_hash,
    device_id,
    user_agent,
    ip,
    expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, user_id, token_hash, device_id, user_agent, ip, expires_at, revoked_at, created_at
`

type CreateRefreshTokenParams struct {
	UserID    int64              `db:"user_id" json:"user_id"`
	TokenHash string             `db:"token_hash" json:"token_hash"`
	DeviceID  string             `db:"device_id" json:"device_id"`
	UserAgent pgtype.Text        `db:"user_agent" json:"user_agent"`
	Ip        *netip.Addr        `db:"ip" json:"ip"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.UserID,
		arg.TokenHash,
		arg.DeviceID,
		arg.UserAgent,
		arg.Ip,
		arg.ExpiresAt,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.DeviceID,
		&i.UserAgent,
		&i.Ip,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (
    email,
    password_hash,
    username,
    avatar_url,
    bio,
    status
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, email, password_hash, username, avatar_url, bio, status, created_at, updated_at
`

type CreateUserParams struct {
	Email        string      `db:"email" json:"email"`
	PasswordHash string      `db:"password_hash" json:"password_hash"`
	Username     string      `db:"username" json:"username"`
	AvatarUrl    pgtype.Text `db:"avatar_url" json:"avatar_url"`
	Bio          pgtype.Text `db:"bio" json:"bio"`
	Status       string      `db:"status" json:"status"`
}

// Owner: WP2 Auth/User
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.Username,
		arg.AvatarUrl,
		arg.Bio,
		arg.Status,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Username,
		&i.AvatarUrl,
		&i.Bio,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, user_id, token_hash, device_id, user_agent, ip, expires_at, revoked_at, created_at
FROM refresh_tokens
WHERE token_hash = $1
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.DeviceID,
		&i.UserAgent,
		&i.Ip,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, username, avatar_url, bio, status, created_at, updated_at
FROM users
WHERE lower(email) = lower($1)
`

func (q *Queries) GetUserByEmail(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Username,
		&i.AvatarUrl,
		&i.Bio,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, username, avatar_url, bio, status, created_at, updated_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Username,
		&i.AvatarUrl,
		&i.Bio,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, password_hash, username, avatar_url, bio, status, created_at, updated_at
FROM users
WHERE ($1::text IS NULL OR status = $1::text)
  AND (
      $2::text IS NULL
      OR email ILIKE '%' || $2::text || '%'
      OR username ILIKE '%' || $2::text || '%'
  )
ORDER BY created_at DESC, id DESC
LIMIT $4 OFFSET $3
`

type ListUsersParams struct {
	Status  pgtype.Text `db:"status" json:"status"`
	Keyword pgtype.Text `db:"keyword" json:"keyword"`
	Offset  int32       `db:"offset" json:"offset"`
	Limit   int32       `db:"limit" json:"limit"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers,
		arg.Status,
		arg.Keyword,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.Username,
			&i.AvatarUrl,
			&i.Bio,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens
SET revoked_at = now()
WHERE token_hash = $1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, tokenHash)
	return err
}

const revokeUserDeviceRefreshTokens = `-- name: RevokeUserDeviceRefreshTokens :exec
UPDATE refresh_tokens
SET revoked_at = now()
WHERE user_id = $1
  AND device_id = $2
  AND revoked_at IS NULL
`

type RevokeUserDeviceRefreshTokensParams struct {
	UserID   int64  `db:"user_id" json:"user_id"`
	DeviceID string `db:"device_id" json:"device_id"`
}

func (q *Queries) RevokeUserDeviceRefreshTokens(ctx context.Context, arg RevokeUserDeviceRefreshTokensParams) error {
	_, err := q.db.Exec(ctx, revokeUserDeviceRefreshTokens, arg.UserID, arg.DeviceID)
	return err
}

const updateUserAdminFields = `-- name: UpdateUserAdminFields :one
UPDATE users
SET username = coalesce($1, username),
    bio = coalesce($2, bio),
    status = coalesce($3, status),
    updated_at = now()
WHERE id = $4
RETURNING id, email, password_hash, username, avatar_url, bio, status, created_at, updated_at
`

type UpdateUserAdminFieldsParams struct {
	Username pgtype.Text `db:"username" json:"username"`
	Bio      pgtype.Text `db:"bio" json:"bio"`
	Status   pgtype.Text `db:"status" json:"status"`
	ID       int64       `db:"id" json:"id"`
}

func (q *Queries) UpdateUserAdminFields(ctx context.Context, arg UpdateUserAdminFieldsParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserAdminFields,
		arg.Username,
		arg.Bio,
		arg.Status,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Username,
		&i.AvatarUrl,
		&i.Bio,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
