version: "2"

linters:
  default: none
  enable:
    - errcheck
    - errname
    - errorlint
    - gocritic
    - govet
    - misspell
    - prealloc
    - staticcheck
    - unconvert
    - unparam
    - unused

formatters:
  enable:
    - gofmt

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
