version: '3'

services:
  mysql:
    image: mysql:8.0.33
    container_name: soj_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: m81rwSo2rF1wrkhlfYDV
    command:
      ["--default-authentication-plugin=mysql_native_password"]
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - soj-net


  mongo:
    image: mongo:latest
    container_name: soj_mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: soj
      MONGO_INITDB_ROOT_PASSWORD: 61Sq8PmDYMDnK090nvpr
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - soj-net

  rabbitmq:
    image: rabbitmq:latest
    container_name: soj_rabbitmq
    restart: unless-stopped
    hostname: myRabbit
    environment:
      RABBITMQ_DEFAULT_VHOST: soj
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: aELzJq0VXxN3fUcTcEDH
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    command: ["/bin/bash", "-c", "rabbitmq-plugins enable --offline rabbitmq_management && rabbitmq-server"]
    networks:
      - soj-net

  judge0_server:
    image: 513254687/soj:1.0
    container_name: soj_judge0_server
    restart: unless-stopped
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    ports:
      - "2358:2358"
    privileged: true
    depends_on:
      - judge0_db
      - judge0_redis
    networks:
      - soj-net

  judge0_workers:
    image: 513254687/soj:1.0
    container_name: soj_judge0_workers
    restart: unless-stopped
    command: ["./scripts/workers"]
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    privileged: true
    depends_on:
      - judge0_server
    networks:
      - soj-net

  judge0_db:
    image: postgres:16.2
    container_name: soj_judge0_postgres
    restart: unless-stopped
    env_file:
      - judge0.conf
    volumes:
      - judge0_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - soj-net

  judge0_redis:
    image: redis:7.2.4
    container_name: soj_judge0_redis
    restart: unless-stopped
    command: [
      "bash", "-c",
      'docker-entrypoint.sh --appendonly no --requirepass "$$REDIS_PASSWORD"'
    ]
    env_file:
      - judge0.conf
    ports:
      - "6379:6379"
    volumes:
      - judge0_redis_data:/data
    networks:
      - soj-net

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: soj_backend
    ports:
      - "8888:8888"
    volumes:
      - ./config:/app/config
    depends_on:
      - mysql
      - redis
      - mongo
      - rabbitmq
    networks:
      - soj-net

volumes:
  mysql-data:
  redis-data:
  mongo-data:
  rabbitmq-data:
  judge0_db_data:
  judge0_redis_data:

networks:
  soj-net:
    driver: bridge
