// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package initialize

import (
	"SOJ/internal/handle"
	"SOJ/internal/mq"
	"SOJ/internal/repository"
	"SOJ/internal/service"
	"SOJ/pkg/email"
	"SOJ/utils/captcha"
	"SOJ/utils/jwt"
)

// Injectors from wire.go:

func InitServer() *Cmd {
	client := InitRedis()
	logger := InitLogger()
	redisStore := captcha.NewRedisStore(client, logger)
	captchaCaptcha := captcha.New(redisStore)
	captchaHandle := handle.NewCaptchaHandle(captchaCaptcha, logger)
	emailProducer := mq.NewEmailProducer(logger)
	emailService := service.NewEmailService(logger, client, emailProducer, captchaCaptcha)
	emailHandle := handle.NewEmailHandle(emailService)
	jwtJWT := jwt.New(client, logger)
	db := InitDB()
	userRepository := repository.NewUserRepository(logger, db, client)
	cosClient := InitCos()
	userService := service.NewUserService(logger, userRepository, client, cosClient, emailService, captchaCaptcha)
	userHandle := handle.NewUserHandle(logger, jwtJWT, userService)
	database := InitMongoDB()
	problemRepository := repository.NewProblemRepository(logger, db, database)
	problemService := service.NewProblemService(logger, problemRepository)
	problemHandle := handle.NewProblemHandle(logger, problemService)
	v := InitMiddleware(jwtJWT)
	engine := InitRoute(captchaHandle, emailHandle, userHandle, problemHandle, v)
	emailEmail := email.New(logger)
	emailConsumer := mq.NewEmailConsumer(logger, emailEmail, emailProducer, client)
	cmd := &Cmd{
		G:             engine,
		EmailConsumer: emailConsumer,
		Mongo:         database,
		DB:            db,
	}
	return cmd
}
