// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package initialize

import (
	"SOJ/internal/api"
	"SOJ/internal/mq"
	"SOJ/pkg/email"
	"SOJ/utils/jwt"
)

// Injectors from wire.go:

func InitServer() *Cmd {
	logger := InitLogger()
	client := InitRedis()
	jwtJWT := jwt.New(client, logger)
	v := InitMiddleware(jwtJWT, logger)
	emailProducer := mq.NewEmailProducer(logger)
	userAPI := api.NewUserAPI(logger, jwtJWT, v, emailProducer)
	emailEmail := email.New(logger)
	emailConsumer := mq.NewEmailConsumer(logger, emailEmail, emailProducer)
	cmd := &Cmd{
		UserAPI:       userAPI,
		EmailConsumer: emailConsumer,
	}
	return cmd
}
