-- SOJ v2 initial schema. This migration targets an empty PostgreSQL database.

CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email text NOT NULL,
    password_hash text NOT NULL,
    username text NOT NULL,
    avatar_url text,
    bio text,
    role text NOT NULL DEFAULT 'user' CHECK (role IN ('user', 'admin', 'root')),
    status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled', 'deleted')),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX users_email_lower_uidx ON users (lower(email));
CREATE INDEX users_status_idx ON users (status);
CREATE INDEX users_role_idx ON users (role);

CREATE TABLE refresh_tokens (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash text NOT NULL,
    device_id text NOT NULL,
    user_agent text,
    ip inet,
    expires_at timestamptz NOT NULL,
    revoked_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX refresh_tokens_token_hash_uidx ON refresh_tokens (token_hash);
CREATE INDEX refresh_tokens_user_id_idx ON refresh_tokens (user_id);
CREATE INDEX refresh_tokens_expires_at_idx ON refresh_tokens (expires_at);
CREATE INDEX refresh_tokens_active_idx ON refresh_tokens (user_id, device_id) WHERE revoked_at IS NULL;

CREATE TABLE problems (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id bigint NOT NULL REFERENCES users(id),
    title text NOT NULL,
    slug text NOT NULL,
    difficulty text NOT NULL CHECK (difficulty IN ('easy', 'medium', 'hard')),
    visibility text NOT NULL CHECK (visibility IN ('private', 'public', 'contest_only')),
    status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'published', 'archived')),
    time_limit_ms integer NOT NULL CHECK (time_limit_ms > 0),
    memory_limit_kb integer NOT NULL CHECK (memory_limit_kb > 0),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    published_at timestamptz
);

CREATE UNIQUE INDEX problems_slug_uidx ON problems (slug);
CREATE INDEX problems_status_visibility_idx ON problems (status, visibility);
CREATE INDEX problems_owner_user_id_idx ON problems (owner_user_id);
CREATE INDEX problems_difficulty_idx ON problems (difficulty);

CREATE TABLE problem_tags (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    slug text NOT NULL
);

CREATE UNIQUE INDEX problem_tags_slug_uidx ON problem_tags (slug);

CREATE TABLE problem_tag_links (
    problem_id bigint NOT NULL REFERENCES problems(id) ON DELETE CASCADE,
    tag_id bigint NOT NULL REFERENCES problem_tags(id) ON DELETE CASCADE,
    PRIMARY KEY (problem_id, tag_id)
);

CREATE INDEX problem_tag_links_tag_id_idx ON problem_tag_links (tag_id);

CREATE TABLE problem_statements (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    problem_id bigint NOT NULL REFERENCES problems(id) ON DELETE CASCADE,
    version integer NOT NULL CHECK (version > 0),
    title text NOT NULL,
    description text NOT NULL,
    input_description text,
    output_description text,
    samples jsonb NOT NULL DEFAULT '[]'::jsonb,
    hint text,
    source text,
    is_current boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX problem_statements_problem_version_uidx ON problem_statements (problem_id, version);
CREATE UNIQUE INDEX problem_statements_current_uidx ON problem_statements (problem_id) WHERE is_current;
CREATE INDEX problem_statements_problem_id_idx ON problem_statements (problem_id);

CREATE TABLE testcase_sets (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    problem_id bigint NOT NULL REFERENCES problems(id) ON DELETE CASCADE,
    version integer NOT NULL CHECK (version > 0),
    storage_key text NOT NULL,
    checksum_sha256 text NOT NULL,
    size_bytes bigint NOT NULL CHECK (size_bytes >= 0),
    case_count integer NOT NULL CHECK (case_count > 0),
    status text NOT NULL CHECK (status IN ('uploading', 'ready', 'disabled')),
    is_current boolean NOT NULL DEFAULT false,
    created_by bigint NOT NULL REFERENCES users(id),
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX testcase_sets_problem_version_uidx ON testcase_sets (problem_id, version);
CREATE INDEX testcase_sets_problem_ready_idx ON testcase_sets (problem_id) WHERE status = 'ready';
CREATE UNIQUE INDEX testcase_sets_current_uidx ON testcase_sets (problem_id) WHERE is_current;

CREATE TABLE languages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    engine text NOT NULL,
    engine_language_id text NOT NULL,
    name text NOT NULL,
    version text,
    compile_command text,
    run_command text,
    default_time_limit_ms integer NOT NULL CHECK (default_time_limit_ms > 0),
    default_memory_limit_kb integer NOT NULL CHECK (default_memory_limit_kb > 0),
    enabled boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX languages_engine_language_uidx ON languages (engine, engine_language_id);
CREATE INDEX languages_enabled_idx ON languages (enabled);

CREATE TABLE contests (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id bigint NOT NULL REFERENCES users(id),
    title text NOT NULL,
    description text,
    visibility text NOT NULL CHECK (visibility IN ('public', 'private')),
    status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'published', 'running', 'ended', 'archived')),
    start_at timestamptz NOT NULL,
    end_at timestamptz NOT NULL,
    freeze_at timestamptz NOT NULL,
    invite_code_hash text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK (start_at < end_at),
    CHECK (freeze_at >= start_at AND freeze_at <= end_at)
);

CREATE INDEX contests_status_start_idx ON contests (status, start_at);
CREATE INDEX contests_owner_user_id_idx ON contests (owner_user_id);
CREATE INDEX contests_visibility_idx ON contests (visibility);

CREATE TABLE contest_problems (
    contest_id bigint NOT NULL REFERENCES contests(id) ON DELETE CASCADE,
    problem_id bigint NOT NULL REFERENCES problems(id),
    alias text NOT NULL,
    sort_order integer NOT NULL CHECK (sort_order > 0),
    PRIMARY KEY (contest_id, problem_id)
);

CREATE UNIQUE INDEX contest_problems_alias_uidx ON contest_problems (contest_id, alias);
CREATE UNIQUE INDEX contest_problems_sort_uidx ON contest_problems (contest_id, sort_order);

CREATE TABLE contest_registrations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contest_id bigint NOT NULL REFERENCES contests(id) ON DELETE CASCADE,
    user_id bigint NOT NULL REFERENCES users(id),
    display_name text NOT NULL,
    email text NOT NULL,
    status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'canceled')),
    registered_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX contest_registrations_contest_user_uidx ON contest_registrations (contest_id, user_id);
CREATE INDEX contest_registrations_user_id_idx ON contest_registrations (user_id);
CREATE INDEX contest_registrations_contest_status_idx ON contest_registrations (contest_id, status);

CREATE TABLE artifacts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_type text NOT NULL CHECK (owner_type IN ('submission', 'run', 'problem', 'testcase')),
    owner_id bigint NOT NULL,
    kind text NOT NULL CHECK (kind IN ('source', 'stdout', 'stderr', 'compile_output', 'judge_log', 'attachment', 'testcase_archive')),
    storage_key text NOT NULL,
    checksum_sha256 text NOT NULL,
    size_bytes bigint NOT NULL CHECK (size_bytes >= 0),
    content_type text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX artifacts_owner_idx ON artifacts (owner_type, owner_id);
CREATE INDEX artifacts_kind_idx ON artifacts (kind);
CREATE UNIQUE INDEX artifacts_storage_key_uidx ON artifacts (storage_key);

CREATE TABLE submissions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id),
    problem_id bigint NOT NULL REFERENCES problems(id),
    contest_id bigint REFERENCES contests(id),
    language_id bigint NOT NULL REFERENCES languages(id),
    testcase_set_id bigint NOT NULL REFERENCES testcase_sets(id),
    status text NOT NULL DEFAULT 'queued' CHECK (
        status IN ('queued', 'running', 'accepted', 'wrong_answer', 'compile_error', 'runtime_error', 'time_limit', 'memory_limit', 'system_error', 'canceled')
    ),
    source_artifact_id bigint REFERENCES artifacts(id),
    time_ms integer CHECK (time_ms IS NULL OR time_ms >= 0),
    memory_kb integer CHECK (memory_kb IS NULL OR memory_kb >= 0),
    score integer NOT NULL DEFAULT 0 CHECK (score >= 0),
    error_message text,
    submitted_at timestamptz NOT NULL DEFAULT now(),
    judged_at timestamptz,
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX submissions_user_submitted_idx ON submissions (user_id, submitted_at DESC);
CREATE INDEX submissions_problem_status_idx ON submissions (problem_id, status);
CREATE INDEX submissions_contest_submitted_idx ON submissions (contest_id, submitted_at DESC);
CREATE INDEX submissions_status_updated_idx ON submissions (status, updated_at);
CREATE INDEX submissions_language_id_idx ON submissions (language_id);

CREATE TABLE judge_tasks (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id bigint NOT NULL REFERENCES submissions(id),
    stream_id text,
    status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'dispatching', 'dispatched', 'running', 'done', 'dead')),
    attempts integer NOT NULL DEFAULT 0 CHECK (attempts >= 0),
    next_run_at timestamptz NOT NULL DEFAULT now(),
    last_error text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX judge_tasks_submission_id_uidx ON judge_tasks (submission_id);
CREATE INDEX judge_tasks_status_next_run_idx ON judge_tasks (status, next_run_at);
CREATE INDEX judge_tasks_stream_id_idx ON judge_tasks (stream_id);

CREATE TABLE runs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id),
    problem_id bigint NOT NULL REFERENCES problems(id),
    language_id bigint NOT NULL REFERENCES languages(id),
    status text NOT NULL DEFAULT 'queued' CHECK (
        status IN ('queued', 'running', 'accepted', 'wrong_answer', 'compile_error', 'runtime_error', 'time_limit', 'memory_limit', 'system_error', 'canceled')
    ),
    source_artifact_id bigint REFERENCES artifacts(id),
    stdin text,
    stdout text,
    stderr text,
    compile_output text,
    time_ms integer CHECK (time_ms IS NULL OR time_ms >= 0),
    memory_kb integer CHECK (memory_kb IS NULL OR memory_kb >= 0),
    error_message text,
    created_at timestamptz NOT NULL DEFAULT now(),
    finished_at timestamptz,
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX runs_user_created_idx ON runs (user_id, created_at DESC);
CREATE INDEX runs_status_updated_idx ON runs (status, updated_at);
CREATE INDEX runs_problem_id_idx ON runs (problem_id);

CREATE TABLE submission_results (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id bigint NOT NULL REFERENCES submissions(id) ON DELETE CASCADE,
    status text NOT NULL CHECK (
        status IN ('accepted', 'wrong_answer', 'compile_error', 'runtime_error', 'time_limit', 'memory_limit', 'system_error', 'canceled')
    ),
    score integer NOT NULL DEFAULT 0 CHECK (score >= 0),
    time_ms integer CHECK (time_ms IS NULL OR time_ms >= 0),
    memory_kb integer CHECK (memory_kb IS NULL OR memory_kb >= 0),
    details jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX submission_results_submission_id_uidx ON submission_results (submission_id);

CREATE TABLE contest_problem_results (
    contest_id bigint NOT NULL REFERENCES contests(id) ON DELETE CASCADE,
    user_id bigint NOT NULL REFERENCES users(id),
    problem_id bigint NOT NULL REFERENCES problems(id),
    status text NOT NULL DEFAULT 'none' CHECK (status IN ('none', 'attempted', 'accepted', 'frozen')),
    attempts integer NOT NULL DEFAULT 0 CHECK (attempts >= 0),
    accepted_at timestamptz,
    penalty_minutes integer NOT NULL DEFAULT 0 CHECK (penalty_minutes >= 0),
    last_submission_id bigint REFERENCES submissions(id),
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (contest_id, user_id, problem_id)
);

CREATE INDEX contest_problem_results_contest_problem_idx ON contest_problem_results (contest_id, problem_id);
CREATE INDEX contest_problem_results_last_submission_idx ON contest_problem_results (last_submission_id);

CREATE TABLE contest_score_snapshots (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contest_id bigint NOT NULL REFERENCES contests(id) ON DELETE CASCADE,
    kind text NOT NULL CHECK (kind IN ('live', 'frozen', 'final')),
    payload jsonb NOT NULL,
    generated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX contest_score_snapshots_contest_kind_generated_idx ON contest_score_snapshots (contest_id, kind, generated_at DESC);
