ALTER TABLE problems
    DROP CONSTRAINT problems_status_check;

ALTER TABLE problems
    ADD CONSTRAINT problems_status_check
    CHECK (status IN ('draft', 'in_review', 'changes_requested', 'published', 'archived'));

CREATE TABLE problem_review_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    problem_id bigint NOT NULL REFERENCES problems(id) ON DELETE CASCADE,
    actor_user_id bigint NOT NULL REFERENCES users(id),
    from_status text NOT NULL,
    to_status text NOT NULL,
    decision text NOT NULL CHECK (decision IN ('submit', 'approve', 'request_changes')),
    comment text NOT NULL DEFAULT '',
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX problem_review_events_problem_created_idx
    ON problem_review_events (problem_id, created_at DESC, id DESC);
CREATE INDEX problem_review_events_queue_idx
    ON problems (status, updated_at DESC, id DESC)
    WHERE status = 'in_review';
