-- One audit ledger for administrative actions: who did what to which object,
-- when. Every object type shares the table because the read pattern is the
-- same for all of them ("this object's history" / "this operator's history");
-- per-domain tables would only force a union in front of those two queries.
--
-- role_audit_events is folded in and dropped: a role change is an
-- administrative action like any other, and two ledgers would mean two write
-- paths and two query paths for one concept.
CREATE TABLE audit_events (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id bigint REFERENCES users(id) ON DELETE SET NULL,
    action        text NOT NULL CHECK (action IN (
        'user.role.granted',
        'user.role.revoked',
        'user.disabled',
        'user.enabled',
        'user.deleted',
        'language.enabled',
        'language.disabled',
        'problem.archived',
        'problem.restored',
        'contest.archived'
    )),
    object_type   text NOT NULL CHECK (object_type IN ('user', 'language', 'problem', 'contest')),
    object_id     bigint NOT NULL,
    reason        text NOT NULL DEFAULT '',
    metadata      jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at    timestamptz NOT NULL DEFAULT now()
);

-- Three read paths, three indexes:
-- 1. the unfiltered timeline (also the fallback for low-selectivity filters);
CREATE INDEX audit_events_created_idx ON audit_events (created_at DESC, id DESC);
-- 2. "everything that happened to this object";
CREATE INDEX audit_events_object_idx ON audit_events (object_type, object_id, created_at DESC, id DESC);
-- 3. "everything this operator did", which also serves the actor_user_id
--    foreign key's reverse lookup.
CREATE INDEX audit_events_actor_idx ON audit_events (actor_user_id, created_at DESC, id DESC);

INSERT INTO audit_events (actor_user_id, action, object_type, object_id, reason, metadata, created_at)
SELECT
    actor_user_id,
    CASE action WHEN 'granted' THEN 'user.role.granted' ELSE 'user.role.revoked' END,
    'user',
    user_id,
    reason,
    jsonb_build_object('role', role_code),
    created_at
FROM role_audit_events
ORDER BY id;

DROP TABLE role_audit_events;

-- Problems need their pre-archive status to be restorable to the state they
-- were taken down from. Restoring every problem to 'draft' would silently
-- demote re-listed published problems into the review workflow; restoring
-- every problem to 'published' would let an archived draft skip review.
ALTER TABLE problems
    ADD COLUMN archived_from_status text CHECK (archived_from_status IN ('draft', 'in_review', 'changes_requested', 'published'));
