-- Contest roles are resource-scoped and must never enter global user assignments.

ALTER TABLE roles
    DROP CONSTRAINT IF EXISTS roles_code_check;

ALTER TABLE roles
    DROP CONSTRAINT IF EXISTS roles_scope_check;

ALTER TABLE roles
    ADD CONSTRAINT roles_code_check
    CHECK (code IN (
        'user', 'author', 'reviewer', 'operator', 'admin', 'root',
        'contest_staff', 'contest_manager', 'contest_judge'
    ));

ALTER TABLE roles
    ADD CONSTRAINT roles_scope_check
    CHECK (
        (code IN ('user', 'author', 'reviewer', 'operator', 'admin', 'root') AND scope = 'global')
        OR (code IN ('contest_staff', 'contest_manager', 'contest_judge') AND scope = 'contest')
    );

INSERT INTO roles (code, display_name, scope)
VALUES
    ('contest_staff', 'Contest Staff', 'contest'),
    ('contest_manager', 'Contest Manager', 'contest'),
    ('contest_judge', 'Contest Judge', 'contest')
ON CONFLICT (code) DO UPDATE
SET display_name = EXCLUDED.display_name,
    scope = EXCLUDED.scope;

ALTER TABLE user_role_assignments
    DROP CONSTRAINT IF EXISTS user_role_assignments_global_role_check;

ALTER TABLE user_role_assignments
    ADD CONSTRAINT user_role_assignments_global_role_check
    CHECK (role_code IN ('user', 'author', 'reviewer', 'operator', 'admin', 'root'));

CREATE TABLE contest_role_assignments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contest_id bigint NOT NULL REFERENCES contests(id) ON DELETE CASCADE,
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role_code text NOT NULL REFERENCES roles(code),
    granted_by bigint REFERENCES users(id) ON DELETE SET NULL,
    granted_at timestamptz NOT NULL DEFAULT now(),
    revoked_at timestamptz,
    CHECK (role_code IN ('contest_staff', 'contest_manager', 'contest_judge')),
    CHECK (granted_by IS NULL OR granted_by <> user_id)
);

CREATE UNIQUE INDEX contest_role_assignments_active_uidx
    ON contest_role_assignments (contest_id, user_id, role_code)
    WHERE revoked_at IS NULL;
CREATE INDEX contest_role_assignments_user_contest_idx
    ON contest_role_assignments (user_id, contest_id, role_code)
    WHERE revoked_at IS NULL;
CREATE INDEX contest_role_assignments_contest_role_idx
    ON contest_role_assignments (contest_id, role_code, user_id)
    WHERE revoked_at IS NULL;

CREATE TABLE contest_role_audit_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contest_id bigint NOT NULL REFERENCES contests(id) ON DELETE CASCADE,
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role_code text NOT NULL REFERENCES roles(code),
    actor_user_id bigint REFERENCES users(id) ON DELETE SET NULL,
    action text NOT NULL CHECK (action IN ('granted', 'revoked')),
    reason text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CHECK (role_code IN ('contest_staff', 'contest_manager', 'contest_judge'))
);

CREATE INDEX contest_role_audit_events_contest_created_idx
    ON contest_role_audit_events (contest_id, created_at DESC, id DESC);
CREATE INDEX contest_role_audit_events_user_created_idx
    ON contest_role_audit_events (user_id, created_at DESC, id DESC);
