-- Contest roles are resource-scoped and must never enter global user assignments.

-- 000001_init originally stored roles on users. That migration is already
-- recorded on databases created before RBAC was released, so bootstrap the
-- RBAC tables here before applying the contest-scoped role changes.
CREATE TABLE IF NOT EXISTS roles (
    code text PRIMARY KEY CHECK (code IN ('user', 'author', 'reviewer', 'operator', 'admin', 'root')),
    display_name text NOT NULL,
    scope text NOT NULL DEFAULT 'global' CHECK (scope = 'global'),
    system_role boolean NOT NULL DEFAULT true
);

INSERT INTO roles (code, display_name, scope, system_role)
VALUES
    ('user', 'User', 'global', true),
    ('author', 'Author', 'global', true),
    ('reviewer', 'Reviewer', 'global', true),
    ('operator', 'Operator', 'global', true),
    ('admin', 'Administrator', 'global', true),
    ('root', 'Root Administrator', 'global', true)
ON CONFLICT (code) DO UPDATE
SET display_name = EXCLUDED.display_name,
    scope = EXCLUDED.scope,
    system_role = EXCLUDED.system_role;

CREATE TABLE IF NOT EXISTS user_role_assignments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role_code text NOT NULL REFERENCES roles(code),
    granted_by bigint REFERENCES users(id) ON DELETE SET NULL,
    granted_at timestamptz NOT NULL DEFAULT now(),
    revoked_at timestamptz,
    CHECK (granted_by IS NULL OR granted_by <> user_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS user_role_assignments_active_uidx
    ON user_role_assignments (user_id, role_code)
    WHERE revoked_at IS NULL;
CREATE INDEX IF NOT EXISTS user_role_assignments_user_idx
    ON user_role_assignments (user_id, granted_at DESC);
CREATE INDEX IF NOT EXISTS user_role_assignments_role_idx
    ON user_role_assignments (role_code, user_id)
    WHERE revoked_at IS NULL;

CREATE TABLE IF NOT EXISTS role_audit_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role_code text NOT NULL REFERENCES roles(code),
    actor_user_id bigint REFERENCES users(id) ON DELETE SET NULL,
    action text NOT NULL CHECK (action IN ('granted', 'revoked')),
    reason text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS role_audit_events_user_created_idx
    ON role_audit_events (user_id, created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS role_audit_events_actor_created_idx
    ON role_audit_events (actor_user_id, created_at DESC, id DESC);

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = current_schema()
          AND table_name = 'users'
          AND column_name = 'role'
    ) THEN
        EXECUTE $sql$
            INSERT INTO user_role_assignments (user_id, role_code, granted_at)
            SELECT u.id, u.role, now()
            FROM users AS u
            WHERE u.role IN ('user', 'admin', 'root')
              AND NOT EXISTS (
                  SELECT 1
                  FROM user_role_assignments AS a
                  WHERE a.user_id = u.id
                    AND a.role_code = u.role
                    AND a.revoked_at IS NULL
              )
        $sql$;
    END IF;
END
$$;

ALTER TABLE roles
    DROP CONSTRAINT IF EXISTS roles_code_check;

ALTER TABLE roles
    DROP CONSTRAINT IF EXISTS roles_scope_check;

ALTER TABLE roles
    ADD CONSTRAINT roles_code_check
    CHECK (code IN (
        'user', 'author', 'reviewer', 'operator', 'admin', 'root',
        'contest_staff', 'contest_manager', 'contest_judge'
    ));

ALTER TABLE roles
    ADD CONSTRAINT roles_scope_check
    CHECK (
        (code IN ('user', 'author', 'reviewer', 'operator', 'admin', 'root') AND scope = 'global')
        OR (code IN ('contest_staff', 'contest_manager', 'contest_judge') AND scope = 'contest')
    );

INSERT INTO roles (code, display_name, scope)
VALUES
    ('contest_staff', 'Contest Staff', 'contest'),
    ('contest_manager', 'Contest Manager', 'contest'),
    ('contest_judge', 'Contest Judge', 'contest')
ON CONFLICT (code) DO UPDATE
SET display_name = EXCLUDED.display_name,
    scope = EXCLUDED.scope;

ALTER TABLE user_role_assignments
    DROP CONSTRAINT IF EXISTS user_role_assignments_global_role_check;

ALTER TABLE user_role_assignments
    ADD CONSTRAINT user_role_assignments_global_role_check
    CHECK (role_code IN ('user', 'author', 'reviewer', 'operator', 'admin', 'root'));

CREATE TABLE contest_role_assignments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contest_id bigint NOT NULL REFERENCES contests(id) ON DELETE CASCADE,
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role_code text NOT NULL REFERENCES roles(code),
    granted_by bigint REFERENCES users(id) ON DELETE SET NULL,
    granted_at timestamptz NOT NULL DEFAULT now(),
    revoked_at timestamptz,
    CHECK (role_code IN ('contest_staff', 'contest_manager', 'contest_judge')),
    CHECK (granted_by IS NULL OR granted_by <> user_id)
);

CREATE UNIQUE INDEX contest_role_assignments_active_uidx
    ON contest_role_assignments (contest_id, user_id, role_code)
    WHERE revoked_at IS NULL;
CREATE INDEX contest_role_assignments_user_contest_idx
    ON contest_role_assignments (user_id, contest_id, role_code)
    WHERE revoked_at IS NULL;
CREATE INDEX contest_role_assignments_contest_role_idx
    ON contest_role_assignments (contest_id, role_code, user_id)
    WHERE revoked_at IS NULL;

CREATE TABLE contest_role_audit_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contest_id bigint NOT NULL REFERENCES contests(id) ON DELETE CASCADE,
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role_code text NOT NULL REFERENCES roles(code),
    actor_user_id bigint REFERENCES users(id) ON DELETE SET NULL,
    action text NOT NULL CHECK (action IN ('granted', 'revoked')),
    reason text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CHECK (role_code IN ('contest_staff', 'contest_manager', 'contest_judge'))
);

CREATE INDEX contest_role_audit_events_contest_created_idx
    ON contest_role_audit_events (contest_id, created_at DESC, id DESC);
CREATE INDEX contest_role_audit_events_user_created_idx
    ON contest_role_audit_events (user_id, created_at DESC, id DESC);
