server:
  port: ":8888"

log:
  path: "logs"

mysql:
  dsn: "root:sparkyi-soj@tcp(192.168.65.131:3306)/soj?charset=utf8mb4&parseTime=True&loc=Local"

redis:
  addr: "192.168.65.131:6379"
  password: ""
  db: 0

mongo:
  uri: "mongodb://192.168.65.131:27017"
  db: "soj"
  collection_problem: "problem"
  collection_blog: "blog"

postgresql:
  dsn: "host=192.168.65.131 user=soj password=soj dbname=judge0 port=5432 sslmode=disable TimeZone=Asia/Shanghai"


email:
  host: "smtp.qq.com"
  port: 25
  username: "513254687@qq.com"
  password: ""

rabbitmq:
  url: "amqp://admin:admin@192.168.65.131/soj"
  exchange_email: "email_exchange"
  queue_email: "email_queue"

cos:
  url: "https://xxx.cos.ap-hangzhou.myqcloud.com"
  secret_id: ""
  secret_key: ""


judge0:
  addr: "192.168.65.131:2358"

jwt:
  access_secret: "fLz4d8R!1nB6hPqT@2WmK7cJ#3vL0aY9xU"
  refresh_secret: "pQ7oL3Yt*2VgD0bKzJ9x5Zf1GdN8wT4u$"
  issuer: "SOJ"
  access_expire: 1 # 1h
  refresh_expire: 720 # 24*30h